// === BASE DE DATOS DE LECCIONES: ALEMÁN (ES -> DE) ===
window.courseDe = {
    title: "Curso de Alemán",
    mission: "Misión: Nivel A1 (Grundstufe)",
    langCode: "de-DE",
    units: [
        {
            id: 1, title: "Primeros Pasos", icon: "🥨",
            levels: [
                ["Hola", "Hallo", "____!", ["Hallo", "Tschüss", "Wasser", "Brot"], "👋", "Para saludar usa <b>Hallo</b>.", "Hallo!"],
                ["Yo soy", "Ich bin", "____ Alex", ["Ich bin", "Du bist", "Er ist", "Wir sind"], "👤", "Presentarse con <b>Ich bin</b>.", "Ich bin Alex"],
                ["Uno", "Eins", "Nummer ____", ["Eins", "Zwei", "Drei", "Vier"], "1️⃣", "El número uno.", "Eins bitte"],
                ["Adiós", "Tschüss", "____!", ["Tschüss", "Hallo", "Bitte", "Danke"], "🏃", "Despedirse con <b>Tschüss</b>.", "Tschüss!"],
                ["Dos", "Zwei", "Nummer ____", ["Zwei", "Eins", "Drei", "Vier"], "2️⃣", "El número dos.", "Zwei Bier"],
                ["Por favor", "Bitte", "____, hilf mir", ["Bitte", "Danke", "Ja", "Nein"], "🙏", "Pedir cosas con <b>Bitte</b>.", "Einen Kaffee, bitte"],
                ["Gracias", "Danke", "____ für alles", ["Danke", "Bitte", "Hallo", "Nein"], "✨", "Agradecer con <b>Danke</b>.", "Danke schön"],
                ["Tres", "Drei", "Nummer ____", ["Drei", "Zwei", "Eins", "Vier"], "3️⃣", "El número tres.", "Drei Hunde"],
                ["Sí", "Ja", "____, ich bin", ["Ja", "Nein", "Vielleicht", "Nie"], "✅", "Afirmar con <b>Ja</b>.", "Ja, bitte"],
                ["No", "Nein", "____, danke", ["Nein", "Ja", "Sicher", "Immer"], "❌", "Negar con <b>Nein</b>.", "Nein, danke"],
                ["Buenos días", "Guten Morgen", "____!", ["Guten Morgen", "Gute Nacht", "Hallo", "Hi"], "🌅", "Saludo matutino.", "Guten Morgen!"],
                ["Hombre", "Mann", "Der ____", ["Mann", "Frau", "Junge", "Mädchen"], "👨", "Vocabulario: Hombre.", "Ein großer Mann"],
                ["Mujer", "Frau", "Die ____", ["Frau", "Mann", "Mädchen", "Junge"], "👩", "Vocabulario: Mujer.", "Eine starke Frau"],
                ["Niño", "Junge", "Der ____", ["Junge", "Mädchen", "Mann", "Frau"], "👦", "Vocabulario: Niño.", "Ein glücklicher Junge"],
                ["Niña", "Mädchen", "Das ____", ["Mädchen", "Junge", "Frau", "Mann"], "👧", "Vocabulario: Niña.", "Ein kleines Mädchen"],
                ["Cuatro", "Vier", "Nummer ____", ["Vier", "Drei", "Fünf", "Sechs"], "4️⃣", "El número cuatro.", "Vier Bücher"],
                ["Cinco", "Fünf", "Nummer ____", ["Fünf", "Vier", "Sechs", "Sieben"], "5️⃣", "El número cinco.", "Fünf Sterne"],
                ["Nombre", "Name", "Mein ____ ist...", ["Name", "Ist", "Ich", "Bin"], "📛", "Preguntar o decir el nombre.", "Mein Name ist Hans"],
                ["Perro", "Hund", "Mein ____", ["Hund", "Katze", "Vogel", "Fisch"], "🐶", "Mascotas: Perro.", "Ich liebe meinen Hund"],
                ["Gato", "Katze", "Meine ____", ["Katze", "Hund", "Vogel", "Maus"], "🐱", "Mascotas: Gato.", "Die schwarze Katze"]
            ].map((d, i) => ({ id: 100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 2, title: "La Ciudad", icon: "🏙️",
            levels: [
                ["Casa", "Haus", "Mein ____", ["Haus", "Auto", "Straße", "Park"], "🏠", "Donde vives.", "Mein großes Haus"],
                ["Auto", "Auto", "Das rote ____", ["Auto", "Bus", "Zug", "Flugzeug"], "🚗", "Vehículo común.", "Ich habe ein Auto"],
                ["Calle", "Straße", "Auf der ____", ["Straße", "Weg", "Haus", "Park"], "🛣️", "Por donde caminas.", "Die Hauptstraße"],
                ["Parque", "Park", "Im ____", ["Park", "Haus", "Schule", "Bank"], "🌳", "Lugar verde.", "Im Park"],
                ["Banco", "Bank", "Wo ist die ____?", ["Bank", "Café", "Park", "Laden"], "🏦", "Donde está el dinero.", "Die Zentralbank"],
                ["Tienda", "Laden", "Ein großer ____", ["Laden", "Haus", "Park", "Straße"], "🏬", "Lugar para comprar.", "Apple Laden"],
                ["Escuela", "Schule", "Geh zur ____", ["Schule", "Laden", "Bank", "Auto"], "🏫", "Lugar de estudio.", "In der Schule"],
                ["Hospital", "Krankenhaus", "Das nächste ____", ["Krankenhaus", "Park", "Café", "Bank"], "🏥", "Salud.", "Das Stadtkrankenhaus"],
                ["Café", "Café", "Lass uns ins ____ gehen", ["Café", "Laden", "Bank", "Park"], "☕", "Lugar para beber café.", "Ich mag dieses Café"],
                ["Bus", "Bus", "Nimm den ____", ["Bus", "Auto", "Fahrrad", "Taxi"], "🚌", "Transporte público.", "Der Schulbus"],
                ["Taxi", "Taxi", "Ruf ein ____", ["Taxi", "Bus", "Fahrrad", "Flugzeug"], "🚕", "Transporte privado.", "Gelbes Taxi"],
                ["Bici", "Fahrrad", "Fahr ____", ["Fahrrad", "Bus", "Auto", "Taxi"], "🚲", "Dos ruedas.", "Mein neues Fahrrad"],
                ["Tren", "Zug", "Schneller ____", ["Zug", "Bus", "Flugzeug", "Auto"], "🚆", "Vías de hierro.", "Morgenzug"],
                ["Avión", "Flugzeug", "Das ____", ["Flugzeug", "Auto", "Boot", "Bus"], "✈️", "Para volar.", "Das blaue Flugzeug"],
                ["Barco", "Boot", "Das ____", ["Boot", "Auto", "Fahrrad", "Bus"], "🚢", "Por el agua.", "Ein großes Boot"],
                ["Hotel", "Hotel", "Luxus ____", ["Hotel", "Haus", "Bank", "Park"], "🏨", "Para dormir fuera.", "Im Hotel bleiben"],
                ["Cine", "Kino", "Im ____", ["Kino", "Park", "Laden", "Bank"], "🎬", "Ver películas.", "Ins Kino gehen"],
                ["Puente", "Brücke", "Über die ____", ["Brücke", "Straße", "Weg", "Haus"], "🌉", "Une dos caminos.", "Die London Bridge"],
                ["Museo", "Museum", "Das Kunst____", ["Museum", "Laden", "Park", "Bank"], "🏛️", "Historia y arte.", "Besuche das Museum"],
                ["Policía", "Polizei", "Ruf die ____", ["Polizei", "Arzt", "Feuerwehr", "Krankenschwester"], "🚓", "Seguridad.", "Polizeistation"]
            ].map((d, i) => ({ id: 200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 3, title: "El Restaurante", icon: "🍕",
            levels: [
                ["Agua", "Wasser", "Ein Glas ____", ["Wasser", "Wein", "Saft", "Milch"], "💧", "Bebida básica.", "Ich brauche Wasser"],
                ["Pan", "Brot", "Butter und ____", ["Brot", "Kuchen", "Fleisch", "Reis"], "🍞", "Para acompañar.", "Frisches Brot"],
                ["Pizza", "Pizza", "Ich mag ____", ["Pizza", "Pasta", "Suppe", "Salat"], "🍕", "Comida italiana.", "Eine Pizza, bitte"],
                ["Carne", "Fleisch", "Iss ____", ["Fleisch", "Obst", "Brot", "Zucker"], "🥩", "Proteína.", "Gebratenes Fleisch"],
                ["Fruta", "Obst", "Frisches ____", ["Obst", "Fleisch", "Brot", "Reis"], "🍎", "Sano y dulce.", "Iss mehr Obst"],
                ["Arroz", "Reis", "Hähnchen und ____", ["Reis", "Brot", "Pasta", "Fleisch"], "🍚", "Grano común.", "Weißer Reis"],
                ["Ensalada", "Salat", "Grüner ____", ["Salat", "Pizza", "Suppe", "Fleisch"], "🥗", "Vegetales mixtos.", "Ein frischer Salat"],
                ["Sopa", "Suppe", "Heiße ____", ["Suppe", "Salat", "Pizza", "Pasta"], "🥣", "Líquido caliente.", "Tomatensuppe"],
                ["Pasta", "Nudeln", "Italienische ____", ["Nudeln", "Pizza", "Suppe", "Reis"], "🍝", "Fideos y más.", "Ich liebe Nudeln"],
                ["Leche", "Milch", "Kaffee mit ____", ["Milch", "Wasser", "Saft", "Wein"], "🥛", "Bebida blanca.", "Kalte Milch"],
                ["Vino", "Wein", "Roter ____", ["Wein", "Wasser", "Milch", "Bier"], "🍷", "Bebida alcohólica.", "Ein Glas Wein"],
                ["Cerveza", "Bier", "Kaltes ____", ["Bier", "Wein", "Wasser", "Milch"], "🍺", "Bebida de cebada.", "Zwei Bier, bitte"],
                ["Té", "Tee", "Heißer ____", ["Tee", "Kaffee", "Milch", "Wasser"], "🍵", "Infusión.", "Grüner Tee"],
                ["Huevo", "Ei", "Gebratenes ____", ["Ei", "Brot", "Fleisch", "Obst"], "🥚", "Desayuno común.", "Ein Ei, bitte"],
                ["Queso", "Käse", "Schinken und ____", ["Käse", "Brot", "Fleisch", "Obst"], "🧀", "Producto lácteo.", "Ich liebe Käse"],
                ["Pescado", "Fisch", "Gegrillter ____", ["Fisch", "Fleisch", "Hähnchen", "Rind"], "🐟", "Del mar.", "Frischer Fisch"],
                ["Pollo", "Hähnchen", "Gebratenes ____", ["Hähnchen", "Fleisch", "Fisch", "Rind"], "🍗", "Ave común.", "Hähnchen mit Pommes"],
                ["Postre", "Nachtisch", "Schokolade zum ____", ["Nachtisch", "Fleisch", "Suppe", "Salat"], "🍰", "Algo dulce al final.", "Was gibt es zum Nachtisch?"],
                ["Cena", "Abendessen", "Iss ____", ["Abendessen", "Mittagessen", "Frühstück", "Snack"], "🍽️", "Comida nocturna.", "Lass uns Abendessen"],
                ["Cuenta", "Rechnung", "Die ____, bitte", ["Rechnung", "Menü", "Tisch", "Essen"], "💵", "Para pagar.", "Die Rechnung, bitte"]
            ].map((d, i) => ({ id: 300 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 4, title: "Viajes", icon: "✈️",
            levels: [
                ["Maleta", "Koffer", "Mein ____", ["Koffer", "Tasche", "Reisepass", "Ticket"], "🧳", "Para llevar ropa.", "Pack den Koffer"],
                ["Pasaporte", "Reisepass", "Zeig deinen ____", ["Reisepass", "Ticket", "Ausweis", "Geld"], "🛂", "Documento de viaje.", "Mein Reisepass ist bereit"],
                ["Boleto", "Ticket", "Zug____", ["Ticket", "Geld", "Tasche", "Karte"], "🎟️", "Para entrar.", "Ich habe das Ticket"],
                ["Mapa", "Karte", "Schau auf die ____", ["Karte", "Buch", "Straße", "Park"], "🗺️", "Para no perderse.", "Wo ist die Karte?"],
                ["Dinero", "Geld", "Einfaches ____", ["Geld", "Ticket", "Tasche", "Geschenk"], "💵", "Para comprar.", "Ich brauche Geld"],
                ["Cámara", "Kamera", "Nimm eine ____", ["Kamera", "Telefon", "Foto", "Tasche"], "📷", "Para fotos.", "Lächle für die Kamera"],
                ["Playa", "Strand", "Am ____", ["Strand", "Berg", "Wald", "Wüste"], "🏖️", "Arena y mar.", "Ich liebe den Strand"],
                ["Montaña", "Berg", "Hoher ____", ["Berg", "Strand", "Fluss", "See"], "⛰️", "Naturaleza alta.", "Klettere auf den Berg"],
                ["Bosque", "Wald", "Grüner ____", ["Wald", "Strand", "Wüste", "Stadt"], "🌲", "Muchos árboles.", "Im Wald"],
                ["Río", "Fluss", "Kalter ____", ["Fluss", "Meer", "See", "Pool"], "🏞️", "Agua corriente.", "Nahe dem Fluss"],
                ["Mar", "Meer", "Blaues ____", ["Meer", "Fluss", "See", "Pool"], "🌊", "Agua salada.", "Tiefblaues Meer"],
                ["Lago", "See", "Ruhiger ____", ["See", "Meer", "Fluss", "Regen"], "🛶", "Agua tranquila.", "Ein schöner See"],
                ["Desierto", "Wüste", "Heiße ____", ["Wüste", "Wald", "Strand", "Berg"], "🌵", "Mucha arena y sol.", "Die Sahara Wüste"],
                ["Isla", "Insel", "Tropische ____", ["Insel", "Land", "Stadt", "Dorf"], "🏝️", "Tierra rodeada de agua.", "Eine private Insel"],
                ["Ciudad", "Stadt", "Große ____", ["Stadt", "Dorf", "Haus", "Farm"], "🏙️", "Muchos edificios.", "Berlin Stadt"],
                ["Pueblo", "Dorf", "Kleines ____", ["Dorf", "Stadt", "Hauptstadt", "Staat"], "🏡", "Lugar pequeño.", "Ich lebe in einem Dorf"],
                ["Mundo", "Welt", "Die ____", ["Welt", "Planet", "Erde", "Karte"], "🌍", "Donde vivimos todos.", "Reise um die Welt"],
                ["Sol", "Sonne", "Die ____", ["Sonne", "Mond", "Sterne", "Himmel"], "☀️", "Luz del día.", "Die Sonne ist heiß"],
                ["Luna", "Mond", "Voll____", ["Mond", "Sonne", "Sterne", "Himmel"], "🌙", "Luz de noche.", "Schau den Mond an"],
                ["Estrellas", "Sterne", "Viele ____", ["Sterne", "Sonnen", "Monde", "Wolken"], "✨", "Puntos de luz.", "Die Sterne sind hell"]
            ].map((d, i) => ({ id: 400 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 5, title: "Profesiones", icon: "💼",
            levels: [
                ["Doctor", "Arzt", "Geh zum ____", ["Arzt", "Krankenschwester", "Koch", "Pilot"], "👨‍⚕️", "Cura a las personas.", "Er ist Arzt"],
                ["Chef", "Koch", "Ein toller ____", ["Koch", "Arzt", "Fahrer", "Bauer"], "👨‍🍳", "Cocina comida rica.", "Der Restaurantkoch"],
                ["Piloto", "Pilot", "Flugzeug ____", ["Pilot", "Fahrer", "Arzt", "Koch"], "👨‍✈️", "Vuela aviones.", "Der Pilot ist bereit"],
                ["Granjero", "Bauer", "Arbeitet auf dem Hof", ["Bauer", "Koch", "Krankenschwester", "Arzt"], "👨‍🌾", "Trabaja en el campo.", "Der Bauer hat Kühe"],
                ["Policía", "Polizist", "Ruf den ____", ["Polizist", "Koch", "Pilot", "Arzt"], "👮", "Mantiene la ley.", "Der Polizist"],
                ["Bombero", "Feuerwehrmann", "Ruf den ____", ["Feuerwehrmann", "Polizei", "Koch", "Pilot"], "👩‍🚒", "Apaga incendios.", "Ein mutiger Feuerwehrmann"],
                ["Maestro", "Lehrer", "Mein ____", ["Lehrer", "Arzt", "Pilot", "Koch"], "👩‍🏫", "Enseña cosas nuevas.", "Mein Deutschlehrer"],
                ["Enfermera", "Krankenschwester", "Die ____ hilft", ["Krankenschwester", "Arzt", "Koch", "Pilot"], "👩‍⚕️", "Ayuda en el hospital.", "Eine nette Krankenschwester"],
                ["Conductor", "Fahrer", "Taxi ____", ["Fahrer", "Pilot", "Koch", "Arzt"], "👨‍🚀", "Maneja vehículos.", "Ein Busfahrer"],
                ["Artista", "Künstler", "Ein berühmter ____", ["Künstler", "Koch", "Arzt", "Pilot"], "🎨", "Crea arte.", "Ein talentierter Künstler"],
                ["Abogado", "Anwalt", "Sieh einen ____", ["Anwalt", "Arzt", "Koch", "Pilot"], "⚖️", "Defiende personas.", "Mein Anwalt ist gut"],
                ["Dentista", "Zahnarzt", "Geh zum ____", ["Zahnarzt", "Arzt", "Krankenschwester", "Koch"], "🦷", "Cuida los dientes.", "Ich hasse den Zahnarzt"],
                ["Cantante", "Sänger", "Ein Pop ____", ["Sänger", "Künstler", "Koch", "Pilot"], "🎤", "Canta canciones.", "Mein Lieblingssänger"],
                ["Bailarín", "Tänzer", "Ballett ____", ["Tänzer", "Sänger", "Künstler", "Koch"], "💃", "Baila profesionalmente.", "Ein schneller Tänzer"],
                ["Escritor", "Schriftsteller", "Ein Buch ____", ["Schriftsteller", "Künstler", "Lehrer", "Koch"], "✍️", "Escribe libros.", "Ein Krimi-Schriftsteller"],
                ["Fotógrafo", "Fotograf", "Profi ____", ["Fotograf", "Künstler", "Koch", "Pilot"], "📷", "Toma fotos.", "Der Hochzeitsfotograf"],
                ["Ingeniero", "Ingenieur", "Software ____", ["Ingenieur", "Arzt", "Koch", "Pilot"], "🏗️", "Diseña y construye.", "Ein Bauingenieur"],
                ["Científico", "Wissenschaftler", "Labor ____", ["Wissenschaftler", "Arzt", "Koch", "Lehrer"], "🧪", "Investiga la ciencia.", "Ein verrückter Wissenschaftler"],
                ["Astronaut", "Astronaut", "Weltraum ____", ["Astronaut", "Pilot", "Koch", "Arzt"], "🚀", "Viaja al espacio.", "Der erste Astronaut"],
                ["Atleta", "Sportler", "Olympischer ____", ["Sportler", "Sänger", "Bauer", "Arzt"], "🏃", "Practica deportes.", "Ein starker Sportler"]
            ].map((d, i) => ({ id: 500 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 6, title: "Cuerpo y Salud", icon: "🏥",
            levels: [
                ["Cabeza", "Kopf", "Mein ____ tut weh", ["Kopf", "Hand", "Fuß", "Arm"], "👤", "Parte superior.", "Fass deinen Kopf an"],
                ["Ojo", "Auge", "Blaues ____", ["Auge", "Ohr", "Nase", "Mund"], "👁️", "Para ver.", "Ein großes Auge"],
                ["Oreja", "Ohr", "Hör mit deinem ____", ["Ohr", "Auge", "Nase", "Mund"], "👂", "Para oír.", "Linkes Ohr"],
                ["Nariz", "Nase", "Meine ____", ["Nase", "Ohr", "Auge", "Mund"], "👃", "Para oler.", "Eine kleine Nase"],
                ["Boca", "Mund", "Öffne deinen ____", ["Mund", "Nase", "Ohr", "Auge"], "👄", "Para hablar.", "Ein roter Mund"],
                ["Mano", "Hand", "Wasch deine ____", ["Hand", "Fuß", "Arm", "Bein"], "✋", "Para tocar.", "Gib mir die Hand"],
                ["Pie", "Fuß", "Linker ____", ["Fuß", "Hand", "Arm", "Bein"], "🦶", "Para caminar.", "Auf einem Fuß"],
                ["Brazo", "Arm", "Starker ____", ["Arm", "Bein", "Hand", "Fuß"], "💪", "Extremidad superior.", "Mein rechter Arm"],
                ["Pierna", "Bein", "Langes ____", ["Bein", "Arm", "Hand", "Fuß"], "🦵", "Extremidad inferior.", "Brich ein Bein"],
                ["Corazón", "Herz", "Reines ____", ["Herz", "Magen", "Kopf", "Hand"], "❤️", "Bómbea sangre.", "Ein kaltes Herz"],
                ["Dedo", "Finger", "Ring ____", ["Finger", "Zeh", "Hand", "Fuß"], "☝️", "En la mano.", "Zehn Finger"],
                ["Espalda", "Rücken", "Mein ____", ["Rücken", "Brust", "Arm", "Bein"], "🧍", "Parte posterior.", "Ein schmerzender Rücken"],
                ["Dolor", "Schmerz", "Viel ____", ["Schmerz", "Gesundheit", "Medizin", "Arzt"], "🤕", "Sensación mala.", "Viel Schmerz"],
                ["Salud", "Gesundheit", "Gute ____", ["Gesundheit", "Schmerz", "Medizin", "Arzt"], "🍏", "Estar bien.", "Gesundheit ist Reichtum"],
                ["Medicina", "Medizin", "Nimm deine ____", ["Medizin", "Essen", "Wasser", "Milch"], "💊", "Para curarse.", "Die Medizin des Arztes"],
                ["Sangre", "Blut", "Rotes ____", ["Blut", "Wasser", "Milch", "Saft"], "🩸", "Líquido vital.", "Blutbank"],
                ["Hueso", "Knochen", "Gebrochener ____", ["Knochen", "Blut", "Schmerz", "Gesundheit"], "🦴", "Parte dura interna.", "Ein starker Knochen"],
                ["Cuerpo", "Körper", "Menschlicher ____", ["Körper", "Kopf", "Hand", "Fuß"], "🧍", "Todo nosotros.", "Ein gesunder Körper"],
                ["Sueño", "Schlaf", "Brauche ____", ["Schlaf", "Essen", "Trinken", "Spielen"], "😴", "Descansar de noche.", "Geh schlafen"],
                ["Vida", "Leben", "Langes ____", ["Leben", "Gesundheit", "Schmerz", "Körper"], "🌱", "Estar vivos.", "Ein gutes Leben"]
            ].map((d, i) => ({ id: 600 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 7, title: "Clima y Tiempo", icon: "☁️",
            levels: [
                ["Sol", "Sonne", "Die heiße ____", ["Sonne", "Mond", "Regen", "Schnee"], "☀️", "Luz del día.", "Die Sonne brennt"],
                ["Lluvia", "Regen", "Kalter ____", ["Regen", "Sonne", "Schnee", "Wind"], "🌧️", "Agua del cielo.", "Ich liebe Regen"],
                ["Nieve", "Schnee", "Weißer ____", ["Schnee", "Regen", "Sonne", "Wind"], "❄️", "Agua helada.", "Erster Schnee"],
                ["Viento", "Wind", "Starker ____", ["Wind", "Regen", "Sonne", "Schnee"], "💨", "Aire en movimiento.", "Der Wind weht"],
                ["Nube", "Wolke", "Weiße ____", ["Wolke", "Sonne", "Regen", "Mond"], "☁️", "Mucha agua arriba.", "Eine große Wolke"],
                ["Cielo", "Himmel", "Blauer ____", ["Himmel", "Wolke", "Sonne", "Mond"], "🌌", "Arriba nuestro.", "Klarer Himmel"],
                ["Calor", "Hitze", "Es ist ____", ["Hitze", "Kälte", "Regen", "Schnee"], "🔥", "Mucho sol.", "Ein heißer Tag"],
                ["Frío", "Kälte", "Es ist ____", ["Kälte", "Hitze", "Sonne", "Wind"], "🥶", "Poca temperatura.", "Kaltes Wasser"],
                ["Tormenta", "Sturm", "Großer ____", ["Sturm", "Regen", "Wolke", "Wind"], "⛈️", "Lluvia y rayos.", "Ein Sommersturm"],
                ["Clima", "Wetter", "Gutes ____", ["Wetter", "Sonne", "Regen", "Tag"], "🌍", "Estado del aire.", "Wie ist das Wetter?"],
                ["Día", "Tag", "Ein sonniger ____", ["Tag", "Nacht", "Morgen", "Abend"], "☀️", "Luz.", "Hab einen schönen Tag"],
                ["Noche", "Nacht", "Sternenklare ____", ["Nacht", "Tag", "Morgen", "Abend"], "🌙", "Oscuridad.", "Gute Nacht"],
                ["Mañana", "Morgen", "Guten ____", ["Morgen", "Nacht", "Tag", "Abend"], "🌅", "Primeras horas.", "Am Morgen"],
                ["Tarde", "Nachmittag", "Guten ____", ["Nachmittag", "Morgen", "Nacht", "Tag"], "🌤️", "Horas medias.", "Jeden Nachmittag"],
                ["Semana", "Woche", "Letzte ____", ["Woche", "Monat", "Jahr", "Tag"], "📅", "Siete días.", "Nächste Woche"],
                ["Mes", "Monat", "Dieser ____", ["Monat", "Woche", "Jahr", "Tag"], "🗓️", "Treinta días.", "Jeden Monat"],
                ["Año", "Jahr", "Neues ____", ["Jahr", "Monat", "Woche", "Tag"], "🎉", "Doce meses.", "Frohes neues Jahr"],
                ["Hora", "Stunde", "Eine ____", ["Stunde", "Minute", "Sekunde", "Tag"], "⏰", "Sesenta minutos.", "Warte eine Stunde"],
                ["Minuto", "Minute", "Fünf ____", ["Minute", "Stunde", "Sekunde", "Tag"], "⏱️", "Sesenta segundos.", "Eine Minute, bitte"],
                ["Segunda", "Sekunde", "Warte eine ____", ["Sekunde", "Minute", "Stunde", "Tag"], "⌛", "Tiempo muy corto.", "Warte eine Sekunde"]
            ].map((d, i) => ({ id: 700 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 8, title: "Ropa y Tienda", icon: "🛍️",
            levels: [
                ["Camisa", "Hemd", "Blaues ____", ["Hemd", "Hose", "Kleid", "Schuh"], "👕", "Ropa de arriba.", "Ein Baumwollhemd"],
                ["Pantalón", "Hose", "Lange ____", ["Hose", "Hemd", "Kleid", "Schuh"], "👖", "Ropa de piernas.", "Blaue Hose"],
                ["Vestido", "Kleid", "Rotes ____", ["Kleid", "Hemd", "Hose", "Schuh"], "👗", "Ropa de fiesta.", "Ein schönes Kleid"],
                ["Zapato", "Schuh", "Schwarzer ____", ["Schuh", "Hemd", "Hose", "Kleid"], "👞", "Para los pies.", "Lauf in Schuhen"],
                ["Gorra", "Hut", "Cooler ____", ["Hut", "Hemd", "Hose", "Kleid"], "🧢", "Para la cabeza.", "Trag einen Hut"],
                ["Ropa", "Kleidung", "Neue ____", ["Kleidung", "Schuhe", "Taschen", "Hut"], "👗", "Todo lo que usamos.", "Saubere Kleidung"],
                ["Precio", "Preis", "Hoher ____", ["Preis", "Geld", "Rechnung", "Kosten"], "💰", "Lo que cuesta.", "Der beste Preis"],
                ["Barato", "Billig", "Sehr ____", ["Billig", "Teuer", "Neu", "Alt"], "🏷️", "Cuesta poco.", "Billiges Essen"],
                ["Caro", "Teuer", "Es ist ____", ["Teuer", "Billig", "Neu", "Alt"], "💎", "Cuesta mucho.", "Ein teures Auto"],
                ["Comprar", "Kaufen", "Ich will ____", ["Kaufen", "Verkaufen", "Geben", "Nehmen"], "🛒", "Adquirir algo.", "Kauf ein Geschenk"],
                ["Vender", "Verkaufen", "Ich will ____", ["Verkaufen", "Kaufen", "Geben", "Nehmen"], "🏪", "Dar por dinero.", "Verkauf mein Auto"],
                ["Chaqueta", "Jacke", "Winter____", ["Jacke", "Hemd", "Mantel", "Kleid"], "🧥", "Para el frío.", "Eine warme Jacke"],
                ["Calcetín", "Socke", "Linke ____", ["Socke", "Schuh", "Hose", "Hemd"], "🧦", "Debajo del zapato.", "Eine weiße Socke"],
                ["Gafas", "Brille", "Sonnen____", ["Brille", "Hut", "Ring", "Uhr"], "🕶️", "Para los ojos.", "Trag eine Brille"],
                ["Reloj", "Uhr", "Armband____", ["Uhr", "Uhr", "Ring", "Hut"], "⌚", "Para ver la hora.", "Eine silberne Uhr"],
                ["Bolso", "Tasche", "Hand____", ["Tasche", "Box", "Koffer", "Tüte"], "👜", "Para llevar cosas.", "Trag eine Tasche"],
                ["Cinturón", "Gürtel", "Leder____", ["Gürtel", "Hose", "Hemd", "Kleid"], "🎗️", "Para ajustar.", "Ein schwarzer Gürtel"],
                ["Traje", "Anzug", "Schwarzer ____", ["Anzug", "Hemd", "Hose", "Kleid"], "👔", "Ropa formal.", "Trag einen Anzug"],
                ["Bufanda", "Schal", "Langer ____", ["Schal", "Hut", "Mantel", "Handschuh"], "🧣", "Para el cuello.", "Ein Wollschal"],
                ["Guantes", "Handschuhe", "Ein Paar ____", ["Handschuhe", "Socken", "Schuhe", "Hüte"], "🧤", "Para las manos.", "Warme Handschuhe"]
            ].map((d, i) => ({ id: 800 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 9, title: "Entretenimiento", icon: "🎮",
            levels: [
                ["Juego", "Spiel", "Neues ____", ["Spiel", "Spielen", "Sport", "Arbeit"], "🎮", "Para divertirse.", "Ein lustiges Spiel"],
                ["Cine", "Kino", "Geh ins ____", ["Kino", "Laden", "Bank", "Park"], "🎬", "Ver películas.", "Im Kino"],
                ["Cuento", "Geschichte", "Erzähl eine ____", ["Geschichte", "Lied", "Spiel", "Theater"], "📚", "Narración.", "Eine Gute-Nacht-Geschichte"],
                ["Música", "Musik", "Hör ____", ["Musik", "Ton", "Lärm", "Stimme"], "🎵", "Sonidos rítmicos.", "Leise Musik"],
                ["Baile", "Tanz", "Lass uns ____", ["Tanz", "Singen", "Spielen", "Rennen"], "💃", "Mover el cuerpo.", "Lern den Tanz"],
                ["Fiesta", "Party", "Geburtstags____", ["Party", "Arbeit", "Schule", "Zuhause"], "🥳", "Celebración.", "Eine große Party"],
                ["Película", "Film", "Grusel____", ["Film", "Buch", "Lied", "Spiel"], "🎥", "Historia visual.", "Schau einen Film"],
                ["Radio", "Radio", "Im ____", ["Radio", "Telefon", "TV", "Web"], "📻", "Para oír noticias.", "Hör Radio"],
                ["Tele", "Fernsehen", "Schau ____", ["Fernsehen", "Radio", "Buch", "Spiel"], "📺", "Televisión.", "Mach den Fernseher an"],
                ["Libro", "Buch", "Lies ein ____", ["Buch", "Stift", "Seite", "Tisch"], "📖", "Hojas escritas.", "Ein langes Buch"],
                ["Actor", "Schauspieler", "Berühmter ____", ["Schauspieler", "Sänger", "Künstler", "Arzt"], "🎭", "Actúa en cine.", "Ein Hollywood Schauspieler"],
                ["Pintura", "Gemälde", "Öl____", ["Gemälde", "Foto", "Zeichnung", "Kunst"], "🎨", "Arte con pincel.", "Ein schönes Gemälde"],
                ["Dibujo", "Zeichnung", "Stift____", ["Zeichnung", "Gemälde", "Foto", "Kunst"], "✏️", "Arte con lápiz.", "Mach eine Zeichnung"],
                ["Museo", "Museum", "Geschichts____", ["Museum", "Kino", "Laden", "Park"], "🏛️", "Donde hay arte.", "Besuch das Museum"],
                ["Teatro", "Theater", "Altes ____", ["Theater", "Kino", "Laden", "Park"], "🏟️", "Obras en vivo.", "Im Theater"],
                ["Concierto", "Konzert", "Rock ____", ["Konzert", "Film", "Spiel", "Party"], "🎸", "Música en vivo.", "Geh zum Konzert"],
                ["Piano", "Klavier", "Spiel ____", ["Klavier", "Gitarre", "Trommel", "Geige"], "🎹", "Instrumento de teclas.", "Das große Klavier"],
                ["Guitarra", "Gitarre", "Elektrische ____", ["Gitarre", "Klavier", "Trommel", "Geige"], "🎸", "Instrumento de cuerdas.", "Eine laute Gitarre"],
                ["Tambor", "Trommel", "Schlag die ____", ["Trommel", "Klavier", "Gitarre", "Geige"], "🥁", "Instrumento de percusión.", "Eine große Trommel"],
                ["Violín", "Geige", "Klassische ____", ["Geige", "Klavier", "Gitarre", "Trommel"], "🎻", "Instrumento delicado.", "Die kleine Geige"]
            ].map((d, i) => ({ id: 900 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 10, title: "Deporte y Ocio", icon: "⚽",
            levels: [
                ["Fútbol", "Fußball", "Spiel ____", ["Fußball", "Tennis", "Golf", "Rennen"], "⚽", "Con los pies.", "Amerikanischer Fußball"],
                ["Tenis", "Tennis", "Spiel ____", ["Tennis", "Fußball", "Golf", "Rennen"], "🎾", "Con raqueta.", "Spiel Tennis"],
                ["Correr", "Laufen", "Ich mag ____", ["Laufen", "Schwimmen", "Gehen", "Springen"], "🏃", "Ir rápido a pie.", "Lauf schnell"],
                ["Nadar", "Schwimmen", "Im Pool", ["Schwimmen", "Laufen", "Gehen", "Springen"], "🏊", "En el agua.", "Schwimmen wie ein Fisch"],
                ["Golf", "Golf", "Spiel ____", ["Golf", "Tennis", "Fußball", "Laufen"], "⛳", "Con hoyos.", "Ein Spiel Golf"],
                ["Bici", "Fahrrad", "Fahr ____", ["Fahrrad", "Auto", "Bus", "Zug"], "🚲", "Dos ruedas.", "Mein rotes Fahrrad"],
                ["Pelota", "Ball", "Kick den ____", ["Ball", "Schläger", "Netz", "Tor"], "⚽", "Redonda.", "Ein Plastikball"],
                ["Equipo", "Team", "Bestes ____", ["Team", "Spieler", "Spiel", "Sieg"], "👫", "Grupo unido.", "Ein starkes Team"],
                ["Ganar", "Gewinnen", "Ich will ____", ["Gewinnen", "Verlieren", "Unentschieden", "Spielen"], "🏆", "Ser el primero.", "Gewinn das Spiel"],
                ["Jugar", "Spielen", "Lass uns ____", ["Spielen", "Arbeiten", "Schlafen", "Essen"], "🎮", "Hacer deporte.", "Spiel mit Freunden"],
                ["Perder", "Verlieren", "Nicht ____", ["Verlieren", "Gewinnen", "Unentschieden", "Spielen"], "😢", "No ser primero.", "Verliere nicht"],
                ["Empate", "Unentschieden", "Es ist ein ____", ["Unentschieden", "Sieg", "Niederlage", "Spiel"], "🤝", "Iguales.", "Ein faires Unentschieden"],
                ["Entrenar", "Trainieren", "Ich muss ____", ["Trainieren", "Spielen", "Arbeiten", "Ausruhen"], "💪", "Practicar.", "Trainier hart"],
                ["Gimnasio", "Fitnessstudio", "Geh ins ____", ["Fitnessstudio", "Laden", "Bank", "Park"], "🏋️", "Hacer ejercicio.", "Im lokalen Fitnessstudio"],
                ["Piscina", "Schwimmbad", "Blaues ____", ["Schwimmbad", "See", "Meer", "Fluss"], "🏊", "Donde nadas.", "Ein sauberes Schwimmbad"],
                ["Estadio", "Stadion", "Großes ____", ["Stadion", "Fitnessstudio", "Park", "Kino"], "🏟️", "Donde hay partidos.", "Das Stadtstadion"],
                ["Caminar", "Gehen", "Geh ____", ["Gehen", "Laufen", "Schwimmen", "Springen"], "🚶", "Ir a pie.", "Geh im Park"],
                ["Saltar", "Springen", "Ich kann ____", ["Springen", "Laufen", "Schwimmen", "Gehen"], "🦘", "Hacia arriba.", "Spring hoch"],
                ["Cantar", "Singen", "Versuch zu ____", ["Singen", "Tanzen", "Sprechen", "Hören"], "🎤", "Voz musical.", "Sing ein Lied"],
                ["Reír", "Lachen", "Immer ____", ["Lachen", "Weinen", "Lächeln", "Wütend"], "😂", "Felicidad.", "Lautes Lachen"]
            ].map((d, i) => ({ id: 1000 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 11, title: "Tecnología", icon: "💻",
            levels: [
                ["Compu", "Computer", "Schneller ____", ["Computer", "Telefon", "Radio", "TV"], "💻", "Para trabajar.", "Mein neuer Computer"],
                ["Celular", "Handy", "Mobiles ____", ["Handy", "Radio", "TV", "Web"], "📱", "En tu mano.", "Ruf mich an"],
                ["Internet", "Internet", "Im ____", ["Internet", "Radio", "TV", "Telefon"], "🌐", "Mundo conectado.", "Such im Internet"],
                ["Correo", "E-Mail", "Sende eine ____", ["E-Mail", "Brief", "Anruf", "Spiel"], "📧", "Mensaje digital.", "Check meine E-Mail"],
                ["Web", "Webseite", "Besuch eine ____", ["Webseite", "E-Mail", "Telefon", "TV"], "🌍", "Sitio digital.", "Eine schnelle Webseite"],
                ["Clave", "Passwort", "Sicheres ____", ["Passwort", "Name", "Mail", "Wort"], "🔐", "Secreto.", "Wie ist das Passwort?"],
                ["Pantalla", "Bildschirm", "Großer ____", ["Bildschirm", "Telefon", "Maus", "Taste"], "📺", "Donde ves todo.", "Ein flacher Bildschirm"],
                ["Teclado", "Tastatur", "Tipp auf der ____", ["Tastatur", "Maus", "Bildschirm", "Telefon"], "⌨️", "Para escribir.", "Eine mechanische Tastatur"],
                ["Ratón", "Maus", "Computer ____", ["Maus", "Bildschirm", "Taste", "Telefon"], "🖱️", "Mueve flecha.", "Eine Funkmaus"],
                ["Código", "Code", "Schreib ____", ["Code", "Wort", "Mail", "Anruf"], "⌨️", "Para programar.", "Lern zu coden"],
                ["Robot", "Roboter", "Kluger ____", ["Roboter", "Mann", "Hund", "Katze"], "🤖", "Hombre de metal.", "Der kleine Roboter"],
                ["Espacio", "Weltraum", "Der ____", ["Weltraum", "Himmel", "Wolke", "Sonne"], "🚀", "Estrellas y luna.", "Reise in den Weltraum"],
                ["Nave", "Raumschiff", "Schnelles ____", ["Raumschiff", "Auto", "Bus", "Zug"], "🛸", "Vuela lejos.", "Das silberne Raumschiff"],
                ["Futuro", "Zukunft", "Kluge ____", ["Zukunft", "Vergangenheit", "Jetzt", "Heute"], "⏳", "Lo que vendrá.", "In der Zukunft"],
                ["Chip", "Chip", "Kleiner ____", ["Chip", "Karte", "Schlüssel", "Box"], "💾", "Cerebro digital.", "Ein Silikonchip"],
                ["Cable", "Kabel", "Langes ____", ["Kabel", "Draht", "Link", "Leitung"], "🔌", "Para corriente.", "Steck das Kabel ein"],
                ["Batería", "Batterie", "Volle ____", ["Batterie", "Kraft", "Niedrig", "Leben"], "🔋", "Energía.", "Lad die Batterie"],
                ["Wifi", "WLAN", "Gratis ____", ["WLAN", "Link", "Web", "Netz"], "📶", "Señal sin hilos.", "Wo ist das WLAN?"],
                ["App", "App", "Mobile ____", ["App", "Spiel", "Web", "Mail"], "📱", "Programa de móvil.", "Installier die App"],
                ["Juego", "Videospiel", "Video ____", ["Videospiel", "App", "Web", "Mail"], "🎮", "Diversión digital.", "Ich liebe dieses Videospiel"]
            ].map((d, i) => ({ id: 1100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 12, title: "Sentimientos", icon: "🔥",
            levels: [
                ["Amor", "Liebe", "Ich ____ dich", ["Liebe", "Hass", "Mag", "Will"], "❤️", "Sentir mucho.", "Wahre Liebe"],
                ["Odio", "Hass", "Stopp den ____", ["Hass", "Liebe", "Mag", "Will"], "😠", "Sentir mal.", "Hasse nicht"],
                ["Feliz", "Glücklich", "Fühl dich ____", ["Glücklich", "Traurig", "Wütend", "Angst"], "😊", "Estar bien.", "Ich bin glücklich"],
                ["Triste", "Traurig", "Sei nicht ____", ["Traurig", "Glücklich", "Wütend", "Angst"], "😢", "Estar mal.", "Ein trauriger Tag"],
                ["Enojo", "Wütend", "Hör auf ____ zu sein", ["Wütend", "Glücklich", "Traurig", "Angst"], "😡", "Mucha rabia.", "Der wütende Mann"],
                ["Miedo", "Angst", "Keine ____", ["Angst", "Liebe", "Hoffnung", "Freude"], "😨", "Susto.", "Stell dich der Angst"],
                ["Paz", "Frieden", "Welt____", ["Frieden", "Krieg", "Liebe", "Hoffnung"], "🕊️", "Tranquilidad.", "Innerer Frieden"],
                ["Guerra", "Krieg", "Stopp den ____", ["Krieg", "Frieden", "Liebe", "Hoffnung"], "💣", "Conflicto.", "Ein langer Krieg"],
                ["Risa", "Lachen", "Ein großes ____", ["Lachen", "Weinen", "Lächeln", "Wütend"], "😄", "Jajaja.", "Ein lautes Lachen"],
                ["Llantos", "Weinen", "Nicht ____", ["Weinen", "Lachen", "Lächeln", "Wütend"], "😭", "Lágrimas.", "Baby weint"],
                ["Deseo", "Wollen", "Ich ____ das", ["Wollen", "Mögen", "Brauchen", "Haben"], "💫", "Querer algo.", "Ich will mehr"],
                ["Gusto", "Mögen", "Ich ____ Essen", ["Mögen", "Lieben", "Wollen", "Brauchen"], "👍", "Agradar.", "Ich mag Pizza"],
                ["Necesidad", "Brauchen", "Ich ____ Wasser", ["Brauchen", "Wollen", "Mögen", "Haben"], "🆘", "Ser urgente.", "Du brauchst Hilfe"],
                ["Tener", "Haben", "Ich ____ ein Auto", ["Haben", "Brauchen", "Wollen", "Mögen"], "🤲", "Posesión.", "Ich habe ein Haus"],
                ["Ser", "Sein", "Einfach ____", ["Sein", "Haben", "Brauchen", "Wollen"], "🧘", "Existir.", "Sein oder nicht sein"],
                ["Amigo", "Freund", "Bester ____", ["Freund", "Feind", "Junge", "Mädchen"], "👫", "Persona cercana.", "Ein guter Freund"],
                ["Enemigo", "Feind", "Töte den ____", ["Feind", "Freund", "Mann", "Frau"], "🦹", "Persona contraria.", "Bleib weg vom Feind"],
                ["Familia", "Familie", "Große ____", ["Familie", "Freund", "Team", "Gruppe"], "👨‍👩‍👧‍👦", "Parientes.", "Ich liebe meine Familie"],
                ["Hogar", "Zuhause", "Gehe nach ____", ["Zuhause", "Haus", "Laden", "Arbeit"], "🏠", "Donde vives.", "Zuhause süßes Zuhause"],
                ["Mundo", "Welt", "Die ganze ____", ["Welt", "Zuhause", "Stadt", "Land"], "🌍", "Todo el planeta.", "Rette die Welt"]
            ].map((d, i) => ({ id: 1200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        }
    ]
};
