// === BASE DE DATOS DE LECCIONES: ITALIANO (ES -> IT) ===
window.courseIt = {
    title: "Corso di Italiano",
    mission: "Missione: Livello A1 (Principiante)",
    langCode: "it-IT",
    units: [
        {
            id: 1, title: "Primi Passi", icon: "🇮🇹",
            levels: [
                ["Hola", "Ciao", "____!", ["Ciao", "Arrivederci", "Acqua", "Pane"], "👋", "Para saludar usa <b>Ciao</b>.", "Ciao!"],
                ["Yo soy", "Io sono", "____ Alex", ["Io sono", "Tu sei", "Lui è", "Noi siamo"], "👤", "Presentarse con <b>Io sono</b>.", "Io sono Alex"],
                ["Uno", "Uno", "Numero ____", ["Uno", "Due", "Tre", "Quattro"], "1️⃣", "El número uno.", "Uno per favore"],
                ["Adiós", "Arrivederci", "____!", ["Arrivederci", "Ciao", "Prego", "Grazie"], "🏃", "Despedirse con <b>Arrivederci</b>.", "Arrivederci!"],
                ["Dos", "Due", "Numero ____", ["Due", "Uno", "Tre", "Quattro"], "2️⃣", "El número dos.", "Due birre"],
                ["Por favor", "Per favore", "____, aiutami", ["Per favore", "Grazie", "Sì", "No"], "🙏", "Pedir cosas con <b>Per favore</b>.", "Un caffè, per favore"],
                ["Gracias", "Grazie", "____ mille", ["Grazie", "Prego", "Ciao", "No"], "✨", "Agradecer con <b>Grazie</b>.", "Grazie mille"],
                ["Tres", "Tre", "Numero ____", ["Tre", "Due", "Uno", "Quattro"], "3️⃣", "El número tres.", "Tre cani"],
                ["Sí", "Sì", "____, io sono", ["Sì", "No", "Forse", "Mai"], "✅", "Afirmar con <b>Sì</b>.", "Sì, grazie"],
                ["No", "No", "____, grazie", ["No", "Sì", "Certo", "Sempre"], "❌", "Negar con <b>No</b>.", "No, scusa"],
                ["Buenos días", "Buongiorno", "____!", ["Buongiorno", "Buonanotte", "Ciao", "Salve"], "🌅", "Saludo matutino.", "Buongiorno!"],
                ["Hombre", "Uomo", "L'____", ["Uomo", "Donna", "Ragazzo", "Ragazza"], "👨", "Vocabulario: Hombre.", "Un uomo alto"],
                ["Mujer", "Donna", "La ____", ["Donna", "Uomo", "Ragazza", "Ragazzo"], "👩", "Vocabulario: Mujer.", "Una donna forte"],
                ["Niño", "Ragazzo", "Il ____", ["Ragazzo", "Ragazza", "Uomo", "Donna"], "👦", "Vocabulario: Niño.", "Un ragazzo felice"],
                ["Niña", "Ragazza", "La ____", ["Ragazza", "Ragazzo", "Donna", "Uomo"], "👧", "Vocabulario: Niña.", "Una ragazza piccola"],
                ["Cuatro", "Quattro", "Numero ____", ["Quattro", "Tre", "Cinque", "Sei"], "4️⃣", "El número cuatro.", "Quattro libri"],
                ["Cinco", "Cinque", "Numero ____", ["Cinque", "Quattro", "Sei", "Sette"], "5️⃣", "El número cinco.", "Cinque stelle"],
                ["Nombre", "Nome", "Il mio ____ è...", ["Nome", "È", "Io", "Sono"], "📛", "Preguntar o decir el nombre.", "Il mio nome è Luca"],
                ["Perro", "Cane", "Il mio ____", ["Cane", "Gatto", "Uccello", "Pesce"], "🐶", "Mascotas: Perro.", "Amo il mio cane"],
                ["Gato", "Gatto", "Il ____ nero", ["Gatto", "Cane", "Uccello", "Topo"], "🐱", "Mascotas: Gato.", "Il gatto nero"]
            ].map((d, i) => ({ id: 100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 2, title: "La Città", icon: "🏙️",
            levels: [
                ["Casa", "Casa", "La mia ____", ["Casa", "Auto", "Strada", "Parco"], "🏠", "Donde vives.", "La mia grande casa"],
                ["Auto", "Auto", "La ____ rossa", ["Auto", "Bus", "Treno", "Aereo"], "🚗", "Vehículo común.", "Ho un'auto"],
                ["Calle", "Strada", "Sulla ____", ["Strada", "Via", "Casa", "Parco"], "🛣️", "Por donde caminas.", "La strada principale"],
                ["Parque", "Parco", "Nel ____", ["Parco", "Casa", "Scuola", "Banca"], "🌳", "Lugar verde.", "Nel parco"],
                ["Banco", "Banca", "Dov'è la ____?", ["Banca", "Caffè", "Parco", "Negozio"], "🏦", "Donde está el dinero.", "La banca centrale"],
                ["Tienda", "Negozio", "Un grande ____", ["Negozio", "Casa", "Parco", "Strada"], "🏬", "Lugar para comprar.", "Negozio Apple"],
                ["Escuela", "Scuola", "Vai a ____", ["Scuola", "Negozio", "Banca", "Auto"], "🏫", "Lugar de estudio.", "A scuola"],
                ["Hospital", "Ospedale", "L'____ vicino", ["Ospedale", "Parco", "Caffè", "Banca"], "🏥", "Salud.", "L'ospedale cittadino"],
                ["Café", "Caffè", "Andiamo al ____", ["Caffè", "Negozio", "Banca", "Parco"], "☕", "Lugar para beber café.", "Mi piace questo caffè"],
                ["Bus", "Autobus", "Prendi l'____", ["Autobus", "Auto", "Bici", "Taxi"], "🚌", "Transporte público.", "L'autobus scolastico"],
                ["Taxi", "Taxi", "Chiama un ____", ["Taxi", "Autobus", "Bici", "Aereo"], "🚕", "Transporte privado.", "Taxi giallo"],
                ["Bici", "Bici", "Guida una ____", ["Bici", "Autobus", "Auto", "Taxi"], "🚲", "Dos ruedas.", "La mia nuova bici"],
                ["Tren", "Treno", "____ veloce", ["Treno", "Autobus", "Aereo", "Auto"], "🚆", "Vías de hierro.", "Treno del mattino"],
                ["Avión", "Aereo", "L'____", ["Aereo", "Auto", "Barca", "Autobus"], "✈️", "Para volar.", "L'aereo blu"],
                ["Barco", "Barca", "La ____", ["Barca", "Auto", "Bici", "Autobus"], "🚢", "Por el agua.", "Una grande barca"],
                ["Hotel", "Hotel", "____ di lusso", ["Hotel", "Casa", "Banca", "Parco"], "🏨", "Para dormir fuera.", "Stare in hotel"],
                ["Cine", "Cinema", "Al ____", ["Cinema", "Parco", "Negozio", "Banca"], "🎬", "Ver películas.", "Andare al cinema"],
                ["Puente", "Ponte", "Attraversa il ____", ["Ponte", "Strada", "Via", "Casa"], "🌉", "Une dos caminos.", "Ponte di Rialto"],
                ["Museo", "Museo", "Il ____ d'arte", ["Museo", "Negozio", "Parco", "Banca"], "🏛️", "Historia y arte.", "Visita il museo"],
                ["Policía", "Polizia", "Chiama la ____", ["Polizia", "Dottore", "Pompieri", "Inferimera"], "🚓", "Seguridad.", "Stazione di polizia"]
            ].map((d, i) => ({ id: 200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 3, title: "Il Ristorante", icon: "🍕",
            levels: [
                ["Agua", "Acqua", "Un bicchiere d'____", ["Acqua", "Vino", "Succo", "Latte"], "💧", "Bebida básica.", "Ho bisogno di acqua"],
                ["Pan", "Pane", "Burro e ____", ["Pane", "Torta", "Carne", "Riso"], "🍞", "Para acompañar.", "Pane fresco"],
                ["Pizza", "Pizza", "Mi piace la ____", ["Pizza", "Pasta", "Zuppa", "Insalata"], "🍕", "Comida italiana.", "Una pizza, per favore"],
                ["Carne", "Carne", "Mangia ____", ["Carne", "Frutta", "Pane", "Zucchero"], "🥩", "Proteína.", "Carne arrosto"],
                ["Fruta", "Frutta", "____ fresca", ["Frutta", "Carne", "Pane", "Riso"], "🍎", "Sano y dulce.", "Mangia più frutta"],
                ["Arroz", "Riso", "Pollo e ____", ["Riso", "Pane", "Pasta", "Carne"], "🍚", "Grano común.", "Riso bianco"],
                ["Ensalada", "Insalata", "____ verde", ["Insalata", "Pizza", "Zuppa", "Carne"], "🥗", "Vegetales mixtos.", "Un'insalata fresca"],
                ["Sopa", "Zuppa", "____ calda", ["Zuppa", "Insalata", "Pizza", "Pasta"], "🥣", "Líquido caliente.", "Zuppa di pomodoro"],
                ["Pasta", "Pasta", "____ italiana", ["Pasta", "Pizza", "Zuppa", "Riso"], "🍝", "Fideos y más.", "Amo la pasta"],
                ["Leche", "Latte", "Caffè con ____", ["Latte", "Acqua", "Succo", "Vino"], "🥛", "Bebida blanca.", "Latte freddo"],
                ["Vino", "Vino", "____ rosso", ["Vino", "Acqua", "Latte", "Birra"], "🍷", "Bebida alcohólica.", "Un bicchiere di vino"],
                ["Cerveza", "Birra", "____ fredda", ["Birra", "Vino", "Acqua", "Latte"], "🍺", "Bebida de cebada.", "Due birre, per favore"],
                ["Té", "Tè", "____ caldo", ["Tè", "Caffè", "Latte", "Acqua"], "🍵", "Infusión.", "Tè verde"],
                ["Huevo", "Uovo", "____ fritto", ["Uovo", "Pane", "Carne", "Frutta"], "🥚", "Desayuno común.", "Un uovo, per favore"],
                ["Queso", "Formaggio", "Prosciutto e ____", ["Formaggio", "Pane", "Carne", "Frutta"], "🧀", "Producto lácteo.", "Amo il formaggio"],
                ["Pescado", "Pesce", "____ grigliato", ["Pesce", "Carne", "Pollo", "Manzo"], "🐟", "Del mar.", "Pesce fresco"],
                ["Pollo", "Pollo", "____ fritto", ["Pollo", "Carne", "Pesce", "Manzo"], "🍗", "Ave común.", "Pollo e patatine"],
                ["Postre", "Dolce", "Cioccolato per ____", ["Dolce", "Carne", "Zuppa", "Insalata"], "🍰", "Algo dulce al final.", "Cosa c'è per dolce?"],
                ["Cena", "Cena", "Mangia la ____", ["Cena", "Pranzo", "Colazione", "Spuntino"], "🍽️", "Comida nocturna.", "Facciamo cena"],
                ["Cuenta", "Conto", "Il ____, per favore", ["Conto", "Menu", "Tavolo", "Cibo"], "💵", "Para pagar.", "Il conto, per favore"]
            ].map((d, i) => ({ id: 300 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 4, title: "Viaggi", icon: "✈️",
            levels: [
                ["Maleta", "Valigia", "La mia ____", ["Valigia", "Borsa", "Passaporto", "Biglietto"], "🧳", "Para llevar ropa.", "Prepara la valigia"],
                ["Pasaporte", "Passaporto", "Mostra il ____", ["Passaporto", "Biglietto", "ID", "Soldi"], "🛂", "Documento de viaje.", "Mio passaporto è pronto"],
                ["Boleto", "Biglietto", "____ del treno", ["Biglietto", "Soldi", "Borsa", "Mappa"], "🎟️", "Para entrar.", "Ho il biglietto"],
                ["Mapa", "Mappa", "Guarda la ____", ["Mappa", "Libro", "Strada", "Parco"], "🗺️", "Para no perderse.", "Dov'è la mappa?"],
                ["Dinero", "Soldi", "____ facili", ["Soldi", "Biglietto", "Borsa", "Regalo"], "💵", "Para comprar.", "Ho bisogno di soldi"],
                ["Cámara", "Fotocamera", "Prendi una ____", ["Fotocamera", "Telefono", "Foto", "Borsa"], "📷", "Para fotos.", "Sorridi alla fotocamera"],
                ["Playa", "Spiaggia", "In ____", ["Spiaggia", "Montagna", "Foresta", "Deserto"], "🏖️", "Arena y mar.", "Amo la spiaggia"],
                ["Montaña", "Montagna", "Alta ____", ["Montagna", "Spiaggia", "Fiume", "Lago"], "⛰️", "Naturaleza alta.", "Scala la montagna"],
                ["Bosque", "Foresta", "____ verde", ["Foresta", "Spiaggia", "Deserto", "Città"], "🌲", "Muchos árboles.", "Nella foresta"],
                ["Río", "Fiume", "____ freddo", ["Fiume", "Mare", "Lago", "Piscina"], "🏞️", "Agua corriente.", "Vicino al fiume"],
                ["Mar", "Mare", "____ blu", ["Mare", "Fiume", "Lago", "Piscina"], "🌊", "Agua salada.", "Mare profondo"],
                ["Lago", "Lago", "____ tranquillo", ["Lago", "Mare", "Fiume", "Pioggia"], "🛶", "Agua tranquila.", "Un bel lago"],
                ["Desierto", "Deserto", "____ caldo", ["Deserto", "Foresta", "Spiaggia", "Montagna"], "🌵", "Mucha arena y sol.", "Il deserto del Sahara"],
                ["Isla", "Isola", "____ tropicale", ["Isola", "Terra", "Città", "Villaggio"], "🏝️", "Tierra rodeada de agua.", "Un'isola privata"],
                ["Ciudad", "Città", "Grande ____", ["Città", "Villaggio", "Casa", "Fattoria"], "🏙️", "Muchos edificios.", "Città di Roma"],
                ["Pueblo", "Villaggio", "Piccolo ____", ["Villaggio", "Città", "Capitale", "Stato"], "🏡", "Lugar pequeño.", "Vivo in un villaggio"],
                ["Mundo", "Mondo", "Il ____", ["Mondo", "Pianeta", "Terra", "Mappa"], "🌍", "Donde vivimos todos.", "Viaggia per il mondo"],
                ["Sol", "Sole", "Il ____", ["Sole", "Luna", "Stelle", "Cielo"], "☀️", "Luz del día.", "Il sole è caldo"],
                ["Luna", "Luna", "____ piena", ["Luna", "Sole", "Stelle", "Cielo"], "🌙", "Luz de noche.", "Guarda la luna"],
                ["Estrellas", "Stelle", "Molte ____", ["Stelle", "Soli", "Lune", "Nuvole"], "✨", "Puntos de luz.", "Le stelle sono luminose"]
            ].map((d, i) => ({ id: 400 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 5, title: "Professioni", icon: "💼",
            levels: [
                ["Doctor", "Dottore", "Vedi un ____", ["Dottore", "Infermiere", "Cuoco", "Pilota"], "👨‍⚕️", "Cura a las personas.", "Lui è un dottore"],
                ["Chef", "Cuoco", "Un grande ____", ["Cuoco", "Dottore", "Autista", "Contadino"], "👨‍🍳", "Cocina comida rica.", "Il cuoco del ristorante"],
                ["Piloto", "Pilota", "____ d'aereo", ["Pilota", "Autista", "Dottore", "Cuoco"], "👨‍✈️", "Vuela aviones.", "Il pilota è pronto"],
                ["Granjero", "Contadino", "Lavora in fattoria", ["Contadino", "Cuoco", "Infermiere", "Dottore"], "👨‍🌾", "Trabaja en el campo.", "Il contadino ha mucche"],
                ["Policía", "Polizia", "Chiama la ____", ["Polizia", "Cuoco", "Pilota", "Dottore"], "👮", "Mantiene la ley.", "L'ufficiale di polizia"],
                ["Bombero", "Pompieri", "Chiama i ____", ["Pompieri", "Polizia", "Cuoco", "Pilota"], "👩‍🚒", "Apaga incendios.", "Un pompiere coraggioso"],
                ["Maestro", "Insegnante", "Il mio ____", ["Insegnante", "Dottore", "Pilota", "Cuoco"], "👩‍🏫", "Enseña cosas nuevas.", "Il mio insegnante di italiano"],
                ["Enfermera", "Infermiere", "L'____ aiuta", ["Infermiere", "Dottore", "Cuoco", "Pilota"], "👩‍⚕️", "Ayuda en el hospital.", "Un infermiere gentile"],
                ["Conductor", "Autista", "____ di taxi", ["Autista", "Pilota", "Cuoco", "Dottore"], "👨‍🚀", "Maneja vehículos.", "Un autista di autobus"],
                ["Artista", "Artista", "Un ____ famoso", ["Artista", "Cuoco", "Dottore", "Pilota"], "🎨", "Crea arte.", "Un artista di talento"],
                ["Abogado", "Avvocato", "Vedi un ____", ["Avvocato", "Dottore", "Cuoco", "Pilota"], "⚖️", "Defiende personas.", "Il mio avvocato è bravo"],
                ["Dentista", "Dentista", "Vai dal ____", ["Dentista", "Dottore", "Infermiere", "Cuoco"], "🦷", "Cuida los dientes.", "Odio il dentista"],
                ["Cantante", "Cantante", "Un ____ pop", ["Cantante", "Artista", "Cuoco", "Pilota"], "🎤", "Canta canciones.", "Il mio cantante preferito"],
                ["Bailarín", "Ballerino", "____ di danza", ["Ballerino", "Cantante", "Artista", "Cuoco"], "💃", "Baila profesionalmente.", "Un ballerino veloce"],
                ["Escritor", "Scrittore", "Un ____ di libri", ["Scrittore", "Artista", "Insegnante", "Cuoco"], "✍️", "Escribe libros.", "Uno scrittore di gialli"],
                ["Fotógrafo", "Fotografo", "____ professionista", ["Fotografo", "Artista", "Cuoco", "Pilota"], "📷", "Toma fotos.", "Il fotografo di matrimoni"],
                ["Ingeniero", "Ingegnere", "____ informatico", ["Ingegnere", "Dottore", "Cuoco", "Pilota"], "🏗️", "Diseña y construye.", "Un ingegnere civile"],
                ["Científico", "Scienziato", "____ di laboratorio", ["Scienziato", "Dottore", "Cuoco", "Insegnante"], "🧪", "Investiga la ciencia.", "Uno scienziato pazzo"],
                ["Astronauta", "Astronauta", "____ spaziale", ["Astronauta", "Pilota", "Cuoco", "Dottore"], "🚀", "Viaja al espacio.", "Il primo astronauta"],
                ["Atleta", "Atleta", "____ olimpico", ["Atleta", "Cantante", "Contadino", "Dottore"], "🏃", "Practica deportes.", "Un atleta forte"]
            ].map((d, i) => ({ id: 500 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 6, title: "Corpo e Salute", icon: "🏥",
            levels: [
                ["Cabeza", "Testa", "La mia ____ fa male", ["Testa", "Mano", "Piede", "Braccio"], "👤", "Parte superior.", "Tocca la tua testa"],
                ["Ojo", "Occhio", "____ blu", ["Occhio", "Orecchio", "Naso", "Bocca"], "👁️", "Para ver.", "Un occhio grande"],
                ["Oreja", "Orecchio", "Ascolta col tuo ____", ["Orecchio", "Occhio", "Naso", "Bocca"], "👂", "Para oír.", "Orecchio sinistro"],
                ["Nariz", "Naso", "Il mio ____", ["Naso", "Orecchio", "Occhio", "Bocca"], "👃", "Para oler.", "Un naso piccolo"],
                ["Boca", "Bocca", "Apri la ____", ["Bocca", "Naso", "Orecchio", "Occhio"], "👄", "Para hablar.", "Una bocca rossa"],
                ["Mano", "Mano", "Lava la tua ____", ["Mano", "Piede", "Braccio", "Gamba"], "✋", "Para tocar.", "Dammi una mano"],
                ["Pie", "Piede", "____ sinistro", ["Piede", "Mano", "Braccio", "Gamba"], "🦶", "Para caminar.", "Su un piede"],
                ["Brazo", "Braccio", "____ forte", ["Braccio", "Gamba", "Mano", "Piede"], "💪", "Extremidad superior.", "Il mio braccio destro"],
                ["Pierna", "Gamba", "____ lunga", ["Gamba", "Braccio", "Mano", "Piede"], "🦵", "Extremidad inferior.", "Rompiti una gamba"],
                ["Corazón", "Cuore", "____ puro", ["Cuore", "Stomaco", "Testa", "Mano"], "❤️", "Bómbea sangre.", "Un cuore freddo"],
                ["Dedo", "Dito", "____ dell'anello", ["Dito", "Dito del piede", "Mano", "Piede"], "☝️", "En la mano.", "Dieci dita"],
                ["Espalda", "Schiena", "La mia ____", ["Schiena", "Petto", "Braccio", "Gamba"], "🧍", "Parte posterior.", "Mal di schiena"],
                ["Dolor", "Dolore", "Molto ____", ["Dolore", "Salute", "Medicina", "Dottore"], "🤕", "Sensación mala.", "In molto dolore"],
                ["Salud", "Salute", "Buona ____", ["Salute", "Dolore", "Medicina", "Dottore"], "🍏", "Estar bien.", "La salute è ricchezza"],
                ["Medicina", "Medicina", "Prendi la ____", ["Medicina", "Cibo", "Acqua", "Latte"], "💊", "Para curarse.", "La medicina del dottore"],
                ["Sangre", "Sangue", "____ rosso", ["Sangue", "Acqua", "Latte", "Succo"], "🩸", "Líquido vital.", "Banca del sangue"],
                ["Hueso", "Osso", "____ rotto", ["Osso", "Sangue", "Dolore", "Salute"], "🦴", "Parte dura interna.", "Un osso forte"],
                ["Cuerpo", "Corpo", "____ umano", ["Corpo", "Testa", "Mano", "Piede"], "🧍", "Todo nosotros.", "Un corpo sano"],
                ["Sueño", "Sonno", "Ho bisogno di ____", ["Sonno", "Mangiare", "Bere", "Giocare"], "😴", "Descansar de noche.", "Vai a dormire"],
                ["Vida", "Vita", "Lunga ____", ["Vita", "Salute", "Dolore", "Corpo"], "🌱", "Estar vivos.", "Una bella vita"]
            ].map((d, i) => ({ id: 600 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 7, title: "Clima e Tempo", icon: "☁️",
            levels: [
                ["Sol", "Sole", "Il ____ caldo", ["Sole", "Luna", "Pioggia", "Neve"], "☀️", "Luz del día.", "Il sole scotta"],
                ["Lluvia", "Pioggia", "____ fredda", ["Pioggia", "Sole", "Neve", "Vento"], "🌧️", "Agua del cielo.", "Amo la pioggia"],
                ["Nieve", "Neve", "____ bianca", ["Neve", "Pioggia", "Sole", "Vento"], "❄️", "Agua helada.", "Prima neve"],
                ["Viento", "Vento", "____ forte", ["Vento", "Pioggia", "Sole", "Neve"], "💨", "Aire en movimiento.", "Il vento soffia"],
                ["Nube", "Nuvola", "____ bianca", ["Nuvola", "Sole", "Pioggia", "Luna"], "☁️", "Mucha agua arriba.", "Una grande nuvola"],
                ["Cielo", "Cielo", "____ blu", ["Cielo", "Nuvola", "Sole", "Luna"], "🌌", "Arriba nuestro.", "Cielo sereno"],
                ["Calor", "Caldo", "Fa ____", ["Caldo", "Freddo", "Pioggia", "Neve"], "🔥", "Mucho sol.", "Una giornata calda"],
                ["Frío", "Freddo", "Fa ____", ["Freddo", "Caldo", "Sole", "Vento"], "🥶", "Poca temperatura.", "Acqua fredda"],
                ["Tormenta", "Tempesta", "Grande ____", ["Tempesta", "Pioggia", "Nuvola", "Vento"], "⛈️", "Lluvia y rayos.", "Tempesta estiva"],
                ["Clima", "Tempo", "Bel ____", ["Tempo", "Sole", "Pioggia", "Giorno"], "🌍", "Estado del aire.", "Com'è il tempo?"],
                ["Día", "Giorno", "Un ____ di sole", ["Giorno", "Notte", "Mattina", "Sera"], "☀️", "Luz.", "Buona giornata"],
                ["Noche", "Notte", "____ stellata", ["Notte", "Giorno", "Mattina", "Sera"], "🌙", "Oscuridad.", "Buonanotte"],
                ["Mañana", "Mattina", "Buona ____", ["Mattina", "Notte", "Giorno", "Sera"], "🌅", "Primeras horas.", "Di mattina"],
                ["Tarde", "Pomeriggio", "Buon ____", ["Pomeriggio", "Mattina", "Notte", "Giorno"], "🌤️", "Horas medias.", "Ogni pomeriggio"],
                ["Semana", "Settimana", "Scorsa ____", ["Settimana", "Mese", "Anno", "Giorno"], "📅", "Siete días.", "Prossima settimana"],
                ["Mes", "Mese", "Questo ____", ["Mese", "Settimana", "Anno", "Giorno"], "🗓️", "Treinta días.", "Ogni mese"],
                ["Año", "Anno", "Nuovo ____", ["Anno", "Mese", "Settimana", "Giorno"], "🎉", "Doce meses.", "Felice Anno Nuovo"],
                ["Hora", "Ora", "Un'____", ["Ora", "Minuto", "Secondo", "Giorno"], "⏰", "Sesenta minutos.", "Aspetta un'ora"],
                ["Minuto", "Minuto", "Cinque ____", ["Minuto", "Ora", "Secondo", "Giorno"], "⏱️", "Sesenta segundos.", "Un minuto, per favore"],
                ["Segunda", "Secondo", "Aspetta un ____", ["Secondo", "Minuto", "Ora", "Giorno"], "⌛", "Tiempo muy corto.", "Aspetta un secondo"]
            ].map((d, i) => ({ id: 700 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 8, title: "Abbigliamento", icon: "🛍️",
            levels: [
                ["Camisa", "Camicia", "____ blu", ["Camicia", "Pantaloni", "Abito", "Scarpa"], "👕", "Ropa de arriba.", "Una camicia di cotone"],
                ["Pantalón", "Pantaloni", "____ lunghi", ["Pantaloni", "Camicia", "Abito", "Scarpa"], "👖", "Ropa de piernas.", "Pantaloni blu"],
                ["Vestido", "Abito", "____ rosso", ["Abito", "Camicia", "Pantaloni", "Scarpa"], "👗", "Ropa de fiesta.", "Un bell'abito"],
                ["Zapato", "Scarpa", "____ nera", ["Scarpa", "Camicia", "Pantaloni", "Abito"], "👞", "Para los pies.", "Corri con le scarpe"],
                ["Gorra", "Cappello", "Bel ____", ["Cappello", "Camicia", "Pantaloni", "Abito"], "🧢", "Para la cabeza.", "Indossa un cappello"],
                ["Ropa", "Vestiti", "____ nuovi", ["Vestiti", "Scarpe", "Borse", "Cappello"], "👗", "Todo lo que usamos.", "Vestiti puliti"],
                ["Precio", "Prezzo", "____ alto", ["Prezzo", "Soldi", "Conto", "Costo"], "💰", "Lo que cuesta.", "Il miglior prezzo"],
                ["Barato", "Economico", "Molto ____", ["Economico", "Costoso", "Nuovo", "Vecchio"], "🏷️", "Cuesta poco.", "Cibo economico"],
                ["Caro", "Costoso", "È ____", ["Costoso", "Economico", "Nuovo", "Vecchio"], "💎", "Cuesta mucho.", "Un'auto costosa"],
                ["Comprar", "Comprare", "Voglio ____", ["Comprare", "Vendere", "Dare", "Prendere"], "🛒", "Adquirir algo.", "Compra un regalo"],
                ["Vender", "Vendere", "Voglio ____", ["Vendere", "Comprare", "Dare", "Prendere"], "🏪", "Dar por dinero.", "Vendi la mia auto"],
                ["Chaqueta", "Giacca", "____ invernale", ["Giacca", "Camicia", "Cappotto", "Abito"], "🧥", "Para el frío.", "Una giacca calda"],
                ["Calcetín", "Calzino", "____ sinistro", ["Calzino", "Scarpa", "Pantaloni", "Camicia"], "🧦", "Debajo del zapato.", "Un calzino bianco"],
                ["Gafas", "Occhiali", "____ da sole", ["Occhiali", "Cappello", "Anello", "Orologio"], "🕶️", "Para los ojos.", "Indossa gli occhiali"],
                ["Reloj", "Orologio", "____ da polso", ["Orologio", "Orologio", "Anello", "Cappello"], "⌚", "Para ver la hora.", "Un orologio d'argento"],
                ["Bolso", "Borsa", "____ a mano", ["Borsa", "Scatola", "Valigia", "Tasca"], "👜", "Para llevar cosas.", "Porta una borsa"],
                ["Cinturón", "Cintura", "____ di pelle", ["Cintura", "Pantaloni", "Camicia", "Abito"], "🎗️", "Para ajustar.", "Una cintura nera"],
                ["Traje", "Completo", "____ nero", ["Completo", "Camicia", "Pantaloni", "Abito"], "👔", "Ropa formal.", "Indossa un completo"],
                ["Bufanda", "Sciarpa", "____ lunga", ["Sciarpa", "Cappello", "Cappotto", "Guanto"], "🧣", "Para el cuello.", "Una sciarpa di lana"],
                ["Guantes", "Guanti", "Paio di ____", ["Guanti", "Calzini", "Scarpe", "Cappelli"], "🧤", "Para las manos.", "Mani fredde, guanti caldi"]
            ].map((d, i) => ({ id: 800 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 9, title: "Intrattenimento", icon: "🎮",
            levels: [
                ["Juego", "Gioco", "Nuovo ____", ["Gioco", "Giocare", "Sport", "Lavoro"], "🎮", "Para divertirse.", "Un gioco divertente"],
                ["Cine", "Cinema", "Vai al ____", ["Cinema", "Negozio", "Banca", "Parco"], "🎬", "Ver películas.", "Al cinema"],
                ["Cuento", "Storia", "Racconta una ____", ["Storia", "Canzone", "Gioco", "Teatro"], "📚", "Narración.", "Una storia della buonanotte"],
                ["Música", "Musica", "Ascolta la ____", ["Musica", "Suono", "Rumore", "Voce"], "🎵", "Sonidos rítmicos.", "Musica dolce"],
                ["Baile", "Ballo", "Facciamo un ____", ["Ballo", "Cantare", "Giocare", "Correre"], "💃", "Mover el cuerpo.", "Impara il ballo"],
                ["Fiesta", "Festa", "____ di compleanno", ["Festa", "Lavoro", "Scuola", "Casa"], "🥳", "Celebración.", "Una grande festa"],
                ["Película", "Film", "____ spaventoso", ["Film", "Libro", "Canzone", "Gioco"], "🎥", "Historia visual.", "Guarda un film"],
                ["Radio", "Radio", "Alla ____", ["Radio", "Telefono", "TV", "Web"], "📻", "Para oír noticias.", "Ascolta la radio"],
                ["Tele", "TV", "Guarda la ____", ["TV", "Radio", "Libro", "Gioco"], "📺", "Televisión.", "Accendi la TV"],
                ["Libro", "Libro", "Leggi un ____", ["Libro", "Penna", "Pagina", "Tavolo"], "📖", "Hojas escritas.", "Un libro lungo"],
                ["Actor", "Attore", "____ famoso", ["Attore", "Cantante", "Artista", "Dottore"], "🎭", "Actúa en cine.", "Un attore di Hollywood"],
                ["Pintura", "Quadro", "____ a olio", ["Quadro", "Foto", "Disegno", "Arte"], "🎨", "Arte con pincel.", "Un bel quadro"],
                ["Dibujo", "Disegno", "____ a matita", ["Disegno", "Quadro", "Foto", "Arte"], "✏️", "Arte con lápiz.", "Fai un disegno"],
                ["Museo", "Museo", "____ di storia", ["Museo", "Cinema", "Negozio", "Parco"], "🏛️", "Donde hay arte.", "Visita il museo"],
                ["Teatro", "Teatro", "Vecchio ____", ["Teatro", "Cinema", "Negozio", "Parco"], "🏟️", "Obras en vivo.", "A teatro"],
                ["Concierto", "Concerto", "____ rock", ["Concerto", "Film", "Gioco", "Festa"], "🎸", "Música en vivo.", "Vai a un concerto"],
                ["Piano", "Pianoforte", "Suona il ____", ["Pianoforte", "Chitarra", "Tamburo", "Violino"], "🎹", "Instrumento de teclas.", "Il grande pianoforte"],
                ["Guitarra", "Chitarra", "____ elettrica", ["Chitarra", "Pianoforte", "Tamburo", "Violino"], "🎸", "Instrumento de cuerdas.", "Una chitarra rumorosa"],
                ["Tambor", "Tamburo", "Suona il ____", ["Tamburo", "Pianoforte", "Chitarra", "Violino"], "🥁", "Instrumento de percusión.", "Un grande tamburo"],
                ["Violín", "Violino", "____ classico", ["Violino", "Pianoforte", "Chitarra", "Tamburo"], "🎻", "Instrumento delicado.", "Il piccolo violino"]
            ].map((d, i) => ({ id: 900 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 10, title: "Sport e Tempo Libero", icon: "⚽",
            levels: [
                ["Fútbol", "Calcio", "Gioca a ____", ["Calcio", "Tennis", "Golf", "Corsa"], "⚽", "Con los pies.", "Calcio italiano"],
                ["Tenis", "Tennis", "Gioca a ____", ["Tennis", "Calcio", "Golf", "Corsa"], "🎾", "Con raqueta.", "Gioca a tennis"],
                ["Correr", "Correre", "Mi piace ____", ["Correre", "Nuotare", "Camminare", "Saltare"], "🏃", "Ir rápido a pie.", "Corri veloce"],
                ["Nadar", "Nuotare", "Nella piscina", ["Nuotare", "Correre", "Camminare", "Saltare"], "🏊", "En el agua.", "Nuota come un pesce"],
                ["Golf", "Golf", "Gioca a ____", ["Golf", "Tennis", "Calcio", "Corsa"], "⛳", "Con hoyos.", "Una partita di golf"],
                ["Bici", "Bici", "Guida la ____", ["Bici", "Auto", "Bus", "Treno"], "🚲", "Dos ruedas.", "La mia bici rossa"],
                ["Pelota", "Palla", "Calcia la ____", ["Palla", "Mazza", "Rete", "Porta"], "⚽", "Redonda.", "Una palla di plastica"],
                ["Equipo", "Squadra", "Migliore ____", ["Squadra", "Giocatore", "Gioco", "Vittoria"], "👫", "Grupo unido.", "Una squadra forte"],
                ["Ganar", "Vincere", "Voglio ____", ["Vincere", "Perdere", "Pareggiare", "Giocare"], "🏆", "Ser el primero.", "Vinci la partita"],
                ["Jugar", "Giocare", "Andiamo a ____", ["Giocare", "Lavorare", "Dormire", "Mangiare"], "🎮", "Hacer deporte.", "Gioca con amici"],
                ["Perder", "Perdere", "Non ____", ["Perdere", "Vincere", "Pareggiare", "Giocare"], "😢", "No ser primero.", "Non perdere"],
                ["Empate", "Pareggio", "È un ____", ["Pareggio", "Vittoria", "Sconfitta", "Partita"], "🤝", "Iguales.", "Un pareggio giusto"],
                ["Entrenar", "Allenarsi", "Devo ____", ["Allenarsi", "Giocare", "Lavorare", "Riposare"], "💪", "Practicar.", "Allenati duramente"],
                ["Gimnasio", "Palestra", "Vai in ____", ["Palestra", "Negozio", "Banca", "Parco"], "🏋️", "Hacer ejercicio.", "Nella palestra locale"],
                ["Piscina", "Piscina", "____ blu", ["Piscina", "Lago", "Mare", "Fiume"], "🏊", "Donde nadas.", "Una piscina pulita"],
                ["Estadio", "Stadio", "Grande ____", ["Stadio", "Palestra", "Parco", "Cinema"], "🏟️", "Donde hay partidos.", "Lo stadio cittadino"],
                ["Caminar", "Camminare", "Fai una ____", ["Camminata", "Corsa", "Nuotata", "Salto"], "🚶", "Ir a pie.", "Cammina nel parco"],
                ["Saltar", "Saltare", "Posso ____", ["Saltare", "Correre", "Nuotare", "Camminare"], "🦘", "Hacia arriba.", "Salta in alto"],
                ["Cantar", "Cantare", "Prova a ____", ["Cantare", "Ballare", "Parlare", "Ascoltare"], "🎤", "Voz musical.", "Canta una canzone"],
                ["Reír", "Ridere", "Sempre ____", ["Ridere", "Piangere", "Sorridere", "Arrabbiato"], "😂", "Felicidad.", "Ridere forte"]
            ].map((d, i) => ({ id: 1000 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 11, title: "Tecnologia", icon: "💻",
            levels: [
                ["Compu", "Computer", "____ veloce", ["Computer", "Telefono", "Radio", "TV"], "💻", "Para trabajar.", "Il mio nuovo computer"],
                ["Celular", "Cellulare", "____ mobile", ["Cellulare", "Radio", "TV", "Web"], "📱", "En tu mano.", "Chiamami"],
                ["Internet", "Internet", "Su ____", ["Internet", "Radio", "TV", "Telefono"], "🌐", "Mundo conectado.", "Cerca su Internet"],
                ["Correo", "Email", "Invia una ____", ["Email", "Lettera", "Chiamata", "Gioco"], "📧", "Mensaje digital.", "Controlla la mia email"],
                ["Web", "Sito web", "Visita un ____", ["Sito web", "Email", "Telefono", "TV"], "🌍", "Sitio digital.", "Un sito veloce"],
                ["Clave", "Password", "____ sicura", ["Password", "Nome", "Mail", "Parola"], "🔐", "Secreto.", "Qual è la password?"],
                ["Pantalla", "Schermo", "Grande ____", ["Schermo", "Telefono", "Mouse", "Tasto"], "📺", "Donde ves todo.", "Uno schermo piatto"],
                ["Teclado", "Tastiera", "Scrivi sulla ____", ["Tastiera", "Mouse", "Schermo", "Telefono"], "⌨️", "Para escribir.", "Una tastiera meccanica"],
                ["Ratón", "Mouse", "____ del pc", ["Mouse", "Schermo", "Tasto", "Telefono"], "🖱️", "Mueve flecha.", "Un mouse wireless"],
                ["Código", "Codice", "Scrivi ____", ["Codice", "Parola", "Mail", "Chiamata"], "⌨️", "Para programar.", "Impara a programmare"],
                ["Robot", "Robot", "____ intelligente", ["Robot", "Uomo", "Cane", "Gatto"], "🤖", "Hombre de metal.", "Il piccolo robot"],
                ["Espacio", "Spazio", "____ aperto", ["Spazio", "Cielo", "Nuvola", "Sole"], "🚀", "Estrellas y luna.", "Viaggia nello spazio"],
                ["Nave", "Astronave", "____ veloce", ["Astronave", "Auto", "Bus", "Treno"], "🛸", "Vuela lejos.", "L'astronave argentata"],
                ["Futuro", "Futuro", "____ intelligente", ["Futuro", "Passato", "Adesso", "Oggi"], "⏳", "Lo que vendrá.", "Nel futuro"],
                ["Chip", "Chip", "Piccolo ____", ["Chip", "Carta", "Chiave", "Scatola"], "💾", "Cerebro digital.", "Un chip di silicone"],
                ["Cable", "Cavo", "____ lungo", ["Cavo", "Filo", "Link", "Linea"], "🔌", "Para corriente.", "Collega il cavo"],
                ["Batería", "Batteria", "____ carica", ["Batteria", "Potenza", "Basso", "Vita"], "🔋", "Energía.", "Carica la batteria"],
                ["Wifi", "Wifi", "____ gratis", ["Wifi", "Link", "Web", "Rete"], "📶", "Señal sin hilos.", "Dov'è il wifi?"],
                ["App", "App", "____ mobile", ["App", "Gioco", "Web", "Mail"], "📱", "Programa de móvil.", "Installa l'app"],
                ["Juego", "Videogioco", "____ video", ["Videogioco", "App", "Web", "Mail"], "🎮", "Diversión digital.", "Amo questo videogioco"]
            ].map((d, i) => ({ id: 1100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 12, title: "Sentimenti", icon: "🔥",
            levels: [
                ["Amor", "Amore", "Ti ____", ["Amo", "Odio", "Piaccio", "Voglio"], "❤️", "Sentir mucho.", "Vero amore"],
                ["Odio", "Odio", "Ferma l'____", ["Odio", "Amore", "Piacere", "Volere"], "😠", "Sentir mal.", "Non odiare"],
                ["Feliz", "Felice", "Mi sento ____", ["Felice", "Triste", "Arrabbiato", "Paura"], "😊", "Estar bien.", "Sono felice"],
                ["Triste", "Triste", "Non essere ____", ["Triste", "Felice", "Arrabbiato", "Paura"], "😢", "Estar mal.", "Un giorno triste"],
                ["Enojo", "Arrabbiato", "Smetti di essere ____", ["Arrabbiato", "Felice", "Triste", "Paura"], "😡", "Mucha rabia.", "L'uomo arrabbiato"],
                ["Miedo", "Paura", "Niente ____", ["Paura", "Amore", "Speranza", "Gioia"], "😨", "Susto.", "Affronta la paura"],
                ["Paz", "Pace", "____ nel mondo", ["Pace", "Guerra", "Amore", "Speranza"], "🕊️", "Tranquilidad.", "Pace interiore"],
                ["Guerra", "Guerra", "Ferma la ____", ["Guerra", "Pace", "Amore", "Speranza"], "💣", "Conflicto.", "Una lunga guerra"],
                ["Risa", "Risata", "Una grande ____", ["Risata", "Pianto", "Sorriso", "Rabbia"], "😄", "Jajaja.", "Una risata forte"],
                ["Llantos", "Pianto", "Non ____", ["Piangere", "Ridere", "Sorridere", "Arrabbiarsi"], "😭", "Lágrimas.", "Bimbo piange"],
                ["Deseo", "Desiderio", "Ho un ____", ["Desiderio", "Piacere", "Bisogno", "Avere"], "💫", "Querer algo.", "Voglio di più"],
                ["Gusto", "Mi piace", "____ il cibo", ["Mi piace", "Amo", "Voglio", "Ho bisogno"], "👍", "Agradar.", "Mi piace la pizza"],
                ["Necesidad", "Bisogno", "Ho ____ di acqua", ["Bisogno", "Voglia", "Piacere", "Avere"], "🆘", "Ser urgente.", "Hai bisogno di aiuto"],
                ["Tener", "Avere", "Io ____ un'auto", ["Ho", "Bisogno", "Voglio", "Mi piace"], "🤲", "Posesión.", "Ho una casa"],
                ["Ser", "Essere", "Solo ____", ["Essere", "Avere", "Bisogno", "Volere"], "🧘", "Existir.", "Essere o non essere"],
                ["Amigo", "Amico", "Migliore ____", ["Amico", "Nemico", "Ragazzo", "Ragazza"], "👫", "Persona cercana.", "Un buon amico"],
                ["Enemigo", "Nemico", "Uccidi il ____", ["Nemico", "Amico", "Uomo", "Donna"], "🦹", "Persona contraria.", "Stai lontano dal nemico"],
                ["Familia", "Famiglia", "Grande ____", ["Famiglia", "Amico", "Squadra", "Gruppo"], "👨‍👩‍👧‍👦", "Parientes.", "Amo la mia famiglia"],
                ["Hogar", "Casa", "Vado a ____", ["Casa", "Negozio", "Lavoro", "Scuola"], "🏠", "Donde vives.", "Casa dolce casa"],
                ["Mundo", "Mondo", "Tutto il ____", ["Mondo", "Casa", "Città", "Terra"], "🌍", "Todo el planeta.", "Salva il mondo"]
            ].map((d, i) => ({ id: 1200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        }
    ]
};
