// === BASE DE DATOS DE LECCIONES: NORUEGO (ES -> NO) ===
window.courseNo = {
    title: "Norskkurs",
    mission: "Oppdrag: Nivå A1 (Nybegynner)",
    langCode: "no-NO",
    units: [
        {
            id: 1, title: "Første Skritt", icon: "🇳🇴",
            levels: [
                ["Hola", "Hei", "____!", ["Hei", "Ha det", "Vann", "Brød"], "👋", "Para saludar usa <b>Hei</b>.", "Hei!"],
                ["Yo soy", "Jeg er", "____ Alex", ["Jeg er", "Du er", "Han er", "Vi er"], "👤", "Presentarse con <b>Jeg er</b>.", "Jeg er Alex"],
                ["Uno", "En", "Nummer ____", ["En", "To", "Tre", "Fire"], "1️⃣", "El número uno.", "En takk"],
                ["Adiós", "Ha det", "____!", ["Ha det", "Hei", "Vær så snill", "Takk"], "🏃", "Despedirse con <b>Ha det</b>.", "Ha det bra!"],
                ["Dos", "To", "Nummer ____", ["To", "En", "Tre", "Fire"], "2️⃣", "El número dos.", "To øl"],
                ["Por favor", "Vær så snill", "____, hjelp meg", ["Vær så snill", "Takk", "Ja", "Nei"], "🙏", "Pedir cosas con <b>Vær så snill</b>.", "En kaffe, vær så snill"],
                ["Gracias", "Takk", "Mange ____", ["Takk", "Vær så snill", "Hei", "Nei"], "✨", "Agradecer con <b>Takk</b>.", "Tusen takk"],
                ["Tres", "Tre", "Nummer ____", ["Tre", "To", "En", "Fire"], "3️⃣", "El número tres.", "Tre hunder"],
                ["Sí", "Ja", "____, jeg er", ["Ja", "Nei", "Kanskje", "Aldri"], "✅", "Afirmar con <b>Ja</b>.", "Ja, takk"],
                ["No", "Nei", "____, takk", ["Nei", "Ja", "Sikkert", "Alltid"], "❌", "Negar con <b>Nei</b>.", "Nei, dessverre"],
                ["Buenos días", "God morgen", "____!", ["God morgen", "God natt", "Hei", "Hallo"], "🌅", "Saludo matutino.", "God morgen!"],
                ["Hombre", "Mann", "En ____", ["Mann", "Kvinne", "Gutt", "Jente"], "👨", "Vocabulario: Hombre.", "En høy mann"],
                ["Mujer", "Kvinne", "En ____", ["Kvinne", "Mann", "Jente", "Gutt"], "👩", "Vocabulario: Mujer.", "En sterk kvinne"],
                ["Niño", "Gutt", "En ____", ["Gutt", "Jente", "Mann", "Kvinne"], "👦", "Vocabulario: Niño.", "En glad gutt"],
                ["Niña", "Jente", "En ____", ["Jente", "Gutt", "Kvinne", "Mann"], "👧", "Vocabulario: Niña.", "En liten jente"],
                ["Cuatro", "Fire", "Nummer ____", ["Fire", "Tre", "Fem", "Seks"], "4️⃣", "El número cuatro.", "Fire bøker"],
                ["Cinco", "Fem", "Nummer ____", ["Fem", "Fire", "Seks", "Syv"], "5️⃣", "El número cinco.", "Fem stjerner"],
                ["Nombre", "Navn", "Mitt ____ er...", ["Navn", "Er", "Jeg", "Heter"], "📛", "Preguntar o decir el nombre.", "Mitt navn er Ole"],
                ["Perro", "Hund", "Min ____", ["Hund", "Katt", "Fugl", "Fisk"], "🐶", "Mascotas: Perro.", "Jeg elsker hunden min"],
                ["Gato", "Katt", "Min ____", ["Katt", "Hund", "Fugl", "Mus"], "🐱", "Mascotas: Gato.", "Den svarte katten"]
            ].map((d, i) => ({ id: 100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 2, title: "Byen", icon: "🏙️",
            levels: [
                ["Casa", "Hus", "Mitt ____", ["Hus", "Bil", "Gate", "Park"], "🏠", "Donde vives.", "Mitt store hus"],
                ["Auto", "Bil", "Rød ____", ["Bil", "Buss", "Tog", "Fly"], "🚗", "Vehículo común.", "Jeg har en bil"],
                ["Calle", "Gate", "På ____", ["Gate", "Vei", "Hus", "Park"], "🛣️", "Por donde caminas.", "Hovedgaten"],
                ["Parque", "Park", "I ____", ["Park", "Hus", "Skole", "Bank"], "🌳", "Lugar verde.", "I parken"],
                ["Banco", "Bank", "Hvor er ____?", ["Bank", "Kafé", "Park", "Butikk"], "🏦", "Donde está el dinero.", "Sentralbanken"],
                ["Tienda", "Butikk", "Stor ____", ["Butikk", "Hus", "Park", "Gate"], "🏬", "Lugar para comprar.", "Apple butikk"],
                ["Escuela", "Skole", "Gå til ____", ["Skole", "Butikk", "Bank", "Bil"], "🏫", "Lugar de estudio.", "På skolen"],
                ["Hospital", "Sykehus", "Nærmeste ____", ["Sykehus", "Park", "Kafé", "Bank"], "🏥", "Salud.", "Bysykehuset"],
                ["Café", "Kafé", "La oss gå på ____", ["Kafé", "Butikk", "Bank", "Park"], "☕", "Lugar para beber café.", "Jeg liker denne kaféen"],
                ["Bus", "Buss", "Ta ____", ["Buss", "Bil", "Sykkel", "Taxi"], "🚌", "Transporte público.", "Skolebussen"],
                ["Taxi", "Taxi", "Ring en ____", ["Taxi", "Buss", "Sykkel", "Fly"], "🚕", "Transporte privado.", "Gul taxi"],
                ["Bici", "Sykkel", "Kjør ____", ["Sykkel", "Buss", "Bil", "Taxi"], "🚲", "Dos ruedas.", "Min nye sykkel"],
                ["Tren", "Tog", "Raskt ____", ["Tog", "Buss", "Fly", "Bil"], "🚆", "Vías de hierro.", "Morgentoget"],
                ["Avión", "Fly", "Det ____", ["Fly", "Bil", "Båt", "Buss"], "✈️", "Para volar.", "Det blå flyet"],
                ["Barco", "Båt", "En ____", ["Båt", "Bil", "Sykkel", "Buss"], "🚢", "Por el agua.", "En stor båt"],
                ["Hotel", "Hotell", "Luksus ____", ["Hotell", "Hus", "Bank", "Park"], "🏨", "Para dormir fuera.", "Bo på hotell"],
                ["Cine", "Kino", "På ____", ["Kino", "Park", "Butikk", "Bank"], "🎬", "Ver películas.", "Gå på kino"],
                ["Puente", "Bro", "Over ____", ["Bro", "Gate", "Vei", "Hus"], "🌉", "Une dos caminos.", "London Bridge"],
                ["Museo", "Museum", "Kunst____", ["Museum", "Butikk", "Park", "Bank"], "🏛️", "Historia y arte.", "Besøk museet"],
                ["Policía", "Politi", "Ring ____", ["Politi", "Lege", "Brannmann", "Sykepleier"], "🚓", "Seguridad.", "Politistasjon"]
            ].map((d, i) => ({ id: 200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 3, title: "Restauranten", icon: "🍕",
            levels: [
                ["Agua", "Vann", "Et glass ____", ["Vann", "Vin", "Juice", "Melk"], "💧", "Bebida básica.", "Jeg trenger vann"],
                ["Pan", "Brød", "Smør og ____", ["Brød", "Kake", "Kjøtt", "Ris"], "🍞", "Para acompañar.", "Ferskt brød"],
                ["Pizza", "Pizza", "Jeg liker ____", ["Pizza", "Pasta", "Suppe", "Salat"], "🍕", "Comida italiana.", "En pizza, takk"],
                ["Carne", "Kjøtt", "Spis ____", ["Kjøtt", "Frukt", "Brød", "Sukker"], "🥩", "Proteína.", "Stekt kjøtt"],
                ["Fruta", "Frukt", "Frisk ____", ["Frukt", "Kjøtt", "Brød", "Ris"], "🍎", "Sano y dulce.", "Spis mer frukt"],
                ["Arroz", "Ris", "Kylling og ____", ["Ris", "Brød", "Pasta", "Kjøtt"], "🍚", "Grano común.", "Hvit ris"],
                ["Ensalada", "Salat", "Grønn ____", ["Salat", "Pizza", "Suppe", "Kjøtt"], "🥗", "Vegetales mixtos.", "En frisk salat"],
                ["Sopa", "Suppe", "Varm ____", ["Suppe", "Salat", "Pizza", "Pasta"], "🥣", "Líquido caliente.", "Tomatsuppe"],
                ["Pasta", "Pasta", "Italiensk ____", ["Pasta", "Pizza", "Suppe", "Ris"], "🍝", "Fideos y más.", "Jeg elsker pasta"],
                ["Leche", "Melk", "Kaffe med ____", ["Melk", "Vann", "Juice", "Vin"], "🥛", "Bebida blanca.", "Kald melk"],
                ["Vino", "Vin", "Rød ____", ["Vin", "Vann", "Melk", "Øl"], "🍷", "Bebida alcohólica.", "Et glass vin"],
                ["Cerveza", "Øl", "Kald ____", ["Øl", "Vin", "Vann", "Melk"], "🍺", "Bebida de cebada.", "To øl, takk"],
                ["Té", "Te", "Varm ____", ["Te", "Kaffe", "Melk", "Vann"], "🍵", "Infusión.", "Grønn te"],
                ["Huevo", "Egg", "Stekt ____", ["Egg", "Brød", "Kjøtt", "Frukt"], "🥚", "Desayuno común.", "Et egg, takk"],
                ["Queso", "Ost", "Skinke og ____", ["Ost", "Brød", "Kjøtt", "Frukt"], "🧀", "Producto lácteo.", "Jeg elsker ost"],
                ["Pescado", "Fisk", "Grillet ____", ["Fisk", "Kjøtt", "Kylling", "Biff"], "🐟", "Del mar.", "Fersk fisk"],
                ["Pollo", "Kylling", "Stekt ____", ["Kylling", "Kjøtt", "Fisk", "Biff"], "🍗", "Ave común.", "Kylling og pommes frites"],
                ["Postre", "Dessert", "Sjokolade til ____", ["Dessert", "Kjøtt", "Suppe", "Salat"], "🍰", "Algo dulce al final.", "Hva er til dessert?"],
                ["Cena", "Middag", "Spis ____", ["Middag", "Lunsj", "Frokost", "Snack"], "🍽️", "Comida nocturna.", "La oss spise middag"],
                ["Cuenta", "Regning", "____, takk", ["Regning", "Meny", "Bord", "Mat"], "💵", "Para pagar.", "Regningen, takk"]
            ].map((d, i) => ({ id: 300 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 4, title: "Reise", icon: "✈️",
            levels: [
                ["Maleta", "Koffert", "Min ____", ["Koffert", "Veske", "Pass", "Billett"], "🧳", "Para llevar ropa.", "Pakk kofferten"],
                ["Pasaporte", "Pass", "Vis ditt ____", ["Pass", "Billett", "ID", "Penger"], "🛂", "Documento de viaje.", "Mitt pass er klart"],
                ["Boleto", "Billett", "Tog____", ["Billett", "Penger", "Veske", "Kart"], "🎟️", "Para entrar.", "Jeg har billetten"],
                ["Mapa", "Kart", "Se på ____", ["Kart", "Bok", "Gate", "Park"], "🗺️", "Para no perderse.", "Hvor er kartet?"],
                ["Dinero", "Penger", "Enkle ____", ["Penger", "Billett", "Veske", "Gave"], "💵", "Para comprar.", "Jeg trenger penger"],
                ["Cámara", "Kamera", "Ta et ____", ["Kamera", "Telefon", "Foto", "Veske"], "📷", "Para fotos.", "Smil til kameraet"],
                ["Playa", "Strand", "På ____en", ["Strand", "Fjell", "Skog", "Ørken"], "🏖️", "Arena y mar.", "Jeg elsker stranden"],
                ["Montaña", "Fjell", "Høyt ____", ["Fjell", "Strand", "Elv", "Innsjø"], "⛰️", "Naturaleza alta.", "Klatre på fjellet"],
                ["Bosque", "Skog", "Grønn ____", ["Skog", "Strand", "Ørken", "By"], "🌲", "Muchos árboles.", "I skogen"],
                ["Río", "Elv", "Kald ____", ["Elv", "Hav", "Innsjø", "Basseng"], "🏞️", "Agua corriente.", "Nær elven"],
                ["Mar", "Hav", "Blått ____", ["Hav", "Elv", "Innsjø", "Basseng"], "🌊", "Agua salada.", "Dypt hav"],
                ["Lago", "Innsjø", "Stille ____", ["Innsjø", "Hav", "Elv", "Regn"], "🛶", "Agua tranquila.", "En vakker innsjø"],
                ["Desierto", "Ørken", "Varm ____", ["Ørken", "Skog", "Strand", "Fjell"], "🌵", "Mucha arena y sol.", "Sahara ørkenen"],
                ["Isla", "Øy", "Tropisk ____", ["Øy", "Land", "By", "Landsby"], "🏝️", "Tierra rodeada de agua.", "En privat øy"],
                ["Ciudad", "By", "Stor ____", ["By", "Landsby", "Hus", "Gård"], "🏙️", "Muchos edificios.", "Oslo by"],
                ["Pueblo", "Landsby", "Liten ____", ["Landsby", "By", "Hovedstad", "Stat"], "🏡", "Lugar pequeño.", "Jeg bor i en landsby"],
                ["Mundo", "Verden", "Hele ____", ["Verden", "Planet", "Jord", "Kart"], "🌍", "Donde vivimos todos.", "Reis verden rundt"],
                ["Sol", "Sol", "____en", ["Sol", "Måne", "Stjerner", "Himmel"], "☀️", "Luz del día.", "Solen er varm"],
                ["Luna", "Måne", "Full____", ["Måne", "Sol", "Stjerner", "Himmel"], "🌙", "Luz de noche.", "Se på månen"],
                ["Estrellas", "Stjerner", "Mange ____", ["Stjerner", "Sol", "Måne", "Skyer"], "✨", "Puntos de luz.", "Stjernene er lyse"]
            ].map((d, i) => ({ id: 400 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 5, title: "Yrker", icon: "💼",
            levels: [
                ["Doctor", "Lege", "Se en ____", ["Lege", "Sykepleier", "Kokk", "Pilot"], "👨‍⚕️", "Cura a las personas.", "Han er lege"],
                ["Chef", "Kokk", "En god ____", ["Kokk", "Lege", "Sjåfør", "Bonde"], "👨‍🍳", "Cocina comida rica.", "Restaurantkokken"],
                ["Piloto", "Pilot", "Fly____", ["Pilot", "Sjåfør", "Lege", "Kokk"], "👨‍✈️", "Vuela aviones.", "Piloten er klar"],
                ["Granjero", "Bonde", "Jobber på gård", ["Bonde", "Kokk", "Sykepleier", "Lege"], "👨‍🌾", "Trabaja en el campo.", "Bonden har kuer"],
                ["Policía", "Politi", "Ring ____", ["Politi", "Kokk", "Pilot", "Lege"], "👮", "Mantiene la ley.", "Politibetjenten"],
                ["Bombero", "Brannmann", "Ring ____", ["Brannmann", "Politi", "Kokk", "Pilot"], "👩‍🚒", "Apaga incendios.", "En modig brannmann"],
                ["Maestro", "Lærer", "Min ____", ["Lærer", "Lege", "Pilot", "Kokk"], "👩‍🏫", "Enseña cosas nuevas.", "Min norsklærer"],
                ["Enfermera", "Sykepleier", "____en hjelper", ["Sykepleier", "Lege", "Kokk", "Pilot"], "👩‍⚕️", "Ayuda en el hospital.", "En snill sykepleier"],
                ["Conductor", "Sjåfør", "Taxi____", ["Sjåfør", "Pilot", "Kokk", "Lege"], "👨‍🚀", "Maneja vehículos.", "En bussjåfør"],
                ["Artista", "Kunstner", "En berømt ____", ["Kunstner", "Kokk", "Lege", "Pilot"], "🎨", "Crea arte.", "En talentfull kunstner"],
                ["Abogado", "Advokat", "Se en ____", ["Advokat", "Lege", "Kokk", "Pilot"], "⚖️", "Defiende personas.", "Min advokat er god"],
                ["Dentista", "Tannlege", "Gå til ____", ["Tannlege", "Lege", "Sykepleier", "Kokk"], "🦷", "Cuida los dientes.", "Jeg hater tannlegen"],
                ["Cantante", "Sanger", "En pop____", ["Sanger", "Kunstner", "Kokk", "Pilot"], "🎤", "Canta canciones.", "Min favorittsanger"],
                ["Bailarín", "Danser", "Ballett____", ["Danser", "Sanger", "Kunstner", "Kokk"], "💃", "Baila profesionalmente.", "En rask danser"],
                ["Escritor", "Forfatter", "En bok____", ["Forfatter", "Kunstner", "Lærer", "Kokk"], "✍️", "Escribe libros.", "En krimforfatter"],
                ["Fotógrafo", "Fotograf", "Proff ____", ["Fotograf", "Kunstner", "Kokk", "Pilot"], "📷", "Toma fotos.", "Bryllupsfotografen"],
                ["Ingeniero", "Ingeniør", "Software____", ["Ingeniør", "Lege", "Kokk", "Pilot"], "🏗️", "Diseña y construye.", "En sivilingeniør"],
                ["Científico", "Forsker", "Laboratorie____", ["Forsker", "Lege", "Kokk", "Lærer"], "🧪", "Investiga la ciencia.", "En gal forsker"],
                ["Astronaut", "Astronaut", "Rom____", ["Astronaut", "Pilot", "Kokk", "Lege"], "🚀", "Viaja al espacio.", "Den første astronauten"],
                ["Atleta", "Utøver", "Olympisk ____", ["Utøver", "Sanger", "Bonde", "Lege"], "🏃", "Practica deportes.", "En sterk utøver"]
            ].map((d, i) => ({ id: 500 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 6, title: "Kropp og Helse", icon: "🏥",
            levels: [
                ["Cabeza", "Hode", "Mitt ____ gjør vondt", ["Hode", "Hånd", "Fot", "Arm"], "👤", "Parte superior.", "Ta på hodet ditt"],
                ["Ojo", "Øye", "Blått ____", ["Øye", "Øre", "Nese", "Munn"], "👁️", "Para ver.", "Et stort øye"],
                ["Oreja", "Øre", "Hør med ____t ditt", ["Øre", "Øye", "Nese", "Munn"], "👂", "Para oír.", "Venstre øre"],
                ["Nariz", "Nese", "Min ____", ["Nese", "Øre", "Øye", "Munn"], "👃", "Para oler.", "En liten nese"],
                ["Boca", "Munn", "Åpne ____en", ["Munn", "Nese", "Øre", "Øye"], "👄", "Para hablar.", "En rød munn"],
                ["Mano", "Hånd", "Vask ____en", ["Hånd", "Fot", "Arm", "Ben"], "✋", "Para tocar.", "Gi meg en hånd"],
                ["Pie", "Fot", "Venstre ____", ["Fot", "Hånd", "Arm", "Ben"], "🦶", "Para caminar.", "På en fot"],
                ["Brazo", "Arm", "Sterk ____", ["Arm", "Ben", "Hånd", "Fot"], "💪", "Extremidad superior.", "Min høyre arm"],
                ["Pierna", "Ben", "Langt ____", ["Ben", "Arm", "Hånd", "Fot"], "🦵", "Extremidad inferior.", "Brekk et ben"],
                ["Corazón", "Hjerte", "Rent ____", ["Hjerte", "Mage", "Hode", "Hånd"], "❤️", "Bómbea sangre.", "Et kaldt hjerte"],
                ["Dedo", "Finger", "Ring____", ["Finger", "Tå", "Hånd", "Fot"], "☝️", "En la mano.", "Ti fingre"],
                ["Espalda", "Rygg", "Min ____", ["Rygg", "Bryst", "Arm", "Ben"], "🧍", "Parte posterior.", "Vond rygg"],
                ["Dolor", "Smerte", "Mye ____", ["Smerte", "Helse", "Medisin", "Lege"], "🤕", "Sensación mala.", "Mye smerte"],
                ["Salud", "Helse", "God ____", ["Helse", "Smerte", "Medisin", "Lege"], "🍏", "Estar bien.", "Helse er rikdom"],
                ["Medicina", "Medisin", "Ta ____en", ["Medisin", "Mat", "Vann", "Melk"], "💊", "Para curarse.", "Legens medisin"],
                ["Sangre", "Blod", "Rødt ____", ["Blod", "Vann", "Melk", "Juice"], "🩸", "Líquido vital.", "Blodbank"],
                ["Hueso", "Ben", "Brukket ____", ["Ben", "Blod", "Smerte", "Helse"], "🦴", "Parte dura interna.", "Et sterkt ben"],
                ["Cuerpo", "Kropp", "Menneske____", ["Kropp", "Hode", "Hånd", "Fot"], "🧍", "Todo nosotros.", "En sunn kropp"],
                ["Sueño", "Søvn", "Trenger ____", ["Søvn", "Mat", "Drikke", "Lek"], "😴", "Descansar de noche.", "Gå og sov"],
                ["Vida", "Liv", "Langt ____", ["Liv", "Helse", "Smerte", "Kropp"], "🌱", "Estar vivos.", "Et godt liv"]
            ].map((d, i) => ({ id: 600 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 7, title: "Vær og Tid", icon: "☁️",
            levels: [
                ["Sol", "Sol", "Varm ____", ["Sol", "Måne", "Regn", "Snø"], "☀️", "Luz del día.", "Solen skinner"],
                ["Lluvia", "Regn", "Kaldt ____", ["Regn", "Sol", "Snø", "Vind"], "🌧️", "Agua del cielo.", "Jeg elsker regn"],
                ["Nieve", "Snø", "Hvit ____", ["Snø", "Regn", "Sol", "Vind"], "❄️", "Agua helada.", "Første snø"],
                ["Viento", "Vind", "Sterk ____", ["Vind", "Regn", "Sol", "Snø"], "💨", "Aire en movimiento.", "Vinden blåser"],
                ["Nube", "Sky", "Hvit ____", ["Sky", "Sol", "Regn", "Måne"], "☁️", "Mucha agua arriba.", "En stor sky"],
                ["Cielo", "Himmel", "Blå ____", ["Himmel", "Sky", "Sol", "Måne"], "🌌", "Arriba nuestro.", "Klar himmel"],
                ["Calor", "Varme", "Det er ____", ["Varme", "Kulde", "Regn", "Snø"], "🔥", "Mucho sol.", "En varm dag"],
                ["Frío", "Kulde", "Det er ____", ["Kulde", "Varme", "Sol", "Vind"], "🥶", "Poca temperatura.", "Kaldt vann"],
                ["Tormenta", "Storm", "Stor ____", ["Storm", "Regn", "Sky", "Vind"], "⛈️", "Lluvia y rayos.", "En sommerstorm"],
                ["Clima", "Vær", "Godt ____", ["Vær", "Sol", "Regn", "Dag"], "🌍", "Estado del aire.", "Hvordan er været?"],
                ["Día", "Dag", "En solrik ____", ["Dag", "Natt", "Morgen", "Kveld"], "☀️", "Luz.", "Ha en fin dag"],
                ["Noche", "Natt", "Stjerneklar ____", ["Natt", "Dag", "Morgen", "Kveld"], "🌙", "Oscuridad.", "God natt"],
                ["Mañana", "Morgen", "God ____", ["Morgen", "Natt", "Dag", "Kveld"], "🌅", "Primeras horas.", "Om morgenen"],
                ["Tarde", "Ettermiddag", "God ____", ["Ettermiddag", "Morgen", "Natt", "Dag"], "🌤️", "Horas medias.", "Hver ettermiddag"],
                ["Semana", "Uke", "Forrige ____", ["Uke", "Måned", "År", "Dag"], "📅", "Siete días.", "Neste uke"],
                ["Mes", "Måned", "Denne ____", ["Måned", "Uke", "År", "Dag"], "🗓️", "Treinta días.", "Hver måned"],
                ["Año", "År", "Nytt ____", ["År", "Måned", "Uke", "Dag"], "🎉", "Doce meses.", "Godt nytt år"],
                ["Hora", "Time", "En ____", ["Time", "Minutt", "Sekund", "Dag"], "⏰", "Sesenta minutos.", "Vent en time"],
                ["Minuto", "Minutt", "Fem ____er", ["Minutt", "Time", "Sekund", "Dag"], "⏱️", "Sesenta segundos.", "Et minutt, takk"],
                ["Segunda", "Sekund", "Vent et ____", ["Sekund", "Minutt", "Time", "Dag"], "⌛", "Tiempo muy corto.", "Vent et sekund"]
            ].map((d, i) => ({ id: 700 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 8, title: "Klær og Butikk", icon: "🛍️",
            levels: [
                ["Camisa", "Skjorte", "Blå ____", ["Skjorte", "Bukse", "Kjole", "Sko"], "👕", "Ropa de arriba.", "En bomullsskjorte"],
                ["Pantalón", "Bukse", "Lang ____", ["Bukse", "Skjorte", "Kjole", "Sko"], "👖", "Ropa de piernas.", "Blå bukser"],
                ["Vestido", "Kjole", "Rød ____", ["Kjole", "Skjorte", "Bukse", "Sko"], "👗", "Ropa de fiesta.", "En vakker kjole"],
                ["Zapato", "Sko", "Svart ____", ["Sko", "Skjorte", "Bukse", "Kjole"], "👞", "Para los pies.", "Løp i sko"],
                ["Gorra", "Hatt", "Kul ____", ["Hatt", "Skjorte", "Bukse", "Kjole"], "🧢", "Para la cabeza.", "Bruk hatt"],
                ["Ropa", "Klær", "Nye ____", ["Klær", "Sko", "Vesker", "Hatt"], "👗", "Todo lo que usamos.", "Rene klær"],
                ["Precio", "Pris", "Høy ____", ["Pris", "Penger", "Regning", "Kostnad"], "💰", "Lo que cuesta.", "Den beste prisen"],
                ["Barato", "Billig", "Veldig ____", ["Billig", "Dyr", "Ny", "Gammel"], "🏷️", "Cuesta poco.", "Billig mat"],
                ["Caro", "Dyr", "Det er ____t", ["Dyr", "Billig", "Ny", "Gammel"], "💎", "Cuesta mucho.", "En dyr bil"],
                ["Comprar", "Kjøpe", "Jeg vil ____", ["Kjøpe", "Selge", "Gi", "Ta"], "🛒", "Adquirir algo.", "Kjøp en gave"],
                ["Vender", "Selge", "Jeg vil ____", ["Selge", "Kjøpe", "Gi", "Ta"], "🏪", "Dar por dinero.", "Selg min bil"],
                ["Chaqueta", "Jakke", "Vinter____", ["Jakke", "Skjorte", "Kåpe", "Kjole"], "🧥", "Para el frío.", "En varm jakke"],
                ["Calcetín", "Sokk", "Venstre ____", ["Sokk", "Sko", "Bukse", "Skjorte"], "🧦", "Debajo del zapato.", "En hvit sokk"],
                ["Gafas", "Briller", "Sol____", ["Briller", "Hatt", "Ring", "Klokke"], "🕶️", "Para los ojos.", "Bruk briller"],
                ["Reloj", "Klokke", "Armbånds____", ["Klokke", "Klokke", "Ring", "Hatt"], "⌚", "Para ver la hora.", "En sølvklokke"],
                ["Bolso", "Veske", "Hånd____", ["Veske", "Eske", "Koffert", "Lomme"], "👜", "Para llevar cosas.", "Bær en veske"],
                ["Cinturón", "Belte", "Lær____", ["Belte", "Bukse", "Skjorte", "Kjole"], "🎗️", "Para ajustar.", "Et svart belte"],
                ["Traje", "Dress", "Svart ____", ["Dress", "Skjorte", "Bukse", "Kjole"], "👔", "Ropa formal.", "Bruk dress"],
                ["Bufanda", "Skjerf", "Langt ____", ["Skjerf", "Hatt", "Kåpe", "Hanske"], "🧣", "Para el cuello.", "Et ullskjerf"],
                ["Guantes", "Hansker", "Et par ____", ["Hansker", "Sokker", "Sko", "Hatter"], "🧤", "Para las manos.", "Varme hansker"]
            ].map((d, i) => ({ id: 800 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 9, title: "Underholdning", icon: "🎮",
            levels: [
                ["Juego", "Spill", "Nytt ____", ["Spill", "Spille", "Sport", "Jobb"], "🎮", "Para divertirse.", "Et morsomt spill"],
                ["Cine", "Kino", "Gå på ____", ["Kino", "Butikk", "Bank", "Park"], "🎬", "Ver películas.", "På kino"],
                ["Cuento", "Historie", "Fortell en ____", ["Historie", "Sang", "Spill", "Teater"], "📚", "Narración.", "En godnatthistorie"],
                ["Música", "Musikk", "Hør på ____", ["Musikk", "Lyd", "Støy", "Stemme"], "🎵", "Sonidos rítmicos.", "Rolig musikk"],
                ["Baile", "Dans", "La oss ____e", ["Dans", "Synge", "Spille", "Løpe"], "💃", "Mover el cuerpo.", "Lær dansen"],
                ["Fiesta", "Fest", "Bursdags____", ["Fest", "Jobb", "Skole", "Hjem"], "🥳", "Celebración.", "En stor fest"],
                ["Película", "Film", "Skummel ____", ["Film", "Bok", "Sang", "Spill"], "🎥", "Historia visual.", "Se en film"],
                ["Radio", "Radio", "På ____", ["Radio", "Telefon", "TV", "Web"], "📻", "Para oír noticias.", "Hør på radio"],
                ["Tele", "TV", "Se på ____", ["TV", "Radio", "Bok", "Spill"], "📺", "Televisión.", "Slå på TV-en"],
                ["Libro", "Bok", "Les en ____", ["Bok", "Penn", "Side", "Bord"], "📖", "Hojas escritas.", "En lang bok"],
                ["Actor", "Skuespiller", "Berømt ____", ["Skuespiller", "Sanger", "Kunstner", "Lege"], "🎭", "Actúa en cine.", "En Hollywood skuespiller"],
                ["Pintura", "Maleri", "Olje____", ["Maleri", "Foto", "Tegning", "Kunst"], "🎨", "Arte con pincel.", "Et vakkert maleri"],
                ["Dibujo", "Tegning", "Blyant____", ["Tegning", "Maleri", "Foto", "Kunst"], "✏️", "Arte con lápiz.", "Lag en tegning"],
                ["Museo", "Museum", "Historie____", ["Museum", "Kino", "Butikk", "Park"], "🏛️", "Donde hay arte.", "Besøk museet"],
                ["Teatro", "Teater", "Gammelt ____", ["Teater", "Kino", "Butikk", "Park"], "🏟️", "Obras en vivo.", "På teateret"],
                ["Concierto", "Konsert", "Rocke____", ["Konsert", "Film", "Spill", "Fest"], "🎸", "Música en vivo.", "Gå på konsert"],
                ["Piano", "Piano", "Spill ____", ["Piano", "Gitar", "Tromme", "Fiolin"], "🎹", "Instrumento de teclas.", "Det store pianoet"],
                ["Guitarra", "Gitar", "Elektrisk ____", ["Gitar", "Piano", "Tromme", "Fiolin"], "🎸", "Instrumento de cuerdas.", "En høylytt gitar"],
                ["Tambor", "Tromme", "Slå på ____", ["Tromme", "Piano", "Gitar", "Fiolin"], "🥁", "Instrumento de percusión.", "En stor tromme"],
                ["Violín", "Fiolin", "Klassisk ____", ["Fiolin", "Piano", "Gitar", "Tromme"], "🎻", "Instrumento delicado.", "Den lille fiolinen"]
            ].map((d, i) => ({ id: 900 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 10, title: "Sport og Fritid", icon: "⚽",
            levels: [
                ["Fútbol", "Fotball", "Spill ____", ["Fotball", "Tennis", "Golf", "Løping"], "⚽", "Con los pies.", "Amerikansk fotball"],
                ["Tenis", "Tennis", "Spill ____", ["Tennis", "Fotball", "Golf", "Løping"], "🎾", "Con raqueta.", "Spill tennis"],
                ["Correr", "Løpe", "Jeg liker å ____", ["Løpe", "Svømme", "Gå", "Hoppe"], "🏃", "Ir rápido a pie.", "Løp fort"],
                ["Nadar", "Svømme", "I bassenget", ["Svømme", "Løpe", "Gå", "Hoppe"], "🏊", "En el agua.", "Svøm som en fisk"],
                ["Golf", "Golf", "Spill ____", ["Golf", "Tennis", "Fotball", "Løping"], "⛳", "Con hoyos.", "Et spill golf"],
                ["Bici", "Sykkel", "Kjør ____", ["Sykkel", "Bil", "Buss", "Tog"], "🚲", "Dos ruedas.", "Min røde sykkel"],
                ["Pelota", "Ball", "Spark ____en", ["Ball", "Kølle", "Nett", "Mål"], "⚽", "Redonda.", "En plastball"],
                ["Equipo", "Lag", "Beste ____", ["Lag", "Spiller", "Spill", "Seier"], "👫", "Grupo unido.", "Et sterkt lag"],
                ["Ganar", "Vinne", "Jeg vil ____", ["Vinne", "Tape", "Uavgjort", "Spille"], "🏆", "Ser el primero.", "Vinn spillet"],
                ["Jugar", "Spille", "La oss ____", ["Spille", "Jobbe", "Sove", "Spise"], "🎮", "Hacer deporte.", "Spill med venner"],
                ["Perder", "Tape", "Ikke ____", ["Tape", "Vinne", "Uavgjort", "Spille"], "😢", "No ser primero.", "Ikke tap"],
                ["Empate", "Uavgjort", "Det er ____", ["Uavgjort", "Seier", "Tap", "Spill"], "🤝", "Iguales.", "Et rettferdig uavgjort"],
                ["Entrenar", "Treene", "Jeg må ____", ["Trene", "Spille", "Jobbe", "Hvile"], "💪", "Practicar.", "Tren hardt"],
                ["Gimnasio", "Treningsstudio", "Gå på ____", ["Treningsstudio", "Butikk", "Bank", "Park"], "🏋️", "Hacer ejercicio.", "På det lokale treningsstudioet"],
                ["Piscina", "Svømmebasseng", "Blått ____", ["Svømmebasseng", "Innsjø", "Hav", "Elv"], "🏊", "Donde nadas.", "Et rent svømmebasseng"],
                ["Estadio", "Stadion", "Stort ____", ["Stadion", "Treningsstudio", "Park", "Kino"], "🏟️", "Donde hay partidos.", "Bystadion"],
                ["Caminar", "Gå", "____ en tur", ["Gå", "Løpe", "Svømme", "Hoppe"], "🚶", "Ir a pie.", "Gå i parken"],
                ["Saltar", "Hoppe", "Jeg kan ____", ["Hoppe", "Løpe", "Svømme", "Gå"], "🦘", "Hacia arriba.", "Hopp høyt"],
                ["Cantar", "Synge", "Prøv å ____", ["Synge", "Danse", "Snakke", "Høre"], "🎤", "Voz musical.", "Syng en sang"],
                ["Reír", "Le", "Alltid ____", ["Le", "Gråte", "Smile", "Sint"], "😂", "Felicidad.", "Le høyt"]
            ].map((d, i) => ({ id: 1000 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 11, title: "Teknologi", icon: "💻",
            levels: [
                ["Compu", "Datamaskin", "Rask ____", ["Datamaskin", "Telefon", "Radio", "TV"], "💻", "Para trabajar.", "Min nye datamaskin"],
                ["Celular", "Mobil", "____telefon", ["Mobil", "Radio", "TV", "Web"], "📱", "En tu mano.", "Ring meg"],
                ["Internet", "Internett", "På ____", ["Internett", "Radio", "TV", "Telefon"], "🌐", "Mundo conectado.", "Søk på Internett"],
                ["Correo", "E-post", "Send en ____", ["E-post", "Brev", "Opprinnelse", "Spill"], "📧", "Mensaje digital.", "Sjekk e-posten min"],
                ["Web", "Nettside", "Besøk en ____", ["Nettside", "E-post", "Telefon", "TV"], "🌍", "Sitio digital.", "En rask nettside"],
                ["Clave", "Passord", "Sikkert ____", ["Passord", "Navn", "Mail", "Ord"], "🔐", "Secreto.", "Hva er passordet?"],
                ["Pantalla", "Skjerm", "Stor ____", ["Skjerm", "Telefon", "Mus", "Tast"], "📺", "Donde ves todo.", "En flatskjerm"],
                ["Teclado", "Tastatur", "Skriv på ____", ["Tastatur", "Mus", "Skjerm", "Telefon"], "⌨️", "Para escribir.", "Et mekanisk tastatur"],
                ["Ratón", "Mus", "PC ____", ["Mus", "Skjerm", "Tast", "Telefon"], "🖱️", "Mueve flecha.", "En trådløs mus"],
                ["Código", "Kode", "Skriv ____", ["Kode", "Ord", "Mail", "Opprinnelse"], "⌨️", "Para programar.", "Lær å kode"],
                ["Robot", "Robot", "Smart ____", ["Robot", "Mann", "Hund", "Katt"], "🤖", "Hombre de metal.", "Den lille roboten"],
                ["Espacio", "Verdensrommet", "Ytre ____", ["Verdensrommet", "Himmel", "Sky", "Sol"], "🚀", "Estrellas y luna.", "Reis i verdensrommet"],
                ["Nave", "Romskip", "Raskt ____", ["Romskip", "Bil", "Buss", "Tog"], "🛸", "Vuela lejos.", "Sølvromskipet"],
                ["Futuro", "Fremtid", "Smart ____", ["Fremtid", "Fortid", "Nå", "I dag"], "⏳", "Lo que vendrá.", "I fremtiden"],
                ["Chip", "Brikke", "Liten ____", ["Brikke", "Kort", "Nøkkel", "Boks"], "💾", "Cerebro digital.", "En silisiumbrikke"],
                ["Cable", "Kabel", "Lang ____", ["Kabel", "Tråd", "Link", "Linje"], "🔌", "Para corriente.", "Plugg inn kabelen"],
                ["Batería", "Batteri", "Fullt ____", ["Batteri", "Makt", "Lav", "Liv"], "🔋", "Energía.", "Lad batteriet"],
                ["Wifi", "Wifi", "Gratis ____", ["Wifi", "Link", "Web", "Nett"], "📶", "Señal sin hilos.", "Hvor er wifi?"],
                ["App", "App", "Mobil ____", ["App", "Spill", "Web", "Mail"], "📱", "Programa de móvil.", "Installer appen"],
                ["Juego", "Videospill", "Video ____", ["Videospill", "App", "Web", "Mail"], "🎮", "Diversión digital.", "Jeg elsker dette videospillet"]
            ].map((d, i) => ({ id: 1100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 12, title: "Følelser", icon: "🔥",
            levels: [
                ["Amor", "Kjærlighet", "Jeg ____ deg", ["Elsker", "Hater", "Liker", "Vil ha"], "❤️", "Sentir mucho.", "Sann kjærlighet"],
                ["Odio", "Hat", "Stopp ____et", ["Hat", "Kjærlighet", "Liker", "Vil ha"], "😠", "Sentir mal.", "Ikke hat"],
                ["Feliz", "Lykkelig", "Føler seg ____", ["Lykkelig", "Trist", "Sint", "Redd"], "😊", "Estar bien.", "Jeg er lykkelig"],
                ["Triste", "Trist", "Vær ikke ____", ["Trist", "Lykkelig", "Sint", "Redd"], "😢", "Estar mal.", "En trist dag"],
                ["Enojo", "Sint", "Slutt å være ____", ["Sint", "Lykkelig", "Trist", "Redd"], "😡", "Mucha rabia.", "Den sinte mannen"],
                ["Miedo", "Frykt", "Ingen ____", ["Frykt", "Kjærlighet", "Håp", "Glede"], "😨", "Susto.", "Møt frykten"],
                ["Paz", "Fred", "Verdens____", ["Fred", "Krig", "Kjærlighet", "Håp"], "🕊️", "Tranquilidad.", "Indre fred"],
                ["Guerra", "Krig", "Stopp ____en", ["Krig", "Fred", "Kjærlighet", "Håp"], "💣", "Conflicto.", "En lang krig"],
                ["Risa", "Latter", "En stor ____", ["Latter", "Gråt", "Smil", "Sinne"], "😄", "Jajaja.", "En høy latter"],
                ["Llantos", "Gråt", "Ikke ____", ["Gråt", "Latter", "Smil", "Sinne"], "😭", "Lágrimas.", "Baby gråter"],
                ["Deseo", "Ønske", "Jeg ____ dette", ["Ønsker", "Liker", "Trenger", "Har"], "💫", "Querer algo.", "Jeg ønsker mer"],
                ["Gusto", "Liker", "Jeg ____ mat", ["Liker", "Elsker", "Ønsker", "Trenger"], "👍", "Agradar.", "Jeg liker pizza"],
                ["Necesidad", "Behov", "Jeg ____ vann", ["Trenger", "Ønsker", "Liker", "Har"], "🆘", "Ser urgente.", "Du trenger hjelp"],
                ["Tener", "Ha", "Jeg ____ en bil", ["Har", "Trenger", "Ønsker", "Liker"], "🤲", "Posesión.", "Jeg har et hus"],
                ["Ser", "Være", "Bare ____", ["Være", "Ha", "Trenge", "Ønske"], "🧘", "Existir.", "Være eller ikke være"],
                ["Amigo", "Venn", "Beste ____", ["Venn", "Fiende", "Gutt", "Jente"], "👫", "Persona cercana.", "En god venn"],
                ["Enemigo", "Fiende", "Drep ____n", ["Fiende", "Venn", "Mann", "Kvinne"], "🦹", "Persona contraria.", "Hold deg unna fienden"],
                ["Familia", "Familie", "Stor ____", ["Familie", "Venn", "Lag", "Gruppe"], "👨‍👩‍👧‍👦", "Parientes.", "Jeg elsker familien min"],
                ["Hogar", "Hjem", "Gå ____", ["Hjem", "Butikk", "Jobb", "Skole"], "🏠", "Donde vives.", "Hjem kjære hjem"],
                ["Mundo", "Verden", "Hele ____", ["Verden", "Hjem", "By", "Land"], "🌍", "Todo el planeta.", "Redd verden"]
            ].map((d, i) => ({ id: 1200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        }
    ]
};
