// === BASE DE DATOS DE LECCIONES: JAPONÉS (ES -> JA) ===
window.courseJa = {
    title: "Curso de Japonés",
    mission: "Misión: Nivel N5 (Principiante)",
    langCode: "ja-JP",
    units: [
        {
            id: 1, title: "Primeros Pasos", icon: "🎌",
            levels: [
                ["Hola", "こんにちは", "____!", ["こんにちは", "さようなら", "水", "パン"], "👋", "Para saludar usa <b>Konnichiwa</b>.", "Konnichiwa!"],
                ["Yo soy", "私は", "____ Alex", ["私は", "あなたは", "彼は", "私たちは"], "👤", "Presentarse con <b>Watashi wa</b>.", "Watashi wa Alex desu"],
                ["Uno", "一", "番号 ____", ["一", "二", "三", "四"], "1️⃣", "El número uno (Ichi).", "Ichi desu"],
                ["Adiós", "さようなら", "____!", ["さようなら", "こんにちは", "お願いします", "ありがとう"], "🏃", "Despedirse con <b>Sayounara</b>.", "Sayounara!"],
                ["Dos", "二", "番号 ____", ["二", "一", "三", "四"], "2️⃣", "El número dos (Ni).", "Ni desu"],
                ["Por favor", "お願いします", "____, 助けて", ["お願いします", "ありがとう", "はい", "いいえ"], "🙏", "Pedir cosas con <b>Onegaishimasu</b>.", "Kohi o onegaishimasu"],
                ["Gracias", "ありがとう", "____ございます", ["ありがとう", "お願いします", "こんにちは", "いいえ"], "✨", "Agradecer con <b>Arigatou</b>.", "Arigatou gozaimasu"],
                ["Tres", "三", "番号 ____", ["三", "二", "一", "四"], "3️⃣", "El número tres (San).", "San desu"],
                ["Sí", "はい", "____, そうです", ["はい", "いいえ", "たぶん", "決して"], "✅", "Afirmar con <b>Hai</b>.", "Hai, sou desu"],
                ["No", "いいえ", "____, 違います", ["いいえ", "はい", "もちろん", "いつも"], "❌", "Negar con <b>Iie</b>.", "Iie, chigaimasu"],
                ["Buenos días", "おはよう", "____ございます", ["おはよう", "こんばんわ", "こんにちは", "もしもし"], "🌅", "Saludo matutino (Ohayou).", "Ohayou gozaimasu"],
                ["Hombre", "男", "その____", ["男", "女", "男の子", "女の子"], "👨", "Vocabulario: Hombre (Otoko).", "Otoko no hito"],
                ["Mujer", "女", "その____", ["女", "男", "女の子", "男の子"], "👩", "Vocabulario: Mujer (Onna).", "Onna no hito"],
                ["Niño", "男の子", "元気な____", ["男の子", "女の子", "男", "女"], "👦", "Vocabulario: Niño (Otokonoko).", "Genki na otokonoko"],
                ["Niña", "女の子", "小さな____", ["女の子", "男の子", "女", "男"], "👧", "Vocabulario: Niña (Onnanoko).", "Chiisana onnanoko"],
                ["Cuatro", "四", "番号 ____", ["四", "三", "五", "六"], "4️⃣", "El número cuatro (Yon/Shi).", "Yon desu"],
                ["Cinco", "五", "番号 ____", ["五", "四", "六", "七"], "5️⃣", "El número cinco (Go).", "Go desu"],
                ["Nombre", "名前", "私の____は...", ["名前", "です", "私", "は"], "📛", "Nombre (Namae).", "Watashi no namae wa..."],
                ["Perro", "犬", "私の____", ["犬", "猫", "鳥", "魚"], "🐶", "Mascotas: Perro (Inu).", "Inu ga suki desu"],
                ["Gato", "猫", "黒い____", ["猫", "犬", "鳥", "ねずみ"], "🐱", "Mascotas: Gato (Neko).", "Kuroi neko"]
            ].map((d, i) => ({ id: 100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 2, title: "La Ciudad", icon: "🏙️",
            levels: [
                ["Casa", "家", "私の____", ["家", "車", "道", "公園"], "🏠", "Donde vives (Ie).", "Ookii ie"],
                ["Auto", "車", "赤い____", ["車", "バス", "電車", "飛行機"], "🚗", "Vehículo común (Kuruma).", "Kuruma ga arimasu"],
                ["Calle", "道", "____で", ["道", "家", "学校", "公園"], "🛣️", "Por donde caminas (Michi).", "Michi wo aruku"],
                ["Parque", "公園", "____で", ["公園", "家", "学校", "銀行"], "🌳", "Lugar verde (Kouen).", "Kouen ni iku"],
                ["Banco", "銀行", "____はどこ?", ["銀行", "カフェ", "公園", "店"], "🏦", "Donde está el dinero (Ginkou).", "Ginkou wa doko desu ka?"],
                ["Tienda", "店", "大きい____", ["店", "家", "公園", "道"], "🏬", "Lugar para comprar (Mise).", "Mise ni iku"],
                ["Escuela", "学校", "____へ行く", ["学校", "店", "銀行", "車"], "🏫", "Lugar de estudio (Gakkou).", "Gakkou e iku"],
                ["Hospital", "病院", "近い____", ["病院", "公園", "カフェ", "銀行"], "🏥", "Salud (Byouin).", "Ookii byouin"],
                ["Café", "カフェ", "____に行こう", ["カフェ", "店", "銀行", "公園"], "☕", "Lugar para beber café (Kafe).", "Kafe de nomu"],
                ["Bus", "バス", "____に乗る", ["バス", "車", "自転車", "タクシー"], "🚌", "Transporte público (Basu).", "Basu ni noru"],
                ["Taxi", "タクシー", "____を呼ぶ", ["タクシー", "バス", "自転車", "飛行機"], "🚕", "Transporte privado (Takushii).", "Takushii de iku"],
                ["Bici", "自転車", "____に乗る", ["自転車", "バス", "車", "タクシー"], "🚲", "Dos ruedas (Jitensha).", "Jitensha ga suki"],
                ["Tren", "電車", "速い____", ["電車", "バス", "飛行機", "車"], "🚆", "Vías de hierro (Densha).", "Densha de iku"],
                ["Avión", "飛行機", "その____", ["飛行機", "車", "船", "バス"], "✈️", "Para volar (Hikouki).", "Hikouki wo miru"],
                ["Barco", "船", "大きな____", ["船", "車", "自転車", "バス"], "🚢", "Por el agua (Fune).", "Fune ni noru"],
                ["Hotel", "ホテル", "高い____", ["ホテル", "家", "銀行", "公園"], "🏨", "Para dormir fuera (Hoteru).", "Hoteru ni tomaru"],
                ["Cine", "映画館", "____で", ["映画館", "公園", "店", "銀行"], "🎬", "Ver películas (Eigakan).", "Eigakan e iku"],
                ["Puente", "橋", "____を渡る", ["橋", "道", "家", "車"], "🌉", "Une dos caminos (Hashi).", "Hashi wo wataru"],
                ["Museo", "博物館", "美術____", ["博物館", "店", "公園", "銀行"], "🏛️", "Historia y arte (Hakubutsukan).", "Hakubutsukan wo miru"],
                ["Policía", "警察", "____を呼ぶ", ["警察", "医者", "消防士", "看護師"], "🚓", "Seguridad (Keisatsu).", "Keisatsu desu"]
            ].map((d, i) => ({ id: 200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 3, title: "El Restaurante", icon: "🍕",
            levels: [
                ["Agua", "水", "____をください", ["水", "ワイン", "ジュース", "牛乳"], "💧", "Bebida básica (Mizu).", "Mizu o kudasai"],
                ["Pan", "パン", "バターと____", ["パン", "ケーキ", "肉", "ご飯"], "🍞", "Para acompañar (Pan).", "Oishii pan"],
                ["Pizza", "ピザ", "____が好き", ["ピザ", "パスタ", "スープ", "サラダ"], "🍕", "Comida italiana (Piza).", "Piza o taberu"],
                ["Carne", "肉", "____を食べる", ["肉", "果物", "パン", "砂糖"], "🥩", "Proteína (Niku).", "Niku ga suki"],
                ["Fruta", "果物", "新鮮な____", ["果物", "肉", "パン", "ご飯"], "🍎", "Sano y dulce (Kudamono).", "Kudamono o taberu"],
                ["Arroz", "ご飯", "鶏肉と____", ["ご飯", "パン", "パスタ", "肉"], "🍚", "Grano común (Gohan).", "Shiroi gohan"],
                ["Ensalada", "サラダ", "緑の____", ["サラダ", "ピザ", "スープ", "肉"], "🥗", "Vegetales mixtos (Sarada).", "Sarada o taberu"],
                ["Sopa", "スープ", "熱い____", ["スープ", "サラダ", "ピザ", "パスタ"], "🥣", "Líquido caliente (Suupu).", "Suupu o nomu"],
                ["Pasta", "パスタ", "イタリアの____", ["パスタ", "ピザ", "スープ", "ご飯"], "🍝", "Fideos y más (Pasuta).", "Pasuta ga suki"],
                ["Leche", "牛乳", "コーヒーと____", ["牛乳", "水", "ジュース", "ワイン"], "🥛", "Bebida blanca (Gyuunyuu).", "Gyuunyuu o nomu"],
                ["Vino", "ワイン", "赤____", ["ワイン", "水", "牛乳", "ビール"], "🍷", "Bebida alcohólica (Wain).", "Aka wain"],
                ["Cerveza", "ビール", "冷たい____", ["ビール", "ワイン", "水", "牛乳"], "🍺", "Bebida de cebada (Biiru).", "Biiru o kudasai"],
                ["Té", "お茶", "熱い____", ["お茶", "コーヒー", "牛乳", "水"], "🍵", "Infusión (Ocha).", "Ocha o nomu"],
                ["Huevo", "卵", "目玉焼き____", ["卵", "パン", "肉", "果物"], "🥚", "Desayuno común (Tamago).", "Tamago ryouri"],
                ["Queso", "チーズ", "ハムと____", ["チーズ", "パン", "肉", "果物"], "🧀", "Producto lácteo (Chiizu).", "Chiizu ga suki"],
                ["Pescado", "魚", "焼き____", ["魚", "肉", "鶏肉", "牛肉"], "🐟", "Del mar (Sakana).", "Sakana o taberu"],
                ["Pollo", "鶏肉", "揚げ____", ["鶏肉", "肉", "魚", "牛肉"], "🍗", "Ave común (Toriniku).", "Toriniku ga suki"],
                ["Postre", "デザート", "チョコ____", ["デザート", "肉", "スープ", "サラダ"], "🍰", "Algo dulce al final (Dezaato).", "Dezaato wa nani?"],
                ["Cena", "夕食", "____を食べる", ["夕食", "昼食", "朝食", "おやつ"], "🍽️", "Comida nocturna (Yuushoku).", "Yuushoku no jikan"],
                ["Cuenta", "お会計", "____お願いします", ["お会計", "メニュー", "テーブル", "食べ物"], "💵", "Para pagar (Okaikei).", "Okaikei onegaishimasu"]
            ].map((d, i) => ({ id: 300 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 4, title: "Viajes", icon: "✈️",
            levels: [
                ["Maleta", "スーツケース", "私の____", ["スーツケース", "鞄", "パスポート", "チケット"], "🧳", "Para llevar ropa (Suutsukeesu).", "Suutsukeesu o tsumeru"],
                ["Pasaporte", "パスポート", "____を見せる", ["パスポート", "チケット", "ID", "お金"], "🛂", "Documento de viaje (Pasupooto).", "Pasupooto desu"],
                ["Boleto", "チケット", "電車の____", ["チケット", "お金", "鞄", "地図"], "🎟️", "Para entrar (Chiketto).", "Chiketto ga arimasu"],
                ["Mapa", "地図", "____を見る", ["地図", "本", "道", "公園"], "🗺️", "Para no perderse (Chizu).", "Chizu wa doko?"],
                ["Dinero", "お金", "____が必要", ["お金", "チケット", "鞄", "プレゼント"], "💵", "Para comprar (Okane).", "Okane ga iru"],
                ["Cámara", "カメラ", "____で撮る", ["カメラ", "電話", "写真", "鞄"], "📷", "Para fotos (Kamera).", "Kamera de toru"],
                ["Playa", "海", "____に行く", ["海", "山", "森", "砂漠"], "🏖️", "Arena y mar (Umi).", "Umi ga suki"],
                ["Montaña", "山", "高い____", ["山", "海", "川", "湖"], "⛰️", "Naturaleza alta (Yama).", "Yama ni noboru"],
                ["Bosque", "森", "緑の____", ["森", "海", "砂漠", "街"], "🌲", "Muchos árboles (Mori).", "Mori no naka"],
                ["Río", "川", "冷たい____", ["川", "海", "湖", "プール"], "🏞️", "Agua corriente (Kawa).", "Kawa no近く"],
                ["Mar", "海", "青い____", ["海", "川", "湖", "プール"], "🌊", "Agua salada (Umi).", "Aoi umi"],
                ["Lago", "湖", "静かな____", ["湖", "海", "川", "雨"], "🛶", "Agua tranquila (Mizuumi).", "Kirei na mizuumi"],
                ["Desierto", "砂漠", "暑い____", ["砂漠", "森", "海", "山"], "🌵", "Mucha arena y sol (Sabaku).", "Sabaku wa atsui"],
                ["Isla", "島", "南の____", ["島", "土地", "街", "村"], "🏝️", "Tierra rodeada de agua (Shima).", "Chiisana shima"],
                ["Ciudad", "都会", "大きな____", ["都会", "村", "家", "農場"], "🏙️", "Muchos edificios (Tokai).", "Tokai ni sumu"],
                ["Pueblo", "村", "小さな____", ["村", "都会", "首都", "州"], "🏡", "Lugar pequeño (Mura).", "Mura ni sumu"],
                ["Mundo", "世界", "____中", ["世界", "惑星", "地球", "地図"], "🌍", "Donde vivimos todos (Sekai).", "Sekai isshuu"],
                ["Sol", "太陽", "____が暑い", ["太陽", "月", "星", "空"], "☀️", "Luz del día (Taiyou).", "Taiyou ga teru"],
                ["Luna", "月", "満____", ["月", "太陽", "星", "空"], "🌙", "Luz de noche (Tsuki).", "Tsuki o miru"],
                ["Estrellas", "星", "たくさんの____", ["星", "太陽", "月", "雲"], "✨", "Puntos de luz (Hoshi).", "Hoshi ga hikaru"]
            ].map((d, i) => ({ id: 400 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 5, title: "Profesiones", icon: "💼",
            levels: [
                ["Doctor", "医者", "____に会う", ["医者", "看護師", "シェフ", "パイロット"], "👨‍⚕️", "Cura a las personas (Isha).", "Kare wa isha desu"],
                ["Chef", "シェフ", "すごい____", ["シェフ", "医者", "運転手", "農家"], "👨‍🍳", "Cocina comida rica (Shefu).", "Resutoran no shefu"],
                ["Piloto", "パイロット", "飛行機の____", ["パイロット", "運転手", "医者", "シェフ"], "👨‍✈️", "Vuela aviones (Pairotto).", "Pairotto ni naru"],
                ["Granjero", "農家", "畑で働く", ["農家", "シェフ", "看護師", "医者"], "👨‍🌾", "Trabaja en el campo (Nouka).", "Nouka no shigoto"],
                ["Policía", "警察官", "____を呼ぶ", ["警察官", "シェフ", "パイロット", "医者"], "👮", "Mantiene la ley (Keisatsukan).", "Keisatsukan desu"],
                ["Bombero", "消防士", "____を呼ぶ", ["消防士", "警察", "シェフ", "パイロット"], "👩‍🚒", "Apaga incendios (Shouboushi).", "Yuukan na shouboushi"],
                ["Maestro", "先生", "私の____", ["先生", "医者", "パイロット", "シェフ"], "👩‍🏫", "Enseña cosas nuevas (Sensei).", "Nihongo no sensei"],
                ["Enfermera", "看護師", "優しい____", ["看護師", "医者", "シェフ", "パイロット"], "👩‍⚕️", "Ayuda en el hospital (Kangoshi).", "Yasashii kangoshi"],
                ["Conductor", "運転手", "タクシー____", ["運転手", "パイロット", "シェフ", "医者"], "👨‍🚀", "Maneja vehículos (Untenshu).", "Basu no untenshu"],
                ["Artista", "芸術家", "有名な____", ["芸術家", "シェフ", "医者", "パイロット"], "🎨", "Crea arte (Geijutsuka).", "Sainou aru geijutsuka"],
                ["Abogado", "弁護士", "____と話す", ["弁護士", "医者", "シェフ", "パイロット"], "⚖️", "Defiende personas (Bengoshi).", "Mio bengoshi"],
                ["Dentista", "歯医者", "____に行く", ["歯医者", "医者", "看護師", "シェフ"], "🦷", "Cuida los dientes (Haisha).", "Haisha ga kirai"],
                ["Cantante", "歌手", "ポップ____", ["歌手", "芸術家", "シェフ", "パイロット"], "🎤", "Canta canciones (Kashu).", "Suki na kashu"],
                ["Bailarín", "ダンサー", "バレエ____", ["ダンサー", "歌手", "芸術家", "シェフ"], "💃", "Baila profesionalmente (Dansaa).", "Hayai dansaa"],
                ["Escritor", "作家", "本の____", ["作家", "芸術家", "先生", "シェフ"], "✍️", "Escribe libros (Sakka).", "Misuterii sakka"],
                ["Fotógrafo", "写真家", "プロの____", ["写真家", "芸術家", "シェフ", "パイロット"], "📷", "Toma fotos (Shashinka).", "Kekkonshiki no shashinka"],
                ["Ingeniero", "エンジニア", "ソフト____", ["エンジニア", "医者", "シェフ", "パイロット"], "🏗️", "Diseña y construye (Enjinia).", "Doboku enjinia"],
                ["Científico", "科学者", "実験室の____", ["科学者", "医者", "シェフ", "先生"], "🧪", "Investiga la ciencia (Kagakusha).", "Crazy kagakusha"],
                ["Astronauta", "宇宙飛行士", "宇宙____", ["宇宙飛行士", "パイロット", "シェフ", "医者"], "🚀", "Viaja al espacio (Uchuuhikoushi).", "Saisho no uchuuhikoushi"],
                ["Atleta", "選手", "オリンピック____", ["選手", "歌手", "農家", "医者"], "🏃", "Practica deportes (Senshu).", "Tsuyoi senshu"]
            ].map((d, i) => ({ id: 500 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 6, title: "Cuerpo y Salud", icon: "🏥",
            levels: [
                ["Cabeza", "頭", "____が痛い", ["頭", "手", "足", "腕"], "👤", "Parte superior (Atama).", "Atama o sawaru"],
                ["Ojo", "目", "青い____", ["目", "耳", "鼻", "口"], "👁️", "Para ver (Me).", "Ookii me"],
                ["Oreja", "耳", "____で聞く", ["耳", "目", "鼻", "口"], "👂", "Para oír (Mimi).", "Hidari no mimi"],
                ["Nariz", "鼻", "私の____", ["鼻", "耳", "目", "口"], "👃", "Para oler (Hana).", "Chiisai hana"],
                ["Boca", "口", "____を開けて", ["口", "鼻", "耳", "目"], "👄", "Para hablar (Kuchi).", "Akai kuchi"],
                ["Mano", "手", "____を洗う", ["手", "足", "腕", "脚"], "✋", "Para tocar (Te).", "Te o kasu"],
                ["Pie", "足", "左____", ["足", "手", "腕", "脚"], "🦶", "Para caminar (Ashi).", "Ashi de aruku"],
                ["Brazo", "腕", "強い____", ["腕", "脚", "手", "足"], "💪", "Extremidad superior (Ude).", "Migi no ude"],
                ["Pierna", "脚", "長い____", ["脚", "腕", "手", "足"], "🦵", "Extremidad inferior (Ashi).", "Ashi o oru"],
                ["Corazón", "心臓", "純粋な____", ["心臓", "胃", "頭", "手"], "❤️", "Bómbea sangre (Shinzou/Kokoro).", "Tsumetai kokoro"],
                ["Dedo", "指", "薬____", ["指", "つま先", "手", "足"], "☝️", "En la mano (Yubi).", "Juppon no yubi"],
                ["Espalda", "背中", "私の____", ["背中", "胸", "腕", "脚"], "🧍", "Parte posterior (Senaka).", "Senaka ga itai"],
                ["Dolor", "痛み", "ひどい____", ["痛み", "健康", "薬", "医者"], "🤕", "Sensación mala (Itami).", "Itami ga aru"],
                ["Salud", "健康", "良い____", ["健康", "痛み", "薬", "医者"], "🍏", "Estar bien (Kenkou).", "Kenkou daiichi"],
                ["Medicina", "薬", "____を飲む", ["薬", "食べ物", "水", "牛乳"], "💊", "Para curarse (Kusuri).", "Isha no kusuri"],
                ["Sangre", "血", "赤い____", ["血", "水", "牛乳", "ジュース"], "🩸", "Líquido vital (Chi).", "Ketsueki ginko"],
                ["Hueso", "骨", "折れた____", ["骨", "血", "痛み", "健康"], "🦴", "Parte dura interna (Hone).", "Tsuyoi hone"],
                ["Cuerpo", "体", "人間の____", ["体", "頭", "手", "足"], "🧍", "Todo nosotros (Karada).", "Genki na karada"],
                ["Sueño", "睡眠", "____が必要", ["睡眠", "食事", "飲み物", "遊び"], "😴", "Descansar de noche (Suimin).", "Yoku neru"],
                ["Vida", "命", "長い____", ["命", "健康", "痛み", "体"], "🌱", "Estar vivos (Inochi).", "Yoi inochi"]
            ].map((d, i) => ({ id: 600 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 7, title: "Clima y Tiempo", icon: "☁️",
            levels: [
                ["Sol", "太陽", "暑い____", ["太陽", "月", "雨", "雪"], "☀️", "Luz del día (Taiyou).", "Taiyou ga atsui"],
                ["Lluvia", "雨", "冷たい____", ["雨", "太陽", "雪", "風"], "🌧️", "Agua del cielo (Ame).", "Ame ga suki"],
                ["Nieve", "雪", "白い____", ["雪", "雨", "太陽", "風"], "❄️", "Agua helada (Yuki).", "Hatsuyuki"],
                ["Viento", "風", "強い____", ["風", "雨", "太陽", "雪"], "💨", "Aire en movimiento (Kaze).", "Kaze ga fuku"],
                ["Nube", "雲", "白い____", ["雲", "太陽", "雨", "月"], "☁️", "Mucha agua arriba (Kumo).", "Ookii kumo"],
                ["Cielo", "空", "青い____", ["空", "雲", "太陽", "月"], "🌌", "Arriba nuestro (Sora).", "Kirei na sora"],
                ["Calor", "暑さ", "すごい____", ["暑さ", "寒さ", "雨", "雪"], "🔥", "Mucho sol (Atsusa).", "Atsui hi"],
                ["Frío", "寒さ", "すごい____", ["寒さ", "暑さ", "太陽", "風"], "🥶", "Poca temperatura (Samusa).", "Tsumetai mizu"],
                ["Tormenta", "嵐", "大きな____", ["嵐", "雨", "雲", "風"], "⛈️", "Lluvia y rayos (Arashi).", "Natsu no arashi"],
                ["Clima", "天気", "良い____", ["天気", "太陽", "雨", "日"], "🌍", "Estado del aire (Tenki).", "Tenki wa dou?"],
                ["Día", "日", "晴れた____", ["日", "夜", "朝", "夕方"], "☀️", "Luz (Hi/Nichi).", "Yoi ichinichi wo"],
                ["Noche", "夜", "星の____", ["夜", "日", "朝", "夕方"], "🌙", "Oscuridad (Yoru).", "Oyasumi"],
                ["Mañana", "朝", "おはよう", ["朝", "夜", "日", "夕方"], "🌅", "Primeras horas (Asa).", "Asa ni"],
                ["Tarde", "午後", "こんにちは", ["午後", "朝", "夜", "日"], "🌤️", "Horas medias (Gogo).", "Mainichi gogo"],
                ["Semana", "週", "先____", ["週", "月", "年", "日"], "📅", "Siete días (Shuu).", "Raishuu"],
                ["Mes", "月", "今____", ["月", "週", "年", "日"], "🗓️", "Treinta días (Tsuki).", "Maitsuki"],
                ["Año", "年", "新____", ["年", "月", "週", "日"], "🎉", "Doce meses (Toshi).", "Akemashite omedetou"],
                ["Hora", "時間", "一____", ["時間", "分", "秒", "日"], "⏰", "Sesenta minutos (Jikan).", "Ichijikan matsu"],
                ["Minuto", "分", "五____", ["分", "時間", "秒", "日"], "⏱️", "Sesenta segundos (Fun).", "Ippun kudasai"],
                ["Segunda", "秒", "一____待って", ["秒", "分", "時間", "日"], "⌛", "Tiempo muy corto (Byou).", "Ichibyou matsu"]
            ].map((d, i) => ({ id: 700 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 8, title: "Ropa y Tienda", icon: "🛍️",
            levels: [
                ["Camisa", "シャツ", "青い____", ["シャツ", "ズボン", "ドレス", "靴"], "👕", "Ropa de arriba (Shatsu).", "Koton no shatsu"],
                ["Pantalón", "ズボン", "長い____", ["ズボン", "シャツ", "ドレス", "靴"], "👖", "Ropa de piernas (Zubon).", "Aoi zubon"],
                ["Vestido", "ドレス", "赤い____", ["ドレス", "シャツ", "ズボン", "靴"], "👗", "Ropa de fiesta (Doresu).", "Kirei na doresu"],
                ["Zapato", "靴", "黒い____", ["靴", "シャツ", "ズボン", "ドレス"], "👞", "Para los pies (Kutsu).", "Kutsu de hashiru"],
                ["Gorra", "帽子", "いい____", ["帽子", "シャツ", "ズボン", "ドレス"], "🧢", "Para la cabeza (Boushi).", "Boushi o kaburu"],
                ["Ropa", "服", "新しい____", ["服", "靴", "鞄", "帽子"], "👗", "Todo lo que usamos (Fuku).", "Kirei na fuku"],
                ["Precio", "価格", "高い____", ["価格", "お金", "請求書", "コスト"], "💰", "Lo que cuesta (Kakaku).", "Iichiban no kakaku"],
                ["Barato", "安い", "とても____", ["安い", "高い", "新しい", "古い"], "🏷️", "Cuesta poco (Yasui).", "Yasui tabemono"],
                ["Caro", "高い", "それは____", ["高い", "安い", "新しい", "古い"], "💎", "Cuesta mucho (Takai).", "Takai kuruma"],
                ["Comprar", "買う", "____たい", ["買う", "売る", "与える", "取る"], "🛒", "Adquirir algo (Kau).", "Purezento o kau"],
                ["Vender", "売る", "____たい", ["売る", "買う", "与える", "取る"], "🏪", "Dar por dinero (Uru).", "Kuruma o uru"],
                ["Chaqueta", "ジャケット", "冬の____", ["ジャケット", "シャツ", "コート", "ドレス"], "🧥", "Para el frío (Jaketto).", "Attakai jaketto"],
                ["Calcetín", "靴下", "左の____", ["靴下", "靴", "ズボン", "シャツ"], "🧦", "Debajo del zapato (Kutsushita).", "Shiroi kutsushita"],
                ["Gafas", "眼鏡", "太陽の____", ["眼鏡", "帽子", "指輪", "時計"], "🕶️", "Para los ojos (Megane).", "Megane o kakeru"],
                ["Reloj", "時計", "腕____", ["時計", "時計", "指輪", "帽子"], "⌚", "Para ver la hora (Tokei).", "Gin no tokei"],
                ["Bolso", "鞄", "手____", ["鞄", "箱", "ケース", "ポケット"], "👜", "Para llevar cosas (Kaban).", "Kaban o motsu"],
                ["Cinturón", "ベルト", "革の____", ["ベルト", "ズボン", "シャツ", "ドレス"], "🎗️", "Para ajustar (Beruto).", "Kuroi beruto"],
                ["Traje", "スーツ", "黒い____", ["スーツ", "シャツ", "ズボン", "ドレス"], "👔", "Ropa formal (Suutsu).", "Suutsu o kiru"],
                ["Bufanda", "マフラー", "長い____", ["マフラー", "帽子", "コート", "手袋"], "🧣", "Para el cuello (Mafuraa).", "Uuru no mafuraa"],
                ["Guantes", "手袋", "一対の____", ["手袋", "靴下", "靴", "帽子"], "🧤", "Para las manos (Tebukuro).", "Attakai tebukuro"]
            ].map((d, i) => ({ id: 800 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 9, title: "Entretenimiento", icon: "🎮",
            levels: [
                ["Juego", "ゲーム", "新しい____", ["ゲーム", "遊び", "スポーツ", "仕事"], "🎮", "Para divertirse (Geemu).", "Tanoshii geemu"],
                ["Cine", "映画館", "____に行く", ["映画館", "店", "銀行", "公園"], "🎬", "Ver películas (Eigakan).", "Eigakan de"],
                ["Cuento", "物語", "____を話す", ["物語", "歌", "ゲーム", "劇"], "📚", "Narración (Monogatari).", "Nerumae no monogatari"],
                ["Música", "音楽", "____を聴く", ["音楽", "音", "騒音", "声"], "🎵", "Sonidos rítmicos (Ongaku).", "Shizuka na ongaku"],
                ["Baile", "ダンス", "____しよう", ["ダンス", "歌う", "遊ぶ", "走る"], "💃", "Mover el cuerpo (Dansu).", "Dansu o narau"],
                ["Fiesta", "パーティー", "誕生日____", ["パーティー", "仕事", "学校", "家"], "🥳", "Celebración (Paatii).", "Ookii paatii"],
                ["Película", "映画", "怖い____", ["映画", "本", "歌", "ゲーム"], "🎥", "Historia visual (Eiga).", "Eiga o miru"],
                ["Radio", "ラジオ", "____で", ["ラジオ", "電話", "TV", "ウェブ"], "📻", "Para oír noticias (Rajio).", "Rajio o kiku"],
                ["Tele", "テレビ", "____を見る", ["テレビ", "ラジオ", "本", "ゲーム"], "📺", "Televisión (Terebi).", "Terebi o tsukeru"],
                ["Libro", "本", "____を読む", ["本", "ペン", "ページ", "机"], "📖", "Hojas escritas (Hon).", "Nagai hon"],
                ["Actor", "俳優", "有名な____", ["俳優", "歌手", "芸術家", "医者"], "🎭", "Actúa en cine (Haiyuu).", "Hariuddo no haiyuu"],
                ["Pintura", "絵画", "油____", ["絵画", "写真", "描画", "芸術"], "🎨", "Arte con pincel (Kaiga).", "Kirei na kaiga"],
                ["Dibujo", "描画", "ペン____", ["描画", "絵画", "写真", "芸術"], "✏️", "Arte con lápiz (Byouga).", "Byouga o suru"],
                ["Museo", "博物館", "歴史____", ["博物館", "映画館", "店", "公園"], "🏛️", "Donde hay arte (Hakubutsukan).", "Hakubutsukan ni iku"],
                ["Teatro", "劇場", "古い____", ["劇場", "映画館", "店", "公園"], "🏟️", "Obras en vivo (Gekijou).", "Gekijou de"],
                ["Concierto", "コンサート", "ロック____", ["コンサート", "映画", "ゲーム", "パーティー"], "🎸", "Música en vivo (Konsaato).", "Konsaato ni iku"],
                ["Piano", "ピアノ", "____を弾く", ["ピアノ", "ギター", "ドラム", "バイオリン"], "🎹", "Instrumento de teclas (Piano).", "Ookii piano"],
                ["Guitarra", "ギター", "エレキ____", ["ギター", "ピアノ", "ドラム", "バイオリン"], "🎸", "Instrumento de cuerdas (Gitaa).", "Urusai gitaa"],
                ["Tambor", "ドラム", "____を叩く", ["ドラム", "ピアノ", "ギター", "バイオリン"], "🥁", "Instrumento de percusión (Doramu).", "Ookii doramu"],
                ["Violín", "バイオリン", "クラシック____", ["バイオリン", "ピアノ", "ギター", "ドラム"], "🎻", "Instrumento delicado (Baiorin).", "Chiisai baiorin"]
            ].map((d, i) => ({ id: 900 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 10, title: "Deporte y Ocio", icon: "⚽",
            levels: [
                ["Fútbol", "サッカー", "____をする", ["サッカー", "テニス", "ゴルフ", "走る"], "⚽", "Con los pies (Sakkaa).", "Amerikan sakkaa"],
                ["Tenis", "テニス", "____をする", ["テニス", "サッカー", "ゴルフ", "走る"], "🎾", "Con raqueta (Tenisu).", "Tenisu o suru"],
                ["Correr", "走る", "____のが好き", ["走る", "泳ぐ", "歩く", "ジャンプ"], "🏃", "Ir rápido a pie (Hashiru).", "Hayaku hashiru"],
                ["Nadar", "泳ぐ", "プールで____", ["泳ぐ", "走る", "歩く", "ジャンプ"], "🏊", "En el agua (Oyogu).", "Sakana no youni oyogu"],
                ["Golf", "ゴルフ", "____をする", ["ゴルフ", "テニス", "サッカー", "走る"], "⛳", "Con hoyos (Gorufu).", "Gorufu no geemu"],
                ["Bici", "自転車", "____に乗る", ["自転車", "車", "バス", "電車"], "🚲", "Dos ruedas (Jitensha).", "Akai jitensha"],
                ["Pelota", "ボール", "____を蹴る", ["ボール", "バット", "ネット", "ゴール"], "⚽", "Redonda (Booru).", "Purasuchikku booru"],
                ["Equipo", "チーム", "最高の____", ["チーム", "選手", "ゲーム", "勝利"], "👫", "Grupo unido (Chiimu).", "Tsuyoi chiimu"],
                ["Ganar", "勝つ", "____たい", ["勝つ", "負ける", "引き分け", "遊ぶ"], "🏆", "Ser el primero (Katsu).", "Geemu ni katsu"],
                ["Jugar", "遊ぶ", "____しよう", ["遊ぶ", "働く", "寝る", "食べる"], "🎮", "Hacer deporte (Asobu).", "Tomodachi to asobu"],
                ["Perder", "負ける", "____ないで", ["負ける", "勝つ", "引き分け", "遊ぶ"], "😢", "No ser primero (Makeru).", "Makenaide"],
                ["Empate", "引き分け", "それは____", ["引き分け", "勝利", "敗北", "ゲーム"], "🤝", "Iguales (Hikiwake).", "Kouhei na hikiwake"],
                ["Entrenar", "練習", "____が必要", ["練習", "遊び", "仕事", "休み"], "💪", "Practicar (Renshuu).", "Isshoukenmei renshuu"],
                ["Gimnasio", "ジム", "____に行く", ["ジム", "店", "銀行", "公園"], "🏋️", "Hacer ejercicio (Jimu).", "Jimu de"],
                ["Piscina", "プール", "青い____", ["プール", "湖", "海", "川"], "🏊", "Donde nadas (Puuru).", "Kirei na puuru"],
                ["Estadio", "スタジアム", "大きな____", ["スタジアム", "ジム", "公園", "映画館"], "🏟️", "Donde hay partidos (Sutajiamu).", "Sutajiamu de"],
                ["Caminar", "歩く", "____こう", ["歩く", "走る", "泳ぐ", "ジャンプ"], "🚶", "Ir a pie (Aruku).", "Kouen o aruku"],
                ["Saltar", "ジャンプ", "____できる", ["ジャンプ", "走る", "泳ぐ", "歩く"], "🦘", "Hacia arriba (Janpu).", "Takaku janpu"],
                ["Cantar", "歌う", "____てみて", ["歌う", "踊る", "話す", "聞く"], "🎤", "Voz musical (Utau).", "Uta o utau"],
                ["Reír", "笑う", "いつも____", ["笑う", "泣く", "微笑む", "怒る"], "😂", "Felicidad (Warau).", "Ookiku warau"]
            ].map((d, i) => ({ id: 1000 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 11, title: "Tecnología", icon: "💻",
            levels: [
                ["Compu", "パソコン", "速い____", ["パソコン", "電話", "ラジオ", "テレビ"], "💻", "Para trabajar (Pasokon).", "Atarashii pasokon"],
                ["Celular", "携帯", "____電話", ["携帯", "ラジオ", "テレビ", "ウェブ"], "📱", "En tu mano (Keitai).", "Denwa shite"],
                ["Internet", "ネット", "____で", ["ネット", "ラジオ", "テレビ", "電話"], "🌐", "Mundo conectado (Netto).", "Netto de sagasu"],
                ["Correo", "メール", "____を送る", ["メール", "手紙", "電話", "ゲーム"], "📧", "Mensaje digital (Meeru).", "Meeru o chekku"],
                ["Web", "ウェブ", "____サイト", ["ウェブ", "メール", "電話", "テレビ"], "🌍", "Sitio digital (Webu).", "Hayai webu"],
                ["Clave", "パスワード", "安全な____", ["パスワード", "名前", "メール", "単語"], "🔐", "Secreto (Pasuwaado).", "Pasuwaado wa nani?"],
                ["Pantalla", "画面", "大きな____", ["画面", "電話", "マウス", "キー"], "📺", "Donde ves todo (Gamen).", "Furatto na gamen"],
                ["Teclado", "キーボード", "____で打つ", ["キーボード", "マウス", "画面", "電話"], "⌨️", "Para escribir (Kiiboodo).", "Mekanikaru kiiboodo"],
                ["Ratón", "マウス", "PCの____", ["マウス", "画面", "キー", "電話"], "🖱️", "Mueve flecha (Mausu).", "Waiyaresu mausu"],
                ["Código", "コード", "____を書く", ["コード", "単語", "メール", "電話"], "⌨️", "Para programar (Koodo).", "Koodo o manabu"],
                ["Robot", "ロボット", "賢い____", ["ロボット", "男", "犬", "猫"], "🤖", "Hombre de metal (Robotto).", "Chiisai robotto"],
                ["Espacio", "宇宙", "外____", ["宇宙", "空", "雲", "太陽"], "🚀", "Estrellas y luna (Uchuu).", "Uchuu ryokou"],
                ["Nave", "宇宙船", "速い____", ["宇宙船", "車", "バス", "電車"], "🛸", "Vuela lejos (Uchuusen).", "Gin no uchuusen"],
                ["Futuro", "未来", "賢い____", ["未来", "過去", "今", "今日"], "⏳", "Lo que vendrá (Mirai).", "Mirai ni"],
                ["Chip", "チップ", "小さな____", ["チップ", "カード", "鍵", "箱"], "💾", "Cerebro digital (Chippu).", "Shirikon chippu"],
                ["Cable", "ケーブル", "長い____", ["ケーブル", "ワイヤー", "リンク", "線"], "🔌", "Para corriente (Keeburu).", "Keeburu o tsunagu"],
                ["Batería", "電池", "フル____", ["電池", "力", "低い", "命"], "🔋", "Energía (Denchi).", "Denchi o juuden"],
                ["Wifi", "ワイファイ", "無料____", ["ワイファイ", "リンク", "ウェブ", "ネット"], "📶", "Señal sin hilos (Waifai).", "Waifai wa doko?"],
                ["App", "アプリ", "スマホ____", ["アプリ", "ゲーム", "ウェブ", "メール"], "📱", "Programa de móvil (Apuri).", "Apuri o ireru"],
                ["Juego", "ゲーム", "ビデオ____", ["ゲーム", "アプリ", "ウェブ", "メール"], "🎮", "Diversión digital (Geemu).", "Kono geemu ga suki"]
            ].map((d, i) => ({ id: 1100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 12, title: "Sentimientos", icon: "🔥",
            levels: [
                ["Amor", "愛", "あなたを____", ["愛してる", "嫌い", "好き", "欲しい"], "❤️", "Sentir mucho (Ai).", "Shinjitsu no ai"],
                ["Odio", "憎しみ", "____をやめて", ["憎しみ", "愛", "好き", "欲しい"], "😠", "Sentir mal (Nikushimi).", "Nikumanaide"],
                ["Feliz", "幸せ", "____を感じる", ["幸せ", "悲しい", "怒り", "恐れ"], "😊", "Estar bien (Shiawase).", "Watashi wa shiawase"],
                ["Triste", "悲しい", "____しないで", ["悲しい", "幸せ", "怒り", "恐れ"], "😢", "Estar mal (Kanashii).", "Kanashii hi"],
                ["Enojo", "怒り", "____をやめて", ["怒り", "幸せ", "悲しい", "恐れ"], "😡", "Mucha rabia (Ikari).", "Okotta otoko"],
                ["Miedo", "恐れ", "____はない", ["恐れ", "愛", "希望", "喜び"], "😨", "Susto (Osore).", "Osore ni tachimukau"],
                ["Paz", "平和", "世界____", ["平和", "戦争", "愛", "希望"], "🕊️", "Tranquilidad (Heiwa).", "Uchi naru heiwa"],
                ["Guerra", "戦争", "____を止める", ["戦争", "平和", "愛", "希望"], "💣", "Conflicto (Sensou).", "Nagai sensou"],
                ["Risa", "笑い", "大きな____", ["笑い", "泣く", "微笑み", "怒り"], "😄", "Jajaja (Warai).", "Ookii warai"],
                ["Llantos", "泣く", "____ないで", ["泣く", "笑う", "微笑む", "怒る"], "😭", "Lágrimas (Naku).", "Akachan ga naku"],
                ["Deseo", "欲しい", "これが____", ["欲しい", "好き", "必要", "持つ"], "💫", "Querer algo (Hoshii).", "Motto hoshii"],
                ["Gusto", "好き", "食べ物が____", ["好き", "愛", "欲しい", "必要"], "👍", "Agradar (Suki).", "Piza ga suki"],
                ["Necesidad", "必要", "水が____", ["必要", "欲しい", "好き", "持つ"], "🆘", "Ser urgente (Hitsuyou).", "Tasuke ga hitsuyou"],
                ["Tener", "持つ", "車を____", ["持つ", "必要", "欲しい", "好き"], "🤲", "Posesión (Motsu).", "Ie o motsu"],
                ["Ser", "ある", "ただ____", ["ある", "持つ", "必要", "欲しい"], "🧘", "Existir (Aru/Iru).", "Ikiru ka shinu ka"],
                ["Amigo", "友達", "親____", ["友達", "敵", "男の子", "女の子"], "👫", "Persona cercana (Tomodachi).", "Ii tomodachi"],
                ["Enemigo", "敵", "____を倒す", ["敵", "友達", "男", "女"], "🦹", "Persona contraria (Teki).", "Teki kara hanareru"],
                ["Familia", "家族", "大家____", ["家族", "友達", "チーム", "グループ"], "👨‍👩‍👧‍👦", "Parientes (Kazoku).", "Kazoku o aisu"],
                ["Hogar", "家", "____に帰る", ["家", "店", "仕事", "学校"], "🏠", "Donde vives (Ie).", "Itoshii waga ya"],
                ["Mundo", "世界", "全____", ["世界", "家", "街", "土地"], "🌍", "Todo el planeta (Sekai).", "Sekai o sukuu"]
            ].map((d, i) => ({ id: 1200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        }
    ]
};
