// === BASE DE DATOS DE LECCIONES: FINLANDÉS (ES -> FI) ===
window.courseFi = {
    title: "Suomen Kurssi",
    mission: "Tehtävä: Taso A1 (Alkeet)",
    langCode: "fi-FI",
    units: [
        {
            id: 1, title: "Ensiaskeleet", icon: "🇫🇮",
            levels: [
                ["Hola", "Hei", "____!", ["Hei", "Hei hei", "Vesi", "Leipä"], "👋", "Para saludar usa <b>Hei</b>.", "Hei!"],
                ["Yo soy", "Minä olen", "____ Alex", ["Minä olen", "Sinä olet", "Hän on", "Me olemme"], "👤", "Presentarse con <b>Minä olen</b>.", "Minä olen Alex"],
                ["Uno", "Yksi", "Numero ____", ["Yksi", "Kaksi", "Kolme", "Neljä"], "1️⃣", "El número uno.", "Yksi kiitos"],
                ["Adiós", "Hei hei", "____!", ["Hei hei", "Hei", "Kiitos", "Ei"], "🏃", "Despedirse con <b>Hei hei</b>.", "Hei hei!"],
                ["Dos", "Kaksi", "Numero ____", ["Kaksi", "Yksi", "Kolme", "Neljä"], "2️⃣", "El número dos.", "Kaksi olutta"],
                ["Por favor", "Ole hyvä", "____, auta minua", ["Ole hyvä", "Kiitos", "Kyllä", "Ei"], "🙏", "Pedir cosas con <b>Ole hyvä</b>.", "Kahvi, ole hyvä"],
                ["Gracias", "Kiitos", "Paljon ____", ["Kiitos", "Ole hyvä", "Hei", "Ei"], "✨", "Agradecer con <b>Kiitos</b>.", "Kiitos paljon"],
                ["Tres", "Kolme", "Numero ____", ["Kolme", "Kaksi", "Yksi", "Neljä"], "3️⃣", "El número tres.", "Kolme koiraa"],
                ["Sí", "Kyllä", "____, olen", ["Kyllä", "Ei", "Ehkä", "Koskaan"], "✅", "Afirmar con <b>Kyllä</b>.", "Kyllä kiitos"],
                ["No", "Ei", "____, kiitos", ["Ei", "Kyllä", "Varmasti", "Aina"], "❌", "Negar con <b>Ei</b>.", "Ei kiitos"],
                ["Buenos días", "Hyvää huomenta", "____!", ["Hyvää huomenta", "Hyvää yötä", "Hei", "Moi"], "🌅", "Saludo matutino.", "Hyvää huomenta!"],
                ["Hombre", "Mies", "Yksi ____", ["Mies", "Nainen", "Poika", "Tyttö"], "👨", "Vocabulario: Hombre.", "Pitkä mies"],
                ["Mujer", "Nainen", "Yksi ____", ["Nainen", "Mies", "Tyttö", "Poika"], "👩", "Vocabulario: Mujer.", "Vahva nainen"],
                ["Niño", "Poika", "Yksi ____", ["Poika", "Tyttö", "Mies", "Nainen"], "👦", "Vocabulario: Niño.", "Iloinen poika"],
                ["Niña", "Tyttö", "Yksi ____", ["Tyttö", "Poika", "Nainen", "Mies"], "👧", "Vocabulario: Niña.", "Pieni tyttö"],
                ["Cuatro", "Neljä", "Numero ____", ["Neljä", "Kolme", "Viisi", "Kuusi"], "4️⃣", "El número cuatro.", "Neljä kirjaa"],
                ["Cinco", "Viisi", "Numero ____", ["Viisi", "Neljä", "Kuusi", "Seitsemän"], "5️⃣", "El número cinco.", "Viisi tähteä"],
                ["Nombre", "Nimi", "Minun ____ni on...", ["Nimi", "On", "Minä", "Olen"], "📛", "Preguntar o decir el nombre.", "Nimeni on Matti"],
                ["Perro", "Koira", "Minun ____ni", ["Koira", "Kissa", "Lintu", "Kala"], "🐶", "Mascotas: Perro.", "Rakastan koiraani"],
                ["Gato", "Kissa", "Minun ____ni", ["Kissa", "Koira", "Lintu", "Hiiri"], "🐱", "Mascotas: Gato.", "Musta kissa"]
            ].map((d, i) => ({ id: 100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 2, title: "Kaupunki", icon: "🏙️",
            levels: [
                ["Casa", "Talo", "Minun ____ni", ["Talo", "Auto", "Katu", "Puisto"], "🏠", "Donde vives.", "Iso taloni"],
                ["Auto", "Auto", "Punainen ____", ["Auto", "Bussi", "Juna", "Lentokone"], "🚗", "Vehículo común.", "Minulla on auto"],
                ["Calle", "Katu", "____lla", ["Katu", "Tie", "Talo", "Puisto"], "🛣️", "Por donde caminas.", "Pääkatu"],
                ["Parque", "Puisto", "____ssa", ["Puisto", "Talo", "Koulu", "Pankki"], "🌳", "Lugar verde.", "Puistossa"],
                ["Banco", "Pankki", "Missä on ____?", ["Pankki", "Kahvila", "Puisto", "Kauppa"], "🏦", "Donde está el dinero.", "Keskuspankki"],
                ["Tienda", "Kauppa", "Iso ____", ["Kauppa", "Talo", "Puisto", "Katu"], "🏬", "Lugar para comprar.", "Apple kauppa"],
                ["Escuela", "Koulu", "Mene ____un", ["Koulu", "Kauppa", "Pankki", "Auto"], "🏫", "Lugar de estudio.", "Koulussa"],
                ["Hospital", "Sairaala", "Lähin ____", ["Sairaala", "Puisto", "Kahvila", "Pankki"], "🏥", "Salud.", "Kaupunginsairaala"],
                ["Café", "Kahvila", "Mennään ____an", ["Kahvila", "Kauppa", "Pankki", "Puisto"], "☕", "Lugar para beber café.", "Pidän tästä kahvilasta"],
                ["Bus", "Bussi", "Ota ____", ["Bussi", "Auto", "Pyörä", "Taksi"], "🚌", "Transporte público.", "Koulubussi"],
                ["Taxi", "Taksi", "Soita ____", ["Taksi", "Bussi", "Pyörä", "Lentokone"], "🚕", "Transporte privado.", "Keltainen taksi"],
                ["Bici", "Pyörä", "Aja ____llä", ["Pyörä", "Bussi", "Auto", "Taksi"], "🚲", "Dos ruedas.", "Uusi pyöräni"],
                ["Tren", "Juna", "Nopea ____", ["Juna", "Bussi", "Lentokone", "Auto"], "🚆", "Vías de hierro.", "Aamujuna"],
                ["Avión", "Lentokone", "Se ____", ["Lentokone", "Auto", "Vene", "Bussi"], "✈️", "Para volar.", "Sininen lentokone"],
                ["Barco", "Vene", "Iso ____", ["Vene", "Auto", "Pyörä", "Bussi"], "🚢", "Por el agua.", "Iso vene"],
                ["Hotel", "Hotelli", "Luksus____", ["Hotelli", "Talo", "Pankki", "Puisto"], "🏨", "Para dormir fuera.", "Yövy hotellissa"],
                ["Cine", "Elokuvateatteri", "____ssa", ["Elokuvateatteri", "Puisto", "Kauppa", "Pankki"], "🎬", "Ver películas.", "Mene elokuviin"],
                ["Puente", "Silta", "Ylitä ____", ["Silta", "Katu", "Tie", "Talo"], "🌉", "Une dos caminos.", "Lontoon silta"],
                ["Museo", "Museo", "Taide____", ["Museo", "Kauppa", "Puisto", "Pankki"], "🏛️", "Historia y arte.", "Vieraile museossa"],
                ["Policía", "Poliisi", "Soita ____lle", ["Poliisi", "Lääkäri", "Palomies", "Sairaanhoitaja"], "🚓", "Seguridad.", "Poliisiasema"]
            ].map((d, i) => ({ id: 200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 3, title: "Ravintola", icon: "🍕",
            levels: [
                ["Agua", "Vesi", "Lasi ____ttä", ["Vettä", "Viiniä", "Mehua", "Maitoa"], "💧", "Bebida básica.", "Tarvitsen vettä"],
                ["Pan", "Leipä", "Voita ja ____ä", ["Leipää", "Kakkua", "Lihaa", "Riisiä"], "🍞", "Para acompañar.", "Tuoretta leipää"],
                ["Pizza", "Pizza", "Pidän ____sta", ["Pizzasta", "Pastasta", "Keitosta", "Salaatista"], "🍕", "Comida italiana.", "Yksi pizza, kiitos"],
                ["Carne", "Liha", "Syö ____a", ["Lihaa", "Hedelmää", "Leipää", "Sokeria"], "🥩", "Proteína.", "Paistettua lihaa"],
                ["Fruta", "Hedelmä", "Tuore ____", ["Hedelmä", "Liha", "Leipä", "Riisi"], "🍎", "Sano y dulce.", "Syö enemmän hedelmiä"],
                ["Arroz", "Riisi", "Kanaa ja ____ä", ["Riisiä", "Leipää", "Pastaa", "Lihaa"], "🍚", "Grano común.", "Valkoista riisiä"],
                ["Ensalada", "Salaatti", "Vihreä ____", ["Salaatti", "Pizza", "Keitto", "Liha"], "🥗", "Vegetales mixtos.", "Tuore salaatti"],
                ["Sopa", "Keitto", "Kuuma ____", ["Keitto", "Salaatti", "Pizza", "Pasta"], "🥣", "Líquido caliente.", "Tomaattikeitto"],
                ["Pasta", "Pasta", "Italialainen ____", ["Pasta", "Pizza", "Keitto", "Riisi"], "🍝", "Fideos y más.", "Rakastan pastaa"],
                ["Leche", "Maito", "Kahvi ____lla", ["Maidolla", "Vedellä", "Mehulla", "Viinillä"], "🥛", "Bebida blanca.", "Kylmää maitoa"],
                ["Vino", "Viini", "Punainen ____", ["Viini", "Vesi", "Maito", "Olut"], "🍷", "Bebida alcohólica.", "Lasi viiniä"],
                ["Cerveza", "Olut", "Kylmä ____", ["Olut", "Viini", "Vesi", "Maito"], "🍺", "Bebida de cebada.", "Kaksi olutta, kiitos"],
                ["Té", "Tee", "Kuuma ____", ["Tee", "Kahvi", "Maito", "Vesi"], "🍵", "Infusión.", "Vihreä tee"],
                ["Huevo", "Kananmuna", "Paistettu ____", ["Kananmuna", "Leipä", "Liha", "Hedelmä"], "🥚", "Desayuno común.", "Yksi muna, kiitos"],
                ["Queso", "Juusto", "Kinkku ja ____", ["Juusto", "Leipä", "Liha", "Hedelmä"], "🧀", "Producto lácteo.", "Rakastan juustoa"],
                ["Pescado", "Kala", "Grillattu ____", ["Kala", "Liha", "Kana", "Naudanliha"], "🐟", "Del mar.", "Tuoretta kalaa"],
                ["Pollo", "Kana", "Paistettu ____", ["Kana", "Liha", "Kala", "Naudanliha"], "🍗", "Ave común.", "Kanaa ja ranskalaisia"],
                ["Postre", "Jälkiruoka", "Suklaa ____ksi", ["Jälkiruoaksi", "Lihaksi", "Keitoksi", "Salaatiksi"], "🍰", "Algo dulce al final.", "Mitä on jälkiruokana?"],
                ["Cena", "Illallinen", "Syö ____", ["Illallinen", "Lounas", "Aamiainen", "Välipala"], "🍽️", "Comida nocturna.", "Syödään illallista"],
                ["Cuenta", "Lasku", "____, kiitos", ["Lasku", "Ruokalista", "Pöytä", "Ruoka"], "💵", "Para pagar.", "Lasku, kiitos"]
            ].map((d, i) => ({ id: 300 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 4, title: "Matkustus", icon: "✈️",
            levels: [
                ["Maleta", "Matkalaukku", "Minun ____ni", ["Matkalaukku", "Laukku", "Passi", "Lippu"], "🧳", "Para llevar ropa.", "Pakkaa matkalaukku"],
                ["Pasaporte", "Passi", "Näytä ____si", ["Passi", "Lippu", "Henkilöllisyystodistus", "Raha"], "🛂", "Documento de viaje.", "Passini on valmis"],
                ["Boleto", "Lippu", "Juna____", ["Lippu", "Raha", "Laukku", "Kartta"], "🎟️", "Para entrar.", "Minulla on lippu"],
                ["Mapa", "Kartta", "Katso ____a", ["Kartta", "Kirja", "Katu", "Puisto"], "🗺️", "Para no perderse.", "Missä kartta on?"],
                ["Dinero", "Raha", "Helppo ____", ["Raha", "Lippu", "Laukku", "Lahja"], "💵", "Para comprar.", "Tarvitsen rahaa"],
                ["Cámara", "Kamera", "Ota ____", ["Kamera", "Puhelin", "Kuva", "Laukku"], "📷", "Para fotos.", "Hymyile kameralle"],
                ["Playa", "Ranta", "____lla", ["Ranta", "Vuori", "Metsä", "Aavikko"], "🏖️", "Arena y mar.", "Rakastan rantaa"],
                ["Montaña", "Vuori", "Korkea ____", ["Vuori", "Ranta", "Joki", "Järvi"], "⛰️", "Naturaleza alta.", "Kiipeä vuorelle"],
                ["Bosque", "Metsä", "Vihreä ____", ["Metsä", "Ranta", "Aavikko", "Kaupunki"], "🌲", "Muchos árboles.", "Metsässä"],
                ["Río", "Joki", "Kylmä ____", ["Joki", "Meri", "Järvi", "Uima-allas"], "🏞️", "Agua corriente.", "Joen lähellä"],
                ["Mar", "Meri", "Sininen ____", ["Meri", "Joki", "Järvi", "Uima-allas"], "🌊", "Agua salada.", "Syvä meri"],
                ["Lago", "Järvi", "Rauhallinen ____", ["Järvi", "Meri", "Joki", "Sade"], "🛶", "Agua tranquila.", "Kaunis järvi"],
                ["Desierto", "Aavikko", "Kuuma ____", ["Aavikko", "Metsä", "Ranta", "Vuori"], "🌵", "Mucha arena y sol.", "Saharan aavikko"],
                ["Isla", "Saari", "Trooppinen ____", ["Saari", "Maa", "Kaupunki", "Kylä"], "🏝️", "Tierra rodeada de agua.", "Yksityinen saari"],
                ["Ciudad", "Kaupunki", "Iso ____", ["Kaupunki", "Kylä", "Talo", "Maatila"], "🏙️", "Muchos edificios.", "Helsingin kaupunki"],
                ["Pueblo", "Kylä", "Pieni ____", ["Kylä", "Kaupunki", "Pääkaupunki", "Osavaltio"], "🏡", "Lugar pequeño.", "Asun kylässä"],
                ["Mundo", "Maailma", "Koko ____", ["Maailma", "Planeetta", "Maa", "Kartta"], "🌍", "Donde vivimos todos.", "Matkusta ympäri maailmaa"],
                ["Sol", "Aurinko", "____ paistaa", ["Aurinko", "Kuu", "Tähdet", "Taivas"], "☀️", "Luz del día.", "Aurinko on kuuma"],
                ["Luna", "Kuu", "Täysi____", ["Kuu", "Aurinko", "Tähdet", "Taivas"], "🌙", "Luz de noche.", "Katso kuuta"],
                ["Estrellas", "Tähdet", "Paljon ____iä", ["Tähdet", "Auringot", "Kuut", "Pilvet"], "✨", "Puntos de luz.", "Tähdet ovat kirkkaita"]
            ].map((d, i) => ({ id: 400 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 5, title: "Ammatit", icon: "💼",
            levels: [
                ["Doctor", "Lääkäri", "Mene ____lle", ["Lääkäri", "Sairaanhoitaja", "Kokki", "Lentäjä"], "👨‍⚕️", "Cura a las personas.", "Hän on lääkäri"],
                ["Chef", "Kokki", "Hyvä ____", ["Kokki", "Lääkäri", "Kuski", "Maanviljelijä"], "👨‍🍳", "Cocina comida rica.", "Ravintolakokki"],
                ["Piloto", "Lentäjä", "Lento____", ["Lentäjä", "Kuski", "Lääkäri", "Kokki"], "👨‍✈️", "Vuela aviones.", "Lentäjä on valmis"],
                ["Granjero", "Maanviljelijä", "Työskentelee tilalla", ["Maanviljelijä", "Kokki", "Sairaanhoitaja", "Lääkäri"], "👨‍🌾", "Trabaja en el campo.", "Maanviljelijällä on lehmiä"],
                ["Policía", "Poliisi", "Soita ____lle", ["Poliisi", "Kokki", "Lentäjä", "Lääkäri"], "👮", "Mantiene la ley.", "Poliisi"],
                ["Bombero", "Palomies", "Soita ____lle", ["Palomies", "Poliisi", "Kokki", "Lentäjä"], "👩‍🚒", "Apaga incendios.", "Rohkea palomies"],
                ["Maestro", "Opettaja", "Minun ____ni", ["Opettaja", "Lääkäri", "Lentäjä", "Kokki"], "👩‍🏫", "Enseña cosas nuevas.", "Suomen opettajani"],
                ["Enfermera", "Sairaanhoitaja", "____ auttaa", ["Sairaanhoitaja", "Lääkäri", "Kokki", "Lentäjä"], "👩‍⚕️", "Ayuda en el hospital.", "Mukava sairaanhoitaja"],
                ["Conductor", "Kuski", "Taksi____", ["Kuski", "Lentäjä", "Kokki", "Lääkäri"], "👨‍🚀", "Maneja vehículos.", "Bussikuski"],
                ["Artista", "Taiteilija", "Kuuluisa ____", ["Taiteilija", "Kokki", "Lääkäri", "Lentäjä"], "🎨", "Crea arte.", "Lahjakas taiteilija"],
                ["Abogado", "Lakimies", "Mene ____lle", ["Lakimies", "Lääkäri", "Kokki", "Lentäjä"], "⚖️", "Defiende personas.", "Minun lakimieheni on hyvä"],
                ["Dentista", "Hammaslääkäri", "Mene ____lle", ["Hammaslääkäri", "Lääkäri", "Sairaanhoitaja", "Kokki"], "🦷", "Cuida los dientes.", "Vihaan hammaslääkäriä"],
                ["Cantante", "Laulaja", "Pop____", ["Laulaja", "Taiteilija", "Kokki", "Lentäjä"], "🎤", "Canta canciones.", "Lempilaulajani"],
                ["Bailarín", "Tanssija", "Baletti____", ["Tanssija", "Laulaja", "Taiteilija", "Kokki"], "💃", "Baila profesionalmente.", "Nopea tanssija"],
                ["Escritor", "Kirjailija", "Kirja____", ["Kirjailija", "Taiteilija", "Opettaja", "Kokki"], "✍️", "Escribe libros.", "Rikoskirjailija"],
                ["Fotógrafo", "Valokuvaaja", "Ammatti____", ["Valokuvaaja", "Taiteilija", "Kokki", "Lentäjä"], "📷", "Toma fotos.", "Hääkuvaaja"],
                ["Ingeniero", "Insinööri", "Ohjelmisto____", ["Insinööri", "Lääkäri", "Kokki", "Lentäjä"], "🏗️", "Diseña y construye.", "Rakennusinsinööri"],
                ["Científico", "Tiedemies", "Laboratorio____", ["Tiedemies", "Lääkäri", "Kokki", "Opettaja"], "🧪", "Investiga la ciencia.", "Hullu tiedemies"],
                ["Astronaut", "Astronautti", "Avaruus____", ["Astronautti", "Lentäjä", "Kokki", "Lääkäri"], "🚀", "Viaja al espacio.", "Ensimmäinen astronautti"],
                ["Atleta", "Urheilija", "Olympia____", ["Urheilija", "Laulaja", "Maanviljelijä", "Lääkäri"], "🏃", "Practica deportes.", "Vahva urheilija"]
            ].map((d, i) => ({ id: 500 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 6, title: "Keho ja Terveys", icon: "🏥",
            levels: [
                ["Cabeza", "Pää", "Minun ____huni sattuu", ["Pää", "Käsi", "Jalka", "Käsivarsi"], "👤", "Parte superior.", "Koske päätäsi"],
                ["Ojo", "Silmä", "Sininen ____", ["Silmä", "Korva", "Nenä", "Suu"], "👁️", "Para ver.", "Iso silmä"],
                ["Oreja", "Korva", "Kuuntele ____llasi", ["Korva", "Silmä", "Nenä", "Suu"], "👂", "Para oír.", "Vasen korva"],
                ["Nariz", "Nenä", "Minun ____ni", ["Nenä", "Korva", "Silmä", "Suu"], "👃", "Para oler.", "Pieni nenä"],
                ["Boca", "Suu", "Avaa ____si", ["Suu", "Nenä", "Korva", "Silmä"], "👄", "Para hablar.", "Punainen suu"],
                ["Mano", "Käsi", "Pese ____si", ["Käsi", "Jalka", "Käsivarsi", "Jalka"], "✋", "Para tocar.", "Anna minulle käsi"],
                ["Pie", "Jalka", "Vasen ____", ["Jalka", "Käsi", "Käsivarsi", "Reisi"], "🦶", "Para caminar.", "Yhdellä jalalla"],
                ["Brazo", "Käsivarsi", "Vahva ____", ["Käsivarsi", "Jalka", "Käsi", "Jalka"], "💪", "Extremidad superior.", "Minun oikea käsivarsi"],
                ["Pierna", "Jalka", "Pitkä ____", ["Jalka", "Käsivarsi", "Käsi", "Jalkaterä"], "🦵", "Extremidad inferior.", "Katkaise jalka"],
                ["Corazón", "Sydän", "Puhdas ____", ["Sydän", "Vatsa", "Pää", "Käsi"], "❤️", "Bómbea sangre.", "Kylmä sydän"],
                ["Dedo", "Sormi", "Nimetön ____", ["Sormi", "Varvas", "Käsi", "Jalka"], "☝️", "En la mano.", "Kymmenen sormea"],
                ["Espalda", "Selkä", "Minun ____ni", ["Selkä", "Rinta", "Käsivarsi", "Jalka"], "🧍", "Parte posterior.", "Kipeä selkä"],
                ["Dolor", "Kipu", "Paljon ____a", ["Kipu", "Terveys", "Lääke", "Lääkäri"], "🤕", "Sensación mala.", "Paljon kipua"],
                ["Salud", "Terveys", "Hyvä ____", ["Terveys", "Kipu", "Lääke", "Lääkäri"], "🍏", "Estar bien.", "Terveys on rikkautta"],
                ["Medicina", "Lääke", "Ota ____si", ["Lääke", "Ruoka", "Vesi", "Maito"], "💊", "Para curarse.", "Lääkärin lääke"],
                ["Sangre", "Veri", "Punainen ____", ["Veri", "Vesi", "Maito", "Mehu"], "🩸", "Líquido vital.", "Veripankki"],
                ["Hueso", "Luu", "Murtunut ____", ["Luu", "Veri", "Kipu", "Terveys"], "🦴", "Parte dura interna.", "Vahva luu"],
                ["Cuerpo", "Keho", "Ihmis____", ["Keho", "Pää", "Käsi", "Jalka"], "🧍", "Todo nosotros.", "Terve keho"],
                ["Sueño", "Uni", "Tarvitsen ____a", ["Uni", "Ruoka", "Juoma", "Leikki"], "😴", "Descansar de noche.", "Mene nukkumaan"],
                ["Vida", "Elämä", "Pitkä ____", ["Elämä", "Terveys", "Kipu", "Keho"], "🌱", "Estar vivos.", "Hyvä elämä"]
            ].map((d, i) => ({ id: 600 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 7, title: "Sää ja Aika", icon: "☁️",
            levels: [
                ["Sol", "Aurinko", "Kuuma ____", ["Aurinko", "Kuu", "Sade", "Lumi"], "☀️", "Luz del día.", "Aurinko paistaa"],
                ["Lluvia", "Sade", "Kylmä ____", ["Sade", "Aurinko", "Lumi", "Tuuli"], "🌧️", "Agua del cielo.", "Rakastan sadetta"],
                ["Nieve", "Lumi", "Valkoinen ____", ["Lumi", "Sade", "Aurinko", "Tuuli"], "❄️", "Agua helada.", "Ensilumi"],
                ["Viento", "Tuuli", "Voimakas ____", ["Tuuli", "Sade", "Aurinko", "Lumi"], "💨", "Aire en movimiento.", "Tuuli puhaltaa"],
                ["Nube", "Pilvi", "Valkoinen ____", ["Pilvi", "Aurinko", "Sade", "Kuu"], "☁️", "Mucha agua arriba.", "Iso pilvi"],
                ["Cielo", "Taivas", "Sininen ____", ["Taivas", "Pilvi", "Aurinko", "Kuu"], "🌌", "Arriba nuestro.", "Kirkas taivas"],
                ["Calor", "Lämpö", "On ____", ["Lämpö", "Kylmyys", "Sade", "Lumi"], "🔥", "Mucho sol.", "Kuuma päivä"],
                ["Frío", "Kylmyys", "On ____", ["Kylmyys", "Lämpö", "Aurinko", "Tuuli"], "🥶", "Poca temperatura.", "Kylmä vesi"],
                ["Tormenta", "Myrsky", "Iso ____", ["Myrsky", "Sade", "Pilvi", "Tuuli"], "⛈️", "Lluvia y rayos.", "Kesämyrsky"],
                ["Clima", "Sää", "Hyvä ____", ["Sää", "Aurinko", "Sade", "Päivä"], "🌍", "Estado del aire.", "Millainen sää on?"],
                ["Día", "Päivä", "Aurinkoinen ____", ["Päivä", "Yö", "Aamu", "Ilta"], "☀️", "Luz.", "Hyvää päivää"],
                ["Noche", "Yö", "Tähtikirkas ____", ["Yö", "Päivä", "Aamu", "Ilta"], "🌙", "Oscuridad.", "Hyvää yötä"],
                ["Mañana", "Aamu", "Hyvää ____a", ["Aamu", "Yö", "Päivä", "Ilta"], "🌅", "Primeras horas.", "Aamulla"],
                ["Tarde", "Iltapäivä", "Hyvää ____ä", ["Iltapäivä", "Aamu", "Yö", "Päivä"], "🌤️", "Horas medias.", "Joka iltapäivä"],
                ["Semana", "Viikko", "Viime ____", ["Viikko", "Kuukausi", "Vuosi", "Päivä"], "📅", "Siete días.", "Ensi viikolla"],
                ["Mes", "Kuukausi", "Tämä ____", ["Kuukausi", "Viikko", "Vuosi", "Päivä"], "🗓️", "Treinta días.", "Joka kuukausi"],
                ["Año", "Vuosi", "Uusi ____", ["Vuosi", "Kuukausi", "Viikko", "Päivä"], "🎉", "Doce meses.", "Hyvää uutta vuotta"],
                ["Hora", "Tunti", "Yksi ____", ["Tunti", "Minuutti", "Sekunti", "Päivä"], "⏰", "Sesenta minutos.", "Odota tunti"],
                ["Minuto", "Minuutti", "Viisi ____a", ["Minuutti", "Tunti", "Sekunti", "Päivä"], "⏱️", "Sesenta segundos.", "Minuutti, kiitos"],
                ["Segunda", "Sekunti", "Odota ____", ["Sekunti", "Minuutti", "Tunti", "Päivä"], "⌛", "Tiempo muy corto.", "Odota sekunti"]
            ].map((d, i) => ({ id: 700 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 8, title: "Vaatteet ja Kauppa", icon: "🛍️",
            levels: [
                ["Camisa", "Paita", "Sininen ____", ["Paita", "Housut", "Mekko", "Kenkä"], "👕", "Ropa de arriba.", "Puuvillapaita"],
                ["Pantalón", "Housut", "Pitkät ____", ["Housut", "Paita", "Mekko", "Kenkä"], "👖", "Ropa de piernas.", "Siniset housut"],
                ["Vestido", "Mekko", "Punainen ____", ["Mekko", "Paita", "Housut", "Kenkä"], "👗", "Ropa de fiesta.", "Kaunis mekko"],
                ["Zapato", "Kenkä", "Musta ____", ["Kenkä", "Paita", "Housut", "Mekko"], "👞", "Para los pies.", "Juokse kengissä"],
                ["Gorra", "Hattu", "Siisti ____", ["Hattu", "Paita", "Housut", "Mekko"], "🧢", "Para la cabeza.", "Pidä hattua"],
                ["Ropa", "Vaatteet", "Uudet ____", ["Vaatteet", "Kengät", "Laukut", "Hattu"], "👗", "Todo lo que usamos.", "Puhtaat vaatteet"],
                ["Precio", "Hinta", "Korkea ____", ["Hinta", "Raha", "Lasku", "Kustannus"], "💰", "Lo que cuesta.", "Paras hinta"],
                ["Barato", "Halpa", "Todella ____", ["Halpa", "Kallis", "Uusi", "Vanha"], "🏷️", "Cuesta poco.", "Halpaa ruokaa"],
                ["Caro", "Kallis", "Se on ____", ["Kallis", "Halpa", "Uusi", "Vanha"], "💎", "Cuesta mucho.", "Kallis auto"],
                ["Comprar", "Ostaa", "Haluan ____", ["Ostaa", "Myydä", "Antaa", "Ottaa"], "🛒", "Adquirir algo.", "Osta lahja"],
                ["Vender", "Myydä", "Haluan ____", ["Myydä", "Ostaa", "Antaa", "Ottaa"], "🏪", "Dar por dinero.", "Myy autoni"],
                ["Chaqueta", "Takki", "Talvi____", ["Takki", "Paita", "Mekko", "Kenkä"], "🧥", "Para el frío.", "Lämmin takki"],
                ["Calcetín", "Sukka", "Vasen ____", ["Sukka", "Kenkä", "Housut", "Paita"], "🧦", "Debajo del zapato.", "Valkoinen sukka"],
                ["Gafas", "Silmälasit", "Aurinko____", ["Silmälasit", "Hattu", "Sormus", "Kello"], "🕶️", "Para los ojos.", "Pidä laseja"],
                ["Reloj", "Kello", "Ranne____", ["Kello", "Silmälasit", "Sormus", "Hattu"], "⌚", "Para ver la hora.", "Hopeakello"],
                ["Bolso", "Laukku", "Käsi____", ["Laukku", "Laatikko", "Matkalaukku", "Tasku"], "👜", "Para llevar cosas.", "Kanna laukkua"],
                ["Cinturón", "Vyö", "Nahka____", ["Vyö", "Housut", "Paita", "Mekko"], "🎗️", "Para ajustar.", "Musta vyö"],
                ["Traje", "Puku", "Musta ____", ["Puku", "Paita", "Housut", "Mekko"], "👔", "Ropa formal.", "Pidä pukua"],
                ["Bufanda", "Huivi", "Pitkä ____", ["Huivi", "Hattu", "Takki", "Käsine"], "🧣", "Para el cuello.", "Villahuivi"],
                ["Guantes", "Käsineet", "Pari ____", ["Käsineet", "Sukat", "Kengät", "Hatut"], "🧤", "Para las manos.", "Lämpimät käsineet"]
            ].map((d, i) => ({ id: 800 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 9, title: "Viihde", icon: "🎮",
            levels: [
                ["Juego", "Peli", "Uusi ____", ["Peli", "Pelata", "Urheilu", "Työ"], "🎮", "Para divertirse.", "Hauska peli"],
                ["Cine", "Elokuvateatteri", "Mene ____iin", ["Elokuvateatteri", "Kauppa", "Pankki", "Puisto"], "🎬", "Ver películas.", "Elokuvissa"],
                ["Cuento", "Tarina", "Kerro ____", ["Tarina", "Laulu", "Peli", "Teatteri"], "📚", "Narración.", "Iltasatu"],
                ["Música", "Musiikki", "Kuuntele ____a", ["Musiikki", "Ääni", "Melu", "Ääni"], "🎵", "Sonidos rítmicos.", "Hiljaista musiikkia"],
                ["Baile", "Tanssi", "Mennään ____maan", ["Tanssi", "Laulaa", "Pelata", "Juosta"], "💃", "Mover el cuerpo.", "Opi tanssi"],
                ["Fiesta", "Juhla", "Syntymäpäivä____", ["Juhla", "Työ", "Koulu", "Koti"], "🥳", "Celebración.", "Iso juhla"],
                ["Película", "Elokuva", "Pelottava ____", ["Elokuva", "Kirja", "Laulu", "Peli"], "🎥", "Historia visual.", "Katso elokuva"],
                ["Radio", "Radio", "____ssa", ["Radio", "Puhelin", "TV", "Web"], "📻", "Para oír noticias.", "Kuuntele radiota"],
                ["Tele", "TV", "Katso ____tä", ["TV", "Radio", "Kirja", "Peli"], "📺", "Televisión.", "Avaa TV"],
                ["Libro", "Kirja", "Lue ____", ["Kirja", "Kynä", "Sivu", "Pöytä"], "📖", "Hojas escritas.", "Pitkä kirja"],
                ["Actor", "Näyttelijä", "Kuuluisa ____", ["Näyttelijä", "Laulaja", "Taiteilija", "Lääkäri"], "🎭", "Actúa en cine.", "Hollywood näyttelijä"],
                ["Pintura", "Maalaus", "Öljy____", ["Maalaus", "Valokuva", "Piirustus", "Taide"], "🎨", "Arte con pincel.", "Kaunis maalaus"],
                ["Dibujo", "Piirustus", "Lyijykynä____", ["Piirustus", "Maalaus", "Valokuva", "Taide"], "✏️", "Arte con lápiz.", "Tee piirustus"],
                ["Museo", "Museo", "Historia____", ["Museo", "Elokuvateatteri", "Kauppa", "Puisto"], "🏛️", "Donde hay arte.", "Vieraile museossa"],
                ["Teatro", "Teatteri", "Vanha ____", ["Teatteri", "Elokuvateatteri", "Kauppa", "Puisto"], "🏟️", "Obras en vivo.", "Teatterissa"],
                ["Concierto", "Konsertti", "Rock ____", ["Konsertti", "Elokuva", "Peli", "Juhla"], "🎸", "Música en vivo.", "Mene konserttiin"],
                ["Piano", "Piano", "Soita ____a", ["Piano", "Kitara", "Rumpu", "Viulu"], "🎹", "Instrumento de teclas.", "Iso piano"],
                ["Guitarra", "Kitara", "Sähkö____", ["Kitara", "Piano", "Rumpu", "Viulu"], "🎸", "Instrumento de cuerdas.", "Kovaääninen kitara"],
                ["Tambor", "Rumpu", "Lyö ____a", ["Rumpu", "Piano", "Kitara", "Viulu"], "🥁", "Instrumento de percusión.", "Iso rumpu"],
                ["Violín", "Viulu", "Klassinen ____", ["Viulu", "Piano", "Kitara", "Rumpu"], "🎻", "Instrumento delicado.", "Pieni viulu"]
            ].map((d, i) => ({ id: 900 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 10, title: "Urheilu ja Vapaa-aika", icon: "⚽",
            levels: [
                ["Fútbol", "Jalkapallo", "Pelaa ____a", ["Jalkapallo", "Tennis", "Golf", "Juoksu"], "⚽", "Con los pies.", "Amerikkalainen jalkapallo"],
                ["Tenis", "Tennis", "Pelaa ____tä", ["Tennis", "Jalkapallo", "Golf", "Juoksu"], "🎾", "Con raqueta.", "Pelaa tennistä"],
                ["Correr", "Juosta", "Tykkään ____", ["Juosta", "Uida", "Kävellä", "Hypätä"], "🏃", "Ir rápido a pie.", "Juokse kovaa"],
                ["Nadar", "Uida", "Altaassa", ["Uida", "Juosta", "Kävellä", "Hypätä"], "🏊", "En el agua.", "Ui kuin kala"],
                ["Golf", "Golf", "Pelaa ____ia", ["Golf", "Tennis", "Jalkapallo", "Juoksu"], "⛳", "Con hoyos.", "Golfpeli"],
                ["Bici", "Pyörä", "Aja ____llä", ["Pyörä", "Auto", "Bussi", "Juna"], "🚲", "Dos ruedas.", "Punainen pyöräni"],
                ["Pelota", "Pallo", "Potkaise ____a", ["Pallo", "Maila", "Verkko", "Maali"], "⚽", "Redonda.", "Muovipallo"],
                ["Equipo", "Joukkue", "Paras ____", ["Joukkue", "Pelaaja", "Peli", "Voitto"], "👫", "Grupo unido.", "Vahva joukkue"],
                ["Ganar", "Voittaa", "Haluan ____", ["Voittaa", "Hävitä", "Tasapeli", "Pelata"], "🏆", "Ser el primero.", "Voita peli"],
                ["Jugar", "Pelata", "Mennään ____maan", ["Pelata", "Työskennellä", "Nukkua", "Syödä"], "🎮", "Hacer deporte.", "Pelaa kavereiden kanssa"],
                ["Perder", "Hävitä", "Älä ____", ["Hävitä", "Voittaa", "Tasapeli", "Pelata"], "😢", "No ser primero.", "Älä häviä"],
                ["Empate", "Tasapeli", "Se on ____", ["Tasapeli", "Voitto", "Tappio", "Peli"], "🤝", "Iguales.", "Reilu tasapeli"],
                ["Entrenar", "Harjoitella", "Minun täytyy ____", ["Harjoitella", "Pelata", "Työskennellä", "Levätä"], "💪", "Practicar.", "Harjoittele kovaa"],
                ["Gimnasio", "Kuntosali", "Mene ____lle", ["Kuntosali", "Kauppa", "Pankki", "Puisto"], "🏋️", "Hacer ejercicio.", "Paikallisella kuntosalilla"],
                ["Piscina", "Uima-allas", "Sininen ____", ["Uima-allas", "Järvi", "Meri", "Joki"], "🏊", "Donde nadas.", "Puhdas uima-allas"],
                ["Estadio", "Stadion", "Iso ____", ["Stadion", "Kuntosali", "Puisto", "Elokuvateatteri"], "🏟️", "Donde hay partidos.", "Kaupunginstadion"],
                ["Caminar", "Kävellä", "Mene ____mään", ["Kävellä", "Juosta", "Uida", "Hypätä"], "🚶", "Ir a pie.", "Kävele puistossa"],
                ["Saltar", "Hypätä", "Voin ____", ["Hypätä", "Juosta", "Uida", "Kävellä"], "🦘", "Hacia arriba.", "Hyppää korkealle"],
                ["Cantar", "Laulaa", "Yritä ____", ["Laulaa", "Tanssia", "Puhua", "Kuulla"], "🎤", "Voz musical.", "Laula laulu"],
                ["Reír", "Nauraa", "Aina ____", ["Nauraa", "Itkeä", "Hymyillä", "Vihainen"], "😂", "Felicidad.", "Naura kovaa"]
            ].map((d, i) => ({ id: 1000 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 11, title: "Teknologia", icon: "💻",
            levels: [
                ["Compu", "Tietokone", "Nopea ____", ["Tietokone", "Puhelin", "Radio", "TV"], "💻", "Para trabajar.", "Uusi tietokoneeni"],
                ["Celular", "Kännykkä", "Matka____", ["Kännykkä", "Radio", "TV", "Web"], "📱", "En tu mano.", "Soita minulle"],
                ["Internet", "Internet", "____issä", ["Internet", "Radio", "TV", "Puhelin"], "🌐", "Mundo conectado.", "Etsi internetistä"],
                ["Correo", "Sähköposti", "Lähetä ____", ["Sähköposti", "Kirje", "Puhelu", "Peli"], "📧", "Mensaje digital.", "Tarkista sähköpostini"],
                ["Web", "Verkkosivu", "Vieraile ____lla", ["Verkkosivu", "Sähköposti", "Puhelin", "TV"], "🌍", "Sitio digital.", "Nopea verkkosivu"],
                ["Clave", "Salasana", "Turvallinen ____", ["Salasana", "Nimi", "Posti", "Sana"], "🔐", "Secreto.", "Mikä on salasana?"],
                ["Pantalla", "Näyttö", "Iso ____", ["Näyttö", "Puhelin", "Hiiri", "Näppäin"], "📺", "Donde ves todo.", "Litteä näyttö"],
                ["Teclado", "Näppäimistö", "Kirjoita ____llä", ["Näppäimistö", "Hiiri", "Näyttö", "Puhelin"], "⌨️", "Para escribir.", "Mekaaninen näppäimistö"],
                ["Ratón", "Hiiri", "PC ____", ["Hiiri", "Näyttö", "Näppäin", "Puhelin"], "🖱️", "Mueve flecha.", "Langaton hiiri"],
                ["Código", "Koodi", "Kirjoita ____a", ["Koodi", "Sana", "Posti", "Puhelu"], "⌨️", "Para programar.", "Opi koodaamaan"],
                ["Robot", "Robotti", "Älykäs ____", ["Robotti", "Mies", "Koira", "Kissa"], "🤖", "Hombre de metal.", "Pieni robotti"],
                ["Espacio", "Avaruus", "Ulko____", ["Avaruus", "Taivas", "Pilvi", "Aurinko"], "🚀", "Estrellas y luna.", "Matkusta avaruudessa"],
                ["Nave", "Avaruusalus", "Nopea ____", ["Avaruusalus", "Auto", "Bussi", "Juna"], "🛸", "Vuela lejos.", "Hopeinen avaruusalus"],
                ["Futuro", "Tulevaisuus", "Älykäs ____", ["Tulevaisuus", "Menneisyys", "Nyt", "Tänään"], "⏳", "Lo que vendrá.", "Tulevaisuudessa"],
                ["Chip", "Siru", "Pieni ____", ["Siru", "Kortti", "Avain", "Laatikko"], "💾", "Cerebro digital.", "Piisiru"],
                ["Cable", "Kaapeli", "Pitkä ____", ["Kaapeli", "Johto", "Linkki", "Linja"], "🔌", "Para corriente.", "Kytke kaapeli"],
                ["Batería", "Akku", "Täysi ____", ["Akku", "Voima", "Matala", "Elämä"], "🔋", "Energía.", "Lataa akku"],
                ["Wifi", "Wifi", "Ilmainen ____", ["Wifi", "Linkki", "Web", "Verkko"], "📶", "Señal sin hilos.", "Missä on wifi?"],
                ["App", "Sovellus", "Mobiili ____", ["Sovellus", "Peli", "Web", "Posti"], "📱", "Programa de móvil.", "Asenna sovellus"],
                ["Juego", "Videopeli", "Video ____", ["Videopeli", "Sovellus", "Web", "Posti"], "🎮", "Diversión digital.", "Rakastan tätä videopeliä"]
            ].map((d, i) => ({ id: 1100 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        },
        {
            id: 12, title: "Tunteet", icon: "🔥",
            levels: [
                ["Amor", "Rakkaus", "Minä ____ sinua", ["Rakastan", "Vihaan", "Pidän", "Haluan"], "❤️", "Sentir mucho.", "Tosi rakkaus"],
                ["Odio", "Viha", "Lopeta ____", ["Viha", "Rakkaus", "Tykkää", "Haluaa"], "😠", "Sentir mal.", "Älä vihaa"],
                ["Feliz", "Onnellinen", "Olo on ____", ["Onnellinen", "Surullinen", "Vihainen", "Pelokas"], "😊", "Estar bien.", "Olen onnellinen"],
                ["Triste", "Surullinen", "Älä ole ____", ["Surullinen", "Onnellinen", "Vihainen", "Pelokas"], "😢", "Estar mal.", "Surullinen päivä"],
                ["Enojo", "Vihainen", "Lopeta olemaan ____", ["Vihainen", "Onnellinen", "Surullinen", "Pelokas"], "😡", "Mucha rabia.", "Vihainen mies"],
                ["Miedo", "Pelko", "Ei ____a", ["Pelko", "Rakkaus", "Toivo", "Ilo"], "😨", "Susto.", "Kohtaa pelko"],
                ["Paz", "Rauha", "Maailman____", ["Rauha", "Sota", "Rakkaus", "Toivo"], "🕊️", "Tranquilidad.", "Sisäinen rauha"],
                ["Guerra", "Sota", "Lopeta ____", ["Sota", "Rauha", "Rakkaus", "Toivo"], "💣", "Conflicto.", "Pitkä sota"],
                ["Risa", "Nauru", "Iso ____", ["Nauru", "Itku", "Hymy", "Viha"], "😄", "Jajaja.", "Kova nauru"],
                ["Llantos", "Itku", "Älä ____", ["Itke", "Naura", "Hymyile", "Suutu"], "😭", "Lágrimas.", "Vauva itkee"],
                ["Deseo", "Halu", "Minä ____ tätä", ["Haluan", "Pidän", "Tarvitsen", "Omaan"], "💫", "Querer algo.", "Haluan lisää"],
                ["Gusto", "Tykkää", "Minä ____ ruoasta", ["Tykkään", "Rakastan", "Haluan", "Tarvitsen"], "👍", "Agradar.", "Tykkään pizzasta"],
                ["Necesidad", "Tarve", "Minä ____ vettä", ["Tarvitsen", "Haluan", "Tykkään", "Omaan"], "🆘", "Ser urgente.", "Tarvitset apua"],
                ["Tener", "Olla", "Minulla ____ auto", ["On", "Tarvitsen", "Haluan", "Tykkään"], "🤲", "Posesión.", "Minulla on talo"],
                ["Ser", "Olla", "Vain ____", ["Olla", "Omistaa", "Tarvita", "Haluta"], "🧘", "Existir.", "Olla vai ei olla"],
                ["Amigo", "Ystävä", "Paras ____", ["Ystävä", "Vihollinen", "Poika", "Tyttö"], "👫", "Persona cercana.", "Hyvä ystävä"],
                ["Enemigo", "Vihollinen", "Tapa ____", ["Vihollinen", "Ystävä", "Mies", "Nainen"], "🦹", "Persona contraria.", "Pysy kaukana vihollisesta"],
                ["Familia", "Perhe", "Iso ____", ["Perhe", "Ystävä", "Joukkue", "Ryhmä"], "👨‍👩‍👧‍👦", "Parientes.", "Rakastan perhettäni"],
                ["Hogar", "Koti", "Mene ____in", ["Kotiin", "Kauppaan", "Töihin", "Kouluun"], "🏠", "Donde vives.", "Oma koti kullan kallis"],
                ["Mundo", "Maailma", "Koko ____", ["Maailma", "Koti", "Kaupunki", "Maa"], "🌍", "Todo el planeta.", "Pelasta maailma"]
            ].map((d, i) => ({ id: 1200 + i + 1, num: i + 1, isPro: i >= 10, title: d[0], ans: d[1], code: d[2], opts: d[3], ic: d[4], theory: { text: d[5], example: d[6], voice: d[6] }, questions: [{ type: "translate", text: `¿Cómo se dice '${d[0]}'?`, answer: d[1], options: d[3], voice: d[1] }] }))
        }
    ]
};
